//! Decode an ADFGVX cipher string
//! The ADFGVX cipher was used by the German Army during World War I. It is a
//! fractionating transposition cipher: a 6x6 Polybius square with the labels
//! A, D, F, G, V, X maps each of the 36 symbols (A-Z and 0-9) to a pair of
//! label letters. This implementation recovers the plaintext from the
//! fractionated stage (without the optional columnar transposition).

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// The 36 symbol alphabet of the ADFGVX cipher (A-Z followed by 0-9).
const ADFGVX_ALPHABET: [char; 36] = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
    'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
];

/// The six label characters used for the square rows and columns.
const LABELS: [char; 6] = ['A', 'D', 'F', 'G', 'V', 'X'];

/// The ADFGVX decoder, call:
/// `let adfgvx_decoder = Decoder::<AdfgvxDecoder>::new()` to create a new instance
/// And then call:
/// `result = adfgvx_decoder.crack(input)` to decode an ADFGVX cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::adfgvx_decoder::AdfgvxDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_adfgvx = Decoder::<AdfgvxDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_adfgvx.crack("AAGDGDAAAFDVAAGDAGAAGVFD", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct AdfgvxDecoder;

impl Crack for Decoder<AdfgvxDecoder> {
    fn new() -> Decoder<AdfgvxDecoder> {
        Decoder {
            name: "ADFGVX",
            description: "The ADFGVX cipher is a fractionating transposition cipher which combined a modified Polybius square with a single columnar transposition. The cipher is named after the six possible letters used in the ciphertext: A, D, F, G, V and X. This implementation recovers the plaintext from the fractionated stage. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/ADFGVX_cipher",
            tags: vec!["polybius", "classical", "fractionated"],
            popularity: 0.35,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying ADFGVX Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        // The fractionated ciphertext only uses the letters A, D, F, G, V, X.
        let clean: String = text
            .chars()
            .filter(|c| c.is_ascii_alphabetic())
            .map(|c| c.to_ascii_uppercase())
            .filter(|c| LABELS.contains(c))
            .collect();
        if clean.len() < 8 || !clean.len().is_multiple_of(2) {
            debug!("Input does not look like an ADFGVX ciphertext (even length of label letters required)");
            return results;
        }

        let decoded = adfgvx_decrypt(&clean);
        if decoded.is_empty() {
            return results;
        }
        let checker_result = checker
            .with_sensitivity(Sensitivity::Medium)
            .check(&decoded);
        if checker_result.is_identified || decoded.len() >= 8 {
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&checker_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decrypt an ADFGVX fractionated ciphertext (a stream of label letters
/// grouped into pairs) into plaintext using the standard alphabet square.
/// Returns an empty string when the input cannot be decrypted.
pub fn adfgvx_decrypt(ciphertext: &str) -> String {
    let clean: Vec<char> = ciphertext
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .map(|c| c.to_ascii_uppercase())
        .filter(|c| LABELS.contains(c))
        .collect();
    if clean.len() < 2 || !clean.len().is_multiple_of(2) {
        return String::new();
    }

    let mut result = String::with_capacity(clean.len() / 2);
    let mut idx = 0;
    while idx + 1 < clean.len() {
        let Some(row) = LABELS.iter().position(|&x| x == clean[idx]) else {
            return String::new();
        };
        let Some(col) = LABELS.iter().position(|&x| x == clean[idx + 1]) else {
            return String::new();
        };
        result.push(ADFGVX_ALPHABET[row * 6 + col]);
        idx += 2;
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str) -> String {
        let mut result = String::new();
        for c in text.chars() {
            let upper = c.to_ascii_uppercase();
            if let Some(pos) = ADFGVX_ALPHABET.iter().position(|&x| x == upper) {
                result.push(LABELS[pos / 6]);
                result.push(LABELS[pos % 6]);
            }
        }
        result
    }

    #[test]
    fn test_adfgvx_roundtrip() {
        let plaintext = "ATTACKATDAWN";
        let ciphertext = encrypt(plaintext);
        assert_eq!(adfgvx_decrypt(&ciphertext), plaintext);
    }

    #[test]
    fn test_adfgvx_known_vector() {
        // A = (0,0) => AA, B = (0,1) => AD, etc.
        assert_eq!(encrypt("AB"), "AAAD");
        assert_eq!(adfgvx_decrypt("AAAD"), "AB");
    }

    #[test]
    fn test_adfgvx_crack() {
        let plaintext = "ATTACKATDAWN";
        let ciphertext = encrypt(plaintext);
        let adfgvx_decoder = Decoder::<AdfgvxDecoder>::new();
        let result = adfgvx_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for ADFGVX decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_adfgvx_empty_input() {
        let adfgvx_decoder = Decoder::<AdfgvxDecoder>::new();
        let result = adfgvx_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_adfgvx_invalid_input() {
        let adfgvx_decoder = Decoder::<AdfgvxDecoder>::new();
        // Contains letters outside the ADFGVX label set.
        let result = adfgvx_decoder
            .crack("HELLOWORLD", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
