//! Decode an Affine cipher string
//! The affine cipher is a monoalphabetic substitution cipher where each letter
//! is mapped to its numeric equivalent, multiplied by a key `a`, and shifted
//! by key `b`. Decryption requires finding the modular multiplicative inverse
//! of `a` modulo 26.
//! This implementation brute-forces all valid key pairs (a, b) where `a` is
//! coprime with 26, giving at most 12 × 26 = 312 attempts.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{info, trace};

/// All integers between 1 and 25 that are coprime with 26. These are the only
/// valid values for the multiplicative key `a` of an affine cipher.
static COPRIME_KEYS: [u8; 12] = [1, 3, 5, 7, 9, 11, 15, 17, 19, 21, 23, 25];

/// The Affine decoder, call:
/// `let affine_decoder = Decoder::<AffineDecoder>::new()` to create a new instance
/// And then call:
/// `result = affine_decoder.crack(input)` to decode an affine cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::affine_decoder::AffineDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_affine = Decoder::<AffineDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_affine.crack("zrwu wu i ucspcz qcuuimc zriz uraelx nc pcsajcpcx ny zrc ihhwvc swfrcp", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "this is a secret message that should be recovered by the affine cipher");
/// ```
pub struct AffineDecoder;

impl Crack for Decoder<AffineDecoder> {
    fn new() -> Decoder<AffineDecoder> {
        Decoder {
            name: "Affine",
            description: "The affine cipher is a type of monoalphabetic substitution cipher, wherein each letter in an alphabet is mapped to its numeric equivalent, encrypted using a simple mathematical function, and converted back to a letter. Each letter is enciphered with the function (a*x + b) mod 26, where a and b are the keys of the cipher. This implementation brute-forces all valid key pairs. Uses Low sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Affine_cipher",
            tags: vec!["substitution", "classical", "auto-crack"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Affine Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());
        let mut decoded_strings = Vec::new();

        // Use the checker with Low sensitivity for the Affine cipher
        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Low);

        for &a in &COPRIME_KEYS {
            let a_inv = mod_inverse(a, 26);
            if a_inv.is_none() {
                continue;
            }
            let a_inv = a_inv.unwrap();
            for b in 0..26u8 {
                // Skip the identity transform (a=1, b=0), which returns the
                // input unchanged and would abort the search early.
                if a == 1 && b == 0 {
                    continue;
                }
                let decoded_text = affine_decrypt(text, a_inv, b);
                decoded_strings.push(decoded_text);
                let borrowed_decoded_text = &decoded_strings[decoded_strings.len() - 1];
                if !check_string_success(borrowed_decoded_text, text) {
                    info!(
                        "Failed to decode affine because check_string_success returned false on string {}. This means the string is 'funny' as it wasn't modified.",
                        borrowed_decoded_text
                    );
                    return results;
                }
                let checker_result = checker_with_sensitivity.check(borrowed_decoded_text);
                // If checkers return true, exit early with the correct result
                if checker_result.is_identified {
                    trace!("Found a match with affine keys a={} b={}", a, b);
                    results.unencrypted_text = Some(vec![borrowed_decoded_text.to_string()]);
                    results.update_checker(&checker_result);
                    results.key = Some(format!("a={}, b={}", a, b));
                    return results;
                }
            }
        }
        results.unencrypted_text = Some(decoded_strings);
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Compute the modular multiplicative inverse of `a` modulo `m`, if it exists.
/// Returns None when `a` and `m` are not coprime.
fn mod_inverse(a: u8, m: u8) -> Option<u8> {
    (1..m).find(|&x| (a as u32 * x as u32) % m as u32 == 1)
}

/// Decrypt a single affine cipher with key (a, b), preserving non-alphabetic
/// characters and the case of each letter.
fn affine_decrypt(cipher: &str, a_inv: u8, b: u8) -> String {
    cipher
        .chars()
        .map(|c| {
            if c.is_ascii_alphabetic() {
                let first = if c.is_ascii_lowercase() { b'a' } else { b'A' };
                let y = c as u8 - first;
                // x = a^-1 * (y - b) mod 26
                let x = ((a_inv as u16 * (y as u16 + 26 - b as u16)) % 26) as u8;
                (first + x) as char
            } else {
                c
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    #[test]
    fn test_affine_decrypt_known_key() {
        // Plaintext "helloworld" with a=5, b=8 => "rcllaoaplx"
        let decoded = affine_decrypt("rcllaoaplx", 21, 8);
        assert_eq!(decoded, "helloworld");
    }

    #[test]
    fn test_mod_inverse() {
        assert_eq!(mod_inverse(5, 26), Some(21));
        assert_eq!(mod_inverse(3, 26), Some(9));
        // 2 is not coprime with 26
        assert_eq!(mod_inverse(2, 26), None);
    }

    #[test]
    fn test_affine_auto_crack() {
        // Longer plaintext so the English checker can identify it.
        let affine_decoder = Decoder::<AffineDecoder>::new();
        let result = affine_decoder
            .crack(
                "zrwu wu i ucspcz qcuuimc zriz uraelx nc pcsajcpcx ny zrc ihhwvc swfrcp",
                &get_athena_checker(),
            )
            .unencrypted_text
            .expect("No unencrypted text for Affine decoder");
        assert_eq!(
            result[0],
            "this is a secret message that should be recovered by the affine cipher"
        );
    }

    #[test]
    fn test_affine_auto_crack_key() {
        let affine_decoder = Decoder::<AffineDecoder>::new();
        let result = affine_decoder
            .crack(
                "zrwu wu i ucspcz qcuuimc zriz uraelx nc pcsajcpcx ny zrc ihhwvc swfrcp",
                &get_athena_checker(),
            )
            .key
            .expect("No key for Affine decoder");
        assert_eq!(result, "a=5, b=8");
    }

    #[test]
    fn test_affine_with_spaces_and_case() {
        // "Hello World" with a=7, b=2 => "Zebbw Awrbx"
        let decoded = affine_decrypt("Zebbw Awrbx", 15, 2);
        assert_eq!(decoded, "Hello World");
    }

    #[test]
    fn test_affine_empty_input() {
        let affine_decoder = Decoder::<AffineDecoder>::new();
        let result = affine_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
