//! Decode an Autokey cipher string
//! The Autokey cipher (also known as the autokey Vigenère cipher) is a
//! polyalphabetic substitution cipher that extends the key by appending the
//! plaintext itself after the initial keyword. This implementation recovers
//! the initial keyword via frequency analysis and then decrypts with the
//! autokey rule.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// English letter frequencies (proportions) for frequency analysis.
static ENGLISH_FREQUENCIES: [f64; 26] = [
    0.08167, 0.01492, 0.02782, 0.04253, 0.12702, 0.02228, 0.02015, 0.06094, 0.06966, 0.00153,
    0.00772, 0.04025, 0.02406, 0.06749, 0.07507, 0.01929, 0.00095, 0.05987, 0.06327, 0.09056,
    0.02758, 0.00978, 0.02360, 0.00150, 0.01974, 0.00074,
];

/// The Autokey decoder, call:
/// `let autokey_decoder = Decoder::<AutokeyDecoder>::new()` to create a new instance
/// And then call:
/// `result = autokey_decoder.crack(input)` to decode an Autokey cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::autokey_decoder::AutokeyDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_autokey = Decoder::<AutokeyDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_autokey.crack("JBMW VL H ZWIKOEEBDM YOOR QPQEKL QGJWTSI LZAZ XAL ANMVOES VWZLCT AWVYCV JFUNN", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct AutokeyDecoder;

impl Crack for Decoder<AutokeyDecoder> {
    fn new() -> Decoder<AutokeyDecoder> {
        Decoder {
            name: "Autokey",
            description: "The Autokey cipher is a polyalphabetic substitution cipher closely related to the Vigenère cipher. It uses a keyword for the start of the key, then appends the plaintext itself to the key. This implementation recovers the keyword via frequency analysis and decrypts using the autokey rule. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Autokey_cipher",
            tags: vec!["substitution", "classical", "auto-crack"],
            popularity: 0.25,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Autokey Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let clean_text: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();

        if clean_text.len() < 10 {
            debug!("Input text too short for Autokey analysis");
            return results;
        }

        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let mut best_result = None;

        for key_length in 1..=10 {
            let keyword = recover_keyword(&clean_text, key_length);
            let decode_attempt = autokey_decrypt(text, &keyword);
            let checker_result = checker_with_sensitivity.check(&decode_attempt);
            if checker_result.is_identified {
                results.unencrypted_text = Some(vec![decode_attempt]);
                results.update_checker(&checker_result);
                results.key = Some(keyword);
                return results;
            }
            if best_result.is_none() {
                best_result = Some((keyword, decode_attempt));
            }
        }

        if let Some((keyword, decoded)) = best_result {
            let checker_result = checker_with_sensitivity.check(&decoded);
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&checker_result);
            results.key = Some(keyword);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decrypt an Autokey cipher. The first `keyword.len()` letters use the keyword
/// as key; thereafter the plaintext already decrypted is used as the key.
fn autokey_decrypt(text: &str, keyword: &str) -> String {
    let clean_text: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();
    let plain_len = clean_text.len();
    if plain_len == 0 {
        return String::new();
    }

    // Build an extended key vector: keyword first, then plaintext letters.
    // Store key values as 0-25 integers (not ASCII bytes) for consistency.
    let mut key_stream: Vec<u8> = keyword
        .bytes()
        .map(|b| b.to_ascii_uppercase() - b'A')
        .collect();
    let mut plaintext_letters: Vec<char> = Vec::with_capacity(plain_len);

    for c in clean_text.chars() {
        let base = if c.is_ascii_uppercase() { b'A' } else { b'a' };
        let cipher_val = (c as u8 - base) as i16;
        // The key stream grows by one letter per plaintext character, so the
        // current index is always valid and equals the number of letters so far.
        let key_val = key_stream[plaintext_letters.len()] as i16;
        // P = (C - K) mod 26
        let new_pos = ((cipher_val - key_val).rem_euclid(26)) as u8;
        let plain_char = (base + new_pos) as char;
        plaintext_letters.push(plain_char);
        key_stream.push(plain_char.to_ascii_uppercase() as u8 - b'A');
    }

    // Rebuild the plaintext preserving non-alphabetic characters.
    let mut result = String::with_capacity(text.len());
    let mut plain_idx = 0;
    for c in text.chars() {
        if c.is_ascii_alphabetic() {
            result.push(plaintext_letters[plain_idx]);
            plain_idx += 1;
        } else {
            result.push(c);
        }
    }
    result
}

/// Recover a keyword of the given length from an Autokey ciphertext.
///
/// In an Autokey cipher the plaintext extends the key, so for positions beyond
/// the keyword the decryption is `P[i] = C[i] - P[i - L]`. Expanding this
/// recurrence shows each plaintext letter at position `j + m*L` equals a known
/// constant `T_m` (derived from the ciphertext) plus `(-1)^m * K[j]`, where
/// `K[j]` is the `j`-th keyword letter. This lets us recover each keyword
/// letter independently by scoring candidate letters against English
/// frequencies.
fn recover_keyword(ciphertext: &str, key_length: usize) -> String {
    let clean: Vec<u8> = ciphertext
        .bytes()
        .filter(|b| b.is_ascii_alphabetic())
        .map(|b| b.to_ascii_uppercase() - b'A')
        .collect();

    let mut keyword = String::with_capacity(key_length);
    for j in 0..key_length {
        // Compute T_m for m = 0, 1, 2, ...
        // T_0 = C[j]; T_m = C[j + m*L] - T_{m-1}
        let mut t_values: Vec<i16> = Vec::new();
        let mut t: i16 = 0;
        let mut m = 0;
        loop {
            let idx = j + m * key_length;
            if idx >= clean.len() {
                break;
            }
            if m == 0 {
                t = clean[idx] as i16;
            } else {
                t = clean[idx] as i16 - t;
            }
            t_values.push(t);
            m += 1;
        }
        if t_values.is_empty() {
            keyword.push('A');
            continue;
        }

        let mut best_score = f64::MIN;
        let mut best_char = 'A';
        for k in 0..26i16 {
            let mut score = 0.0;
            for (m, &t_m) in t_values.iter().enumerate() {
                // P[j + m*L] = T_m + (-1)^(m+1) * K[j]: the sign is negative for
                // even m and positive for odd m.
                let sign: i16 = if m % 2 == 0 { -1 } else { 1 };
                let p = (t_m + sign * k).rem_euclid(26) as usize;
                score += ENGLISH_FREQUENCIES[p];
            }
            if score > best_score {
                best_score = score;
                best_char = (b'A' + k as u8) as char;
            }
        }
        keyword.push(best_char);
    }
    keyword
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str, keyword: &str) -> String {
        let clean_text: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();
        let mut key_stream: Vec<u8> = keyword
            .bytes()
            .map(|b| b.to_ascii_uppercase() - b'A')
            .collect();
        let mut cipher_letters: Vec<char> = Vec::with_capacity(clean_text.len());

        for c in clean_text.chars() {
            let base = if c.is_ascii_uppercase() { b'A' } else { b'a' };
            let plain_val = (c as u8 - base) as i16;
            let key_val = key_stream[cipher_letters.len()] as i16;
            // C = (P + K) mod 26
            let new_pos = ((plain_val + key_val).rem_euclid(26)) as u8;
            let cipher_char = (base + new_pos) as char;
            cipher_letters.push(cipher_char);
            key_stream.push(c.to_ascii_uppercase() as u8 - b'A');
        }

        let mut result = String::with_capacity(text.len());
        let mut cipher_idx = 0;
        for c in text.chars() {
            if c.is_ascii_alphabetic() {
                result.push(cipher_letters[cipher_idx]);
                cipher_idx += 1;
            } else {
                result.push(c);
            }
        }
        result
    }

    #[test]
    fn test_autokey_decrypt_known_key() {
        // "ATTACKATDAWN" with keyword "QUEENLY" (classic example)
        let decrypted = autokey_decrypt("qnxepvytwtwp", "QUEENLY");
        assert_eq!(decrypted, "attackatdawn");
    }

    #[test]
    fn test_autokey_roundtrip() {
        let plaintext = "attackatdawn";
        let keyword = "QUEENLY";
        let ciphertext = encrypt(plaintext, keyword);
        let decrypted = autokey_decrypt(&ciphertext, keyword);
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn test_autokey_auto_crack() {
        let plaintext =
            "this is a reasonably long secret message that the autokey cipher should crack";
        let keyword = "QUEEN";
        let ciphertext = encrypt(plaintext, keyword);
        let autokey_decoder = Decoder::<AutokeyDecoder>::new();
        let result = autokey_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Autokey decoder");
        assert_eq!(result[0].trim(), plaintext);
    }

    #[test]
    fn test_autokey_short_input() {
        let autokey_decoder = Decoder::<AutokeyDecoder>::new();
        let result = autokey_decoder
            .crack("short", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_autokey_empty_input() {
        let autokey_decoder = Decoder::<AutokeyDecoder>::new();
        let result = autokey_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
