//! Decode a Bacon cipher string
//! The Baconian cipher (Bacon's cipher) encodes each letter of the plaintext
//! as a five-bit group using A/B (or 0/1) symbols. This implementation uses
//! the 26-letter alphabet and accepts either `A`/`B` or `0`/`1` as the two
//! symbols.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// The 26-letter Bacon code table, indexed by plaintext letter (A=0, B=1, ...).
const BACON_CODES_26: [&str; 26] = [
    "AAAAA", "AAAAB", "AAABA", "AAABB", "AABAA", "AABAB", "AABBA", "AABBB", "ABAAA", "ABAAB",
    "ABABA", "ABABB", "ABBAA", "ABBAB", "ABBBA", "ABBBB", "BAAAA", "BAAAB", "BAABA", "BAABB",
    "BABAA", "BABAB", "BABBA", "BABBB", "BBAAA", "BBAAB",
];

/// The Baconian decoder, call:
/// `let bacon_decoder = Decoder::<BaconDecoder>::new()` to create a new instance
/// And then call:
/// `result = bacon_decoder.crack(input)` to decode a Bacon cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::bacon_decoder::BaconDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_bacon = Decoder::<BaconDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_bacon.crack("AABAB ABABB AABAA AABAA AAAAA BAABB ABBBA ABBAB AAABA AABAA", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct BaconDecoder;

impl Crack for Decoder<BaconDecoder> {
    fn new() -> Decoder<BaconDecoder> {
        Decoder {
            name: "Bacon's cipher",
            description: "The Baconian cipher, or Bacon's cipher, is a method of steganographic message encoding devised by Francis Bacon in 1605. A message is concealed in the presentation of text, rather than its content. Each letter of the plaintext is replaced by a group of five of the letters 'A' or 'B'. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Bacon%27s_cipher",
            tags: vec!["bacon", "steganography", "classical"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Bacon cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        // Normalise the input: only A/B (or 0/1) groups matter, everything
        // else separates groups.
        let tokens: Vec<&str> = text.split_whitespace().collect();
        if tokens.is_empty() {
            return results;
        }
        let all_valid = tokens.iter().all(|t| {
            t.len() == 5
                && t.chars()
                    .all(|c| matches!(c.to_ascii_uppercase(), 'A' | 'B' | '0' | '1'))
        });
        if !all_valid {
            debug!("Input does not look like a Bacon cipher (5-symbol A/B groups required)");
            return results;
        }

        let decoded = bacon_decrypt(&tokens.join(" "));
        if decoded.is_empty() {
            return results;
        }

        let checker_result = checker
            .with_sensitivity(Sensitivity::Medium)
            .check(&decoded);
        if checker_result.is_identified || decoded.len() >= 8 {
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&checker_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decrypt a Bacon cipher string (space-separated five-symbol groups) into
/// plaintext using the 26-letter Bacon code table. Returns an empty string
/// when the input cannot be decrypted.
pub fn bacon_decrypt(ciphertext: &str) -> String {
    let tokens: Vec<&str> = ciphertext.split_whitespace().collect();
    if tokens.is_empty()
        || !tokens.iter().all(|t| {
            t.len() == 5
                && t.chars()
                    .all(|c| matches!(c.to_ascii_uppercase(), 'A' | 'B' | '0' | '1'))
        })
    {
        return String::new();
    }

    let mut result = String::with_capacity(tokens.len());
    for token in tokens {
        let code: String = token
            .chars()
            .map(|c| match c.to_ascii_uppercase() {
                '0' => 'A',
                '1' => 'B',
                c => c,
            })
            .collect();
        match BACON_CODES_26.iter().position(|&x| x == code) {
            Some(pos) => result.push((b'A' + pos as u8) as char),
            None => return String::new(),
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt_26(text: &str) -> String {
        text.chars()
            .filter(|c| c.is_ascii_alphabetic())
            .map(|c| BACON_CODES_26[(c.to_ascii_uppercase() as u8 - b'A') as usize])
            .collect::<Vec<_>>()
            .join(" ")
    }

    #[test]
    fn test_bacon_roundtrip_26() {
        let plaintext = "HELLO";
        let ciphertext = encrypt_26(plaintext);
        assert_eq!(bacon_decrypt(&ciphertext), plaintext);
    }

    #[test]
    fn test_bacon_known_vector() {
        // A=AAAAA, B=AAAAB, C=AAABA, D=AAABB
        assert_eq!(bacon_decrypt("AAAAA AAAAB AAABA AAABB"), "ABCD");
    }

    #[test]
    fn test_bacon_crack() {
        let plaintext = "FLEEATONCE";
        let ciphertext = encrypt_26(plaintext);
        let bacon_decoder = Decoder::<BaconDecoder>::new();
        let result = bacon_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Bacon decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_bacon_binary_symbols() {
        // 0/1 symbols map to A/B.
        assert_eq!(bacon_decrypt("00000 00001 00010 00011"), "ABCD");
    }

    #[test]
    fn test_bacon_empty_input() {
        let bacon_decoder = Decoder::<BaconDecoder>::new();
        let result = bacon_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_bacon_invalid_input() {
        let bacon_decoder = Decoder::<BaconDecoder>::new();
        // Groups are not all length 5.
        let result = bacon_decoder
            .crack("ABA ABBAB", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
