//! Decode a Base62 string.
//!
//! Base62 uses `0-9A-Za-z` (62 characters). Decoding is done by treating the
//! string as a base-62 big integer and converting to bytes.
//!
//! Call `base62_decoder.crack` to use. It returns option<String> and check
//! with `result.is_some()` to see if it returned okay.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Base62 decoder, call:
/// `let base62_decoder = Decoder::<Base62Decoder>::new()` to create a new instance
/// And then call:
/// `result = base62_decoder.crack(input)` to decode a base62 string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base62_decoder::{Base62Decoder};
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base62 = Decoder::<Base62Decoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_base62.crack("6XPMXvWmo8r", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct Base62Decoder;

impl Crack for Decoder<Base62Decoder> {
    fn new() -> Decoder<Base62Decoder> {
        Decoder {
            name: "Base62",
            description: "Base62 is a binary-to-text encoding scheme that represents binary data using 62 characters (0-9, A-Z, a-z). It is commonly used in URL shorteners and for encoding binary data in text contexts.",
            link: "https://en.wikipedia.org/wiki/Base62",
            tags: vec!["base62", "base", "decoder", "base62"],
            popularity: 0.8,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base62 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let decoded_text = decode_base62_no_error_handling(text);

        if decoded_text.is_none() {
            debug!("Failed to decode base62 because decode_base62_no_error_handling returned None");
            return results;
        }

        let decoded_text = decoded_text.unwrap();
        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode base62 because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode a base62 string into bytes using big-integer arithmetic.
/// Returns None on invalid input.
fn decode_base62_no_error_handling(text: &str) -> Option<String> {
    if text.is_empty() {
        return None;
    }

    // Accumulate the base-62 value as a byte vector (little-endian big int).
    let mut acc: Vec<u8> = vec![0];

    for c in text.chars() {
        let digit = match c {
            '0'..='9' => c as u32 - '0' as u32,
            'A'..='Z' => c as u32 - 'A' as u32 + 10,
            'a'..='z' => c as u32 - 'a' as u32 + 36,
            _ => return None,
        };
        // acc = acc * 62 + digit
        let mut carry = digit;
        for byte in acc.iter_mut() {
            let cur = (*byte as u32) * 62 + carry;
            *byte = (cur & 0xff) as u8;
            carry = cur >> 8;
        }
        while carry > 0 {
            acc.push((carry & 0xff) as u8);
            carry >>= 8;
        }
    }

    // Convert little-endian big int to big-endian bytes, dropping leading zeros.
    while acc.len() > 1 && *acc.last().unwrap() == 0 {
        acc.pop();
    }
    acc.reverse();

    // A base62 string usually encodes an arbitrary byte string. Only produce a
    // String if it's valid UTF-8.
    String::from_utf8(acc).ok()
}

#[cfg(test)]
mod tests {
    use super::Base62Decoder;
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encode_base62(bytes: &[u8]) -> String {
        const ALPHABET: &[u8] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        let mut acc: Vec<u8> = vec![0];
        for &b in bytes {
            // acc = acc * 256 + b
            let mut carry = b as u32;
            for byte in acc.iter_mut() {
                let cur = (*byte as u32) * 256 + carry;
                *byte = (cur & 0xff) as u8;
                carry = cur >> 8;
            }
            while carry > 0 {
                acc.push((carry & 0xff) as u8);
                carry >>= 8;
            }
        }
        // Convert base-256 to base-62
        let mut out: Vec<u8> = Vec::new();
        while acc.len() > 1 || (acc.len() == 1 && acc[0] != 0) {
            let mut carry = 0u32;
            for byte in acc.iter_mut().rev() {
                let cur = (*byte as u32) + (carry << 8);
                *byte = (cur / 62) as u8;
                carry = cur % 62;
            }
            out.push(ALPHABET[carry as usize]);
            while acc.len() > 1 && *acc.last().unwrap() == 0 {
                acc.pop();
            }
        }
        out.reverse();
        String::from_utf8(out).unwrap()
    }

    #[test]
    fn successful_decoding() {
        let input = encode_base62(b"hello world");
        let base62_decoder = Decoder::<Base62Decoder>::new();
        let result = base62_decoder.crack(&input, &get_athena_checker());
        let decoded_str = &result
            .unencrypted_text
            .expect("No unencrypted text for base62");
        assert_eq!(decoded_str[0], "hello world");
    }

    #[test]
    fn base62_decode_empty_string() {
        let base62_decoder = Decoder::<Base62Decoder>::new();
        let result = base62_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn base62_decode_invalid() {
        let base62_decoder = Decoder::<Base62Decoder>::new();
        let result = base62_decoder
            .crack("hello world", &get_athena_checker())
            .unencrypted_text;
        // "hello world" contains a space which is invalid base62, but other
        // chars are valid. It may decode to bytes that aren't UTF-8.
        // Just assert it doesn't panic.
        let _ = result;
    }
}
