//! Decode a Base36 string.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, info, trace};

/// The Base36 decoder, call:
/// `let base36_decoder = Decoder::<Base36Decoder>::new()` to create a new instance
/// And then call:
/// `result = base36_decoder.crack(input)` to decode a base36 string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base36_decoder::Base36Decoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base36 = Decoder::<Base36Decoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_base36.crack("FUVRSIVVNFRBJWAJO", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct Base36Decoder;

impl Crack for Decoder<Base36Decoder> {
    fn new() -> Decoder<Base36Decoder> {
        Decoder {
            name: "Base36",
            description: "Base36 treats 0-9 and A-Z as digits of a base-36 integer and converts the value back to bytes. It is commonly used for compact case-insensitive identifiers.",
            link: "https://en.wikipedia.org/wiki/Base36",
            tags: vec!["base36", "base", "decoder"],
            popularity: 0.7,
            phantom: std::marker::PhantomData,
        }
    }

    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base36 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_base36_no_error_handling(text) else {
            debug!("Failed to decode base36");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!("Failed to decode base36 because check_string_success returned false");
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);
        results
    }

    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    fn get_name(&self) -> &str {
        self.name
    }

    fn get_description(&self) -> &str {
        self.description
    }

    fn get_link(&self) -> &str {
        self.link
    }

    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode a base36 string into UTF-8 text. Returns None on invalid input.
fn decode_base36_no_error_handling(text: &str) -> Option<String> {
    let clean: String = text.chars().filter(|c| !c.is_whitespace()).collect();
    if clean.is_empty() {
        return None;
    }

    let mut acc: Vec<u8> = vec![0];
    for c in clean.chars() {
        let digit = match c {
            '0'..='9' => c as u32 - '0' as u32,
            'A'..='Z' => c as u32 - 'A' as u32 + 10,
            'a'..='z' => c as u32 - 'a' as u32 + 10,
            _ => return None,
        };

        let mut carry = digit;
        for byte in acc.iter_mut() {
            let cur = (*byte as u32) * 36 + carry;
            *byte = (cur & 0xff) as u8;
            carry = cur >> 8;
        }
        while carry > 0 {
            acc.push((carry & 0xff) as u8);
            carry >>= 8;
        }
    }

    while acc.len() > 1 && *acc.last().unwrap_or(&0) == 0 {
        acc.pop();
    }
    acc.reverse();
    String::from_utf8(acc).ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        CheckerTypes::CheckAthena(Checker::<Athena>::new())
    }

    #[test]
    fn successful_decoding() {
        let decoder = Decoder::<Base36Decoder>::new();
        let result = decoder
            .crack("FUVRSIVVNFRBJWAJO", &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for base36");
        assert_eq!(result[0], "hello world");
    }

    #[test]
    fn lowercase_decoding() {
        assert_eq!(
            decode_base36_no_error_handling("fuvrsivvnfrbjwajo"),
            Some("hello world".to_string())
        );
    }

    #[test]
    fn invalid_input_returns_none() {
        assert!(decode_base36_no_error_handling("hello!").is_none());
    }

    #[test]
    fn empty_input_returns_none() {
        let decoder = Decoder::<Base36Decoder>::new();
        assert!(decoder
            .crack("", &get_athena_checker())
            .unencrypted_text
            .is_none());
    }
}
