//! Decode a Base64url string.
//!
//! Base64url (RFC 4648 section 5) is the URL-safe variant of base64 which uses
//! `-` and `_` in place of `+` and `/`. The standard base64 decoder already
//! handles URL-safe input heuristically, but this decoder exists as an explicit
//! variant that only accepts URL-safe characters, avoiding false positives on
//! strings that happen to be valid in both alphabets.
//!
//! Call `base64url_decoder.crack` to use. It returns option<String> and check
//! with `result.is_some()` to see if it returned okay.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use base64::{engine::general_purpose, Engine as _};

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Base64url decoder, call:
/// `let base64url_decoder = Decoder::<Base64UrlDecoder>::new()` to create a new instance
/// And then call:
/// `result = base64url_decoder.crack(input)` to decode a base64url string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base64url_decoder::Base64UrlDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base64url = Decoder::<Base64UrlDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_base64url.crack("YWE-", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "aa>");
/// ```
pub struct Base64UrlDecoder;

impl Crack for Decoder<Base64UrlDecoder> {
    fn new() -> Decoder<Base64UrlDecoder> {
        Decoder {
            name: "Base64url",
            description: "Base64url (RFC 4648 section 5) is the URL-safe variant of base64. It uses - and _ instead of + and / so the output can be used directly in URLs and file names. This decoder only accepts URL-safe alphabets.",
            link: "https://datatracker.ietf.org/doc/html/rfc4648#section-5",
            tags: vec!["base64", "base64url", "url", "base", "decoder", "rfc4648"],
            popularity: 0.8,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base64url with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        // Only attempt when URL-safe characters are present, to avoid
        // duplicating the standard base64 decoder's behaviour.
        if !text.contains('-') && !text.contains('_') {
            debug!("Base64url decoder skipped: no URL-safe characters present");
            return results;
        }

        let decoded_text = decode_base64url_no_error_handling(text);

        if decoded_text.is_none() {
            debug!("Failed to decode base64url because decode_base64url_no_error_handling returned None");
            return results;
        }
        trace!("Base64url decoded: {:?}", decoded_text);

        let decoded_text = decoded_text.unwrap();
        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode base64url because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// helper function for url-safe base64
fn decode_base64url_no_error_handling(text: &str) -> Option<String> {
    let text = text.replace('=', "");
    general_purpose::URL_SAFE_NO_PAD
        .decode(text.as_bytes())
        .ok()
        .map(|inner| String::from_utf8(inner).ok())?
}

#[cfg(test)]
mod tests {
    use super::Base64UrlDecoder;
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    #[test]
    fn successful_decoding() {
        // This input contains '-', so the URL-safe variant is required.
        // Standard base64 would need 'YWE+' here.
        let decoder = Decoder::<Base64UrlDecoder>::new();
        let result = decoder.crack("YWE-", &get_athena_checker());
        let decoded_str = &result
            .unencrypted_text
            .expect("No unencrypted text for base64url");
        assert_eq!(decoded_str[0], "aa>");
    }

    #[test]
    fn successful_decoding_with_underscore() {
        // This input contains '_' which standard base64 would reject.
        // Standard base64 would need 'YWE/' here.
        let decoder = Decoder::<Base64UrlDecoder>::new();
        let result = decoder.crack("YWE_", &get_athena_checker());
        let decoded_str = &result
            .unencrypted_text
            .expect("No unencrypted text for base64url");
        assert_eq!(decoded_str[0], "aa?");
    }

    #[test]
    fn skip_when_no_url_safe_chars() {
        let decoder = Decoder::<Base64UrlDecoder>::new();
        let result = decoder
            .crack("aGVsbG8gd29ybGQ=", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn base64url_decode_empty_string() {
        let decoder = Decoder::<Base64UrlDecoder>::new();
        let result = decoder.crack("", &get_athena_checker()).unencrypted_text;
        assert!(result.is_none());
    }
}
