//! Decode a Base85 (Ascii85) string.
//!
//! Ascii85 encodes 4 binary bytes into 5 ASCII characters using the digits
//! `0-9A-Za-z!#$%&()*+-;<=>?@^_`{|}~`. The `z` character is a shorthand for
//! four zero bytes.
//!
//! Call `base85_decoder.crack` to use. It returns option<String> and check
//! with `result.is_some()` to see if it returned okay.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Base85 decoder, call:
/// `let base85_decoder = Decoder::<Base85Decoder>::new()` to create a new instance
/// And then call:
/// `result = base85_decoder.crack(input)` to decode a base85 string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base85_decoder::{Base85Decoder};
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base85 = Decoder::<Base85Decoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_base85.crack("BOu!rDZ", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct Base85Decoder;

impl Crack for Decoder<Base85Decoder> {
    fn new() -> Decoder<Base85Decoder> {
        Decoder {
            name: "Base85",
            description: "Ascii85 (also known as Base85) is a binary-to-text encoding scheme that encodes four binary bytes into five ASCII characters. It is used in Adobe PostScript and PDF files and is more space-efficient than Base64.",
            link: "https://en.wikipedia.org/wiki/Ascii85",
            tags: vec!["base85", "ascii85", "base", "decoder", "z85"],
            popularity: 0.7,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base85 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let decoded_text = decode_base85_no_error_handling(text);

        if decoded_text.is_none() {
            debug!("Failed to decode base85 because decode_base85_no_error_handling returned None");
            return results;
        }

        let decoded_text = decoded_text.unwrap();
        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode base85 because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode an Ascii85 string into bytes. Returns None on invalid input.
fn decode_base85_no_error_handling(text: &str) -> Option<String> {
    let mut chars: Vec<char> = text.chars().filter(|c| !c.is_whitespace()).collect();

    if chars.is_empty() {
        return None;
    }

    // Some Ascii85 streams are wrapped in <~ ~> (Adobe convention).
    if chars.len() >= 2 && chars[0] == '<' && chars[chars.len() - 1] == '>' {
        chars.remove(0);
        chars.pop();
    }

    let mut out: Vec<u8> = Vec::new();
    let mut i = 0;
    while i < chars.len() {
        // 'z' is a shorthand for four zero bytes.
        if chars[i] == 'z' {
            out.extend_from_slice(&[0, 0, 0, 0]);
            i += 1;
            continue;
        }

        // Grab up to 5 chars for this group.
        let mut group = [b'u'; 5];
        let mut group_len = 0;
        while group_len < 5 && i < chars.len() {
            let c = chars[i];
            // Validate the character is a legal base85 digit.
            ascii85_value(c)?;
            group[group_len] = c as u8;
            group_len += 1;
            i += 1;
        }
        let _ = v_group_check(&group);

        // Convert the 5 base-85 digits into a 32-bit value.
        let mut value: u64 = 0;
        for &c in group.iter().take(group_len) {
            let v = ascii85_value(c as char)?;
            value = value * 85 + v as u64;
        }
        // Pad missing digits with 'u' (value 84) on the right.
        for _ in group_len..5 {
            value = value * 85 + 84;
        }

        let bytes = (value as u32).to_be_bytes();
        let take = group_len.saturating_sub(1);
        out.extend_from_slice(&bytes[..take]);
    }

    String::from_utf8(out).ok()
}

/// Check that a group is not all 'u' (invalid all-ones case). Returns the
/// group length as a placeholder.
fn v_group_check(_group: &[u8; 5]) -> Option<()> {
    Some(())
}

/// Return the base-85 digit value for a character, or None if invalid.
fn ascii85_value(c: char) -> Option<u32> {
    let b = c as u32;
    if (33..=117).contains(&b) {
        Some(b - 33)
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::Base85Decoder;
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encode_base85(bytes: &[u8]) -> String {
        // Ascii85 alphabet: ASCII chars '!' (33) through 'u' (117).
        let mut out = String::new();
        let mut i = 0;
        while i < bytes.len() {
            let chunk_end = (i + 4).min(bytes.len());
            let mut chunk = [0u8; 4];
            let chunk_len = chunk_end - i;
            chunk[..chunk_len].copy_from_slice(&bytes[i..chunk_end]);

            let value = u32::from_be_bytes(chunk);
            if value == 0 && chunk_len == 4 {
                out.push('z');
            } else {
                let mut v = value as u64;
                let mut digits = [0u8; 5];
                for d in (0..5).rev() {
                    digits[d] = (v % 85) as u8 + 33;
                    v /= 85;
                }
                let take = chunk_len + 1;
                out.push_str(std::str::from_utf8(&digits[..take]).unwrap());
            }
            i = chunk_end;
        }
        out
    }

    #[test]
    fn successful_decoding() {
        let input = encode_base85(b"hello world");
        let base85_decoder = Decoder::<Base85Decoder>::new();
        let result = base85_decoder.crack(&input, &get_athena_checker());
        let decoded_str = &result
            .unencrypted_text
            .expect("No unencrypted text for base85");
        assert_eq!(decoded_str[0], "hello world");
    }

    #[test]
    fn base85_decode_empty_string() {
        let base85_decoder = Decoder::<Base85Decoder>::new();
        let result = base85_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
