//! Decode a Base32hex string.
//!
//! Base32hex (Crockford-like variant used by RFC 4648 section 7) uses the
//! alphabet `0-9A-V`. It is frequently used in DNSSEC and other
//! standards-conformant contexts where the RFC 4648 base32 alphabet is not
//! allowed.
//!
//! Call `base32hex_decoder.crack` to use. It returns option<String> and check
//! with `result.is_some()` to see if it returned okay.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use data_encoding::BASE32HEX;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Base32hex decoder, call:
/// `let base32hex_decoder = Decoder::<Base32HexDecoder>::new()` to create a new instance
/// And then call:
/// `result = base32hex_decoder.crack(input)` to decode a base32hex string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base32hex_decoder::Base32HexDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base32hex = Decoder::<Base32HexDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_base32hex.crack("D1IMOR3F41RMUSJCCG", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct Base32HexDecoder;

impl Crack for Decoder<Base32HexDecoder> {
    fn new() -> Decoder<Base32HexDecoder> {
        Decoder {
            name: "Base32hex",
            description: "Base32hex is a base32 encoding variant defined in RFC 4648 section 7 that uses the extended hex alphabet (0-9, A-V). Unlike the standard base32 alphabet it avoids ambiguous characters, making it useful in DNSSEC and other contexts.",
            link: "https://datatracker.ietf.org/doc/html/rfc4648#section-7",
            tags: vec!["base32", "base32hex", "base", "decoder", "rfc4648"],
            popularity: 0.6,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base32hex with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let decoded_text = decode_base32hex_no_error_handling(text);

        if decoded_text.is_none() {
            debug!("Failed to decode base32hex because decode_base32hex_no_error_handling returned None");
            return results;
        }

        let decoded_text = decoded_text.unwrap();
        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode base32hex because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode a Base32hex string. Returns None on failure.
fn decode_base32hex_no_error_handling(text: &str) -> Option<String> {
    let cleaned: String = text.chars().filter(|c| !c.is_whitespace()).collect();
    if cleaned.is_empty() {
        return None;
    }
    // Pad to a multiple of 8 chars with '=' so data_encoding can decode it.
    let mut padded = cleaned.to_uppercase();
    let rem = padded.len() % 8;
    if rem != 0 {
        padded.push_str(&"=".repeat(8 - rem));
    }
    let bytes = BASE32HEX.decode(padded.as_bytes()).ok()?;
    String::from_utf8(bytes).ok()
}

#[cfg(test)]
mod tests {
    use super::Base32HexDecoder;
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };
    use data_encoding::BASE32HEX;

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    #[test]
    fn successful_decoding() {
        let input = BASE32HEX.encode(b"hello world");
        let decoder = Decoder::<Base32HexDecoder>::new();
        let result = decoder.crack(&input, &get_athena_checker());
        let decoded_str = &result
            .unencrypted_text
            .expect("No unencrypted text for base32hex");
        assert_eq!(decoded_str[0], "hello world");
    }

    #[test]
    fn base32hex_decode_empty_string() {
        let decoder = Decoder::<Base32HexDecoder>::new();
        let result = decoder.crack("", &get_athena_checker()).unencrypted_text;
        assert!(result.is_none());
    }
}
