//! Decode a Base45 string.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, info, trace};

/// The Base45 alphabet defined by RFC 9285.
const BASE45_ALPHABET: &str = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:";

/// The Base45 decoder, call:
/// `let base45_decoder = Decoder::<Base45Decoder>::new()` to create a new instance
/// And then call:
/// `result = base45_decoder.crack(input)` to decode a base45 string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base45_decoder::Base45Decoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base45 = Decoder::<Base45Decoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_base45.crack("+8D VD82EK4F.KEA2", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct Base45Decoder;

impl Crack for Decoder<Base45Decoder> {
    fn new() -> Decoder<Base45Decoder> {
        Decoder {
            name: "Base45",
            description: "Base45 (RFC 9285) encodes two bytes as three printable characters and one byte as two printable characters. It is used in QR-code-friendly payloads.",
            link: "https://datatracker.ietf.org/doc/html/rfc9285",
            tags: vec!["base45", "base", "decoder", "rfc9285", "qr"],
            popularity: 0.7,
            phantom: std::marker::PhantomData,
        }
    }

    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base45 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_base45_no_error_handling(text) else {
            debug!("Failed to decode base45");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!("Failed to decode base45 because check_string_success returned false");
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);
        results
    }

    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    fn get_name(&self) -> &str {
        self.name
    }

    fn get_description(&self) -> &str {
        self.description
    }

    fn get_link(&self) -> &str {
        self.link
    }

    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode Base45 into UTF-8 text. Returns None on invalid input.
fn decode_base45_no_error_handling(text: &str) -> Option<String> {
    let chars: Vec<char> = text.chars().collect();
    if chars.is_empty() || chars.len() % 3 == 1 {
        return None;
    }

    let mut bytes = Vec::with_capacity(chars.len() * 2 / 3);
    let mut idx = 0;
    while idx < chars.len() {
        let c0 = base45_value(chars[idx])?;
        let c1 = base45_value(chars[idx + 1])?;
        if idx + 2 < chars.len() {
            let c2 = base45_value(chars[idx + 2])?;
            let value = c0 + c1 * 45 + c2 * 45 * 45;
            if value > 0xffff {
                return None;
            }
            bytes.push((value / 256) as u8);
            bytes.push((value % 256) as u8);
            idx += 3;
        } else {
            let value = c0 + c1 * 45;
            if value > 0xff {
                return None;
            }
            bytes.push(value as u8);
            idx += 2;
        }
    }

    String::from_utf8(bytes).ok()
}

/// Map a Base45 character to its numeric value.
fn base45_value(c: char) -> Option<u32> {
    BASE45_ALPHABET.find(c).map(|idx| idx as u32)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        CheckerTypes::CheckAthena(Checker::<Athena>::new())
    }

    #[test]
    fn successful_decoding() {
        let decoder = Decoder::<Base45Decoder>::new();
        let result = decoder
            .crack("+8D VD82EK4F.KEA2", &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for base45");
        assert_eq!(result[0], "hello world");
    }

    #[test]
    fn rfc_example_decodes_ab() {
        assert_eq!(
            decode_base45_no_error_handling("BB8"),
            Some("AB".to_string())
        );
    }

    #[test]
    fn invalid_length_returns_none() {
        assert!(decode_base45_no_error_handling("A").is_none());
    }

    #[test]
    fn invalid_character_returns_none() {
        assert!(decode_base45_no_error_handling("ABC_").is_none());
    }
}
