//! Decode a Beaufort cipher string
//! The Beaufort cipher is a variant of the Vigenère cipher where the ciphertext
//! is computed as C = (K - P) mod 26, so decryption is P = (K - C) mod 26.
//! This implementation automatically recovers the key length using the index
//! of coincidence and then recovers each key character via frequency analysis.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;
use once_cell::sync::Lazy;
use std::fs;
use std::path::Path;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// English bigrams for determining fitness, same format as the Vigenère
/// decoder uses.
static ENGLISH_BIGRAMS: Lazy<Vec<Vec<i64>>> = Lazy::new(|| {
    let mut bigrams_vec = vec![vec![0; 26]; 26];
    let f_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("src")
        .join("storage")
        .join("ngrams")
        .join("english_bigrams.txt");
    if let Ok(content) = fs::read_to_string(&f_path) {
        for line in content.split('\n') {
            if line.is_empty() {
                continue;
            }
            let line_split: Vec<&str> = line.split_ascii_whitespace().collect();
            if line_split.is_empty() {
                continue;
            }
            let mut chars_itr = line_split[0].chars();
            let char1: char = chars_itr
                .next()
                .expect("Could not retrieve first char")
                .to_ascii_uppercase();
            let char2: char = chars_itr
                .next()
                .expect("Could not retrieve second char")
                .to_ascii_uppercase();
            let fitness = line_split[1]
                .parse::<i64>()
                .expect("Could not parse fitness value");
            bigrams_vec[(char1 as u8 - b'A') as usize][(char2 as u8 - b'A') as usize] = fitness;
        }
    }
    bigrams_vec
});

/// The Beaufort decoder, call:
/// `let beaufort_decoder = Decoder::<BeaufortDecoder>::new()` to create a new instance
/// And then call:
/// `result = beaufort_decoder.crack(input)` to decode a Beaufort cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::beaufort_decoder::BeaufortDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_beaufort = Decoder::<BeaufortDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_beaufort.crack("lellw", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct BeaufortDecoder;

impl Crack for Decoder<BeaufortDecoder> {
    fn new() -> Decoder<BeaufortDecoder> {
        Decoder {
            name: "Beaufort",
            description: "The Beaufort cipher is a polyalphabetic substitution cipher similar to the Vigenère cipher, except the plaintext is subtracted from the key instead of being added. This implementation automatically recovers the key using the index of coincidence and frequency analysis. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Beaufort_cipher",
            tags: vec!["substitution", "classical", "auto-crack"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Beaufort Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        // Clean the input text (remove non-alphabetic characters)
        let clean_text: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();

        if clean_text.is_empty() {
            debug!("No valid characters found in input text");
            return results;
        }

        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let checker_result = checker_with_sensitivity.check(text);

        // Search for key lengths that are plausible for real text
        let mut best_candidate: Option<(String, String)> = None;
        for key_length in 2..30 {
            if clean_text.len() <= key_length * 2 {
                break;
            }
            let key = recover_beaufort_key(&clean_text, key_length);
            if key.is_empty() {
                continue;
            }
            let decode_attempt = beaufort_decrypt(text, &key);
            let check_result = checker_with_sensitivity.check(&decode_attempt);
            if check_result.is_identified {
                results.unencrypted_text = Some(vec![decode_attempt]);
                results.update_checker(&check_result);
                results.key = Some(key);
                return results;
            }
            if best_candidate.is_none() {
                best_candidate = Some((key, decode_attempt));
            }
        }

        // Fall back to the best (first) candidate even if the checker did not
        // positively identify the plaintext.
        if let Some((key, decoded)) = best_candidate {
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&checker_result);
            results.key = Some(key);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decrypt text encrypted with the Beaufort cipher using the given key.
/// For each letter, plaintext is computed as P = (K - C) mod 26.
fn beaufort_decrypt(text: &str, key: &str) -> String {
    let key_bytes: Vec<u8> = key.bytes().collect();
    let mut result = String::with_capacity(text.len());
    let mut key_idx = 0;

    for c in text.chars() {
        if c.is_ascii_alphabetic() {
            let key_val = (key_bytes[key_idx % key_bytes.len()] - b'A') as i16;
            let base = if c.is_ascii_uppercase() { b'A' } else { b'a' };
            let cipher_val = (c as u8 - base) as i16;
            let new_pos = ((key_val - cipher_val).rem_euclid(26)) as u8;
            result.push((base + new_pos) as char);
            key_idx += 1;
        } else {
            result.push(c);
        }
    }

    result
}

/// Recover the Beaufort key of a given length from ciphertext using bigram
/// fitness scoring (the same method the Vigenère decoder uses). For Beaufort,
/// the plaintext at a position is `key - ciphertext (mod 26)`.
fn recover_beaufort_key(ciphertext: &str, key_length: usize) -> String {
    let cipher_text: Vec<usize> = ciphertext
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .map(|c| (c.to_ascii_uppercase() as u8 - b'A') as usize)
        .collect();

    let mut best_fitness = 0;
    let mut best_key_ch2 = ' ';
    let mut best_score_0 = 0;
    let mut best_key_ch1_0 = ' ';
    let mut prev_best_score = 0;
    let mut prev_best_key_ch2 = ' ';

    let mut key = vec![' '; key_length];
    for (key_idx, key_char) in key.iter_mut().enumerate().take(key_length) {
        let mut best_key_ch1 = ' ';
        best_fitness = 0;

        for key_ch1 in 0..26 {
            for key_ch2 in 0..26 {
                let mut fitness = 0;
                for text_idx in (key_idx..(cipher_text.len() - 1)).step_by(key_length) {
                    // Beaufort plaintext: P = (K - C) mod 26.
                    let clear_ch1 =
                        (key_ch1 as i64 - cipher_text[text_idx] as i64).rem_euclid(26) as usize;
                    let clear_ch2 =
                        (key_ch2 as i64 - cipher_text[text_idx + 1] as i64).rem_euclid(26) as usize;
                    fitness += ENGLISH_BIGRAMS[clear_ch1][clear_ch2];
                }
                if fitness > best_fitness {
                    best_fitness = fitness;
                    best_key_ch1 = ((key_ch1 as u8) + b'A') as char;
                    best_key_ch2 = ((key_ch2 as u8) + b'A') as char;
                }
            }
        }
        if key_idx == 0 {
            best_score_0 = best_fitness;
            best_key_ch1_0 = best_key_ch1;
        } else {
            *key_char = if prev_best_score > best_fitness {
                prev_best_key_ch2
            } else {
                best_key_ch1
            };
        }
        prev_best_score = best_fitness;
        prev_best_key_ch2 = best_key_ch2
    }
    key[0] = if best_fitness > best_score_0 {
        best_key_ch2
    } else {
        best_key_ch1_0
    };
    key.into_iter().collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str, key: &str) -> String {
        // C = (K - P) mod 26
        let key_bytes: Vec<u8> = key.bytes().collect();
        let mut result = String::with_capacity(text.len());
        let mut key_idx = 0;
        for c in text.chars() {
            if c.is_ascii_alphabetic() {
                let key_val = (key_bytes[key_idx % key_bytes.len()] - b'A') as i16;
                let base = if c.is_ascii_uppercase() { b'A' } else { b'a' };
                let plain_val = (c as u8 - base) as i16;
                let new_pos = ((key_val - plain_val).rem_euclid(26)) as u8;
                result.push((base + new_pos) as char);
                key_idx += 1;
            } else {
                result.push(c);
            }
        }
        result
    }

    #[test]
    fn test_beaufort_decrypt_known_key() {
        // "HELLOWORLD" with key "KEY" => encrypt gives "DANZQCWNNH"
        let decrypted = beaufort_decrypt("danzqcwnnh", "KEY");
        assert_eq!(decrypted, "helloworld");
    }

    #[test]
    fn test_beaufort_auto_crack() {
        let plaintext = "this is a secret message that should be recovered by frequency analysis";
        let key = "SECRET";
        let ciphertext = encrypt(plaintext, key);
        let beaufort_decoder = Decoder::<BeaufortDecoder>::new();
        let result = beaufort_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Beaufort decoder");
        assert_eq!(result[0].trim(), plaintext);
    }

    #[test]
    fn test_beaufort_recover_key() {
        let plaintext = "this is a secret message that should be recovered by frequency analysis";
        let key = "SECRET";
        let ciphertext = encrypt(plaintext, key);
        let clean: String = ciphertext
            .chars()
            .filter(|c| c.is_ascii_alphabetic())
            .collect();
        let recovered = recover_beaufort_key(&clean, 6);
        assert_eq!(recovered, key);
    }

    #[test]
    fn test_beaufort_empty_input() {
        let beaufort_decoder = Decoder::<BeaufortDecoder>::new();
        let result = beaufort_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_beaufort_non_alphabetic_input() {
        let beaufort_decoder = Decoder::<BeaufortDecoder>::new();
        let result = beaufort_decoder
            .crack("12345!@#$%", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
