//! Decode Bech32 strings.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, info, trace};

/// The Bech32 data character set from BIP-173.
const BECH32_CHARSET: &[u8; 32] = b"qpzry9x8gf2tvdw0s3jn54khce6mua7l";
/// The Bech32 checksum generator constants from BIP-173.
const BECH32_GENERATOR: [u32; 5] = [0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3];

/// The Bech32 decoder, call:
/// `let bech32_decoder = Decoder::<Bech32Decoder>::new()` to create a new instance
/// And then call:
/// `result = bech32_decoder.crack(input)` to decode a Bech32 string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::bech32_decoder::Bech32Decoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decoder = Decoder::<Bech32Decoder>::new();
/// let checker = CheckerTypes::CheckAthena(Checker::<Athena>::new());
/// let result = decoder.crack("x1dpjkcmr0yxcmff", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello");
/// ```
pub struct Bech32Decoder;

impl Crack for Decoder<Bech32Decoder> {
    fn new() -> Decoder<Bech32Decoder> {
        Decoder {
            name: "Bech32",
            description: "Bech32 encodes 8-bit data using a checksummed 5-bit alphabet. It is used by Bitcoin SegWit addresses and other cryptocurrency protocols.",
            link: "https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki",
            tags: vec!["bech32", "base", "bitcoin", "encoding", "decoder"],
            popularity: 0.7,
            phantom: std::marker::PhantomData,
        }
    }

    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Bech32 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_bech32_no_error_handling(text) else {
            debug!("Failed to decode Bech32");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!("Failed to decode Bech32 because check_string_success returned false");
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);
        results
    }

    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    fn get_name(&self) -> &str {
        self.name
    }

    fn get_description(&self) -> &str {
        self.description
    }

    fn get_link(&self) -> &str {
        self.link
    }

    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode a checksummed Bech32 string into UTF-8 text.
fn decode_bech32_no_error_handling(text: &str) -> Option<String> {
    let input = text.trim();
    if input.len() < 8 || input.len() > 90 {
        return None;
    }
    if input.chars().any(|c| !c.is_ascii() || c.is_ascii_control()) {
        return None;
    }

    let has_lower = input.chars().any(|c| c.is_ascii_lowercase());
    let has_upper = input.chars().any(|c| c.is_ascii_uppercase());
    if has_lower && has_upper {
        return None;
    }

    let normalized = input.to_ascii_lowercase();
    let separator = normalized.rfind('1')?;
    if separator < 1 || separator + 7 > normalized.len() {
        return None;
    }

    let hrp = &normalized[..separator];
    if !hrp.bytes().all(|byte| (33..=126).contains(&byte)) {
        return None;
    }

    let values: Vec<u8> = normalized[separator + 1..]
        .bytes()
        .map(|byte| {
            BECH32_CHARSET
                .iter()
                .position(|&candidate| candidate == byte)
                .map(|index| index as u8)
        })
        .collect::<Option<Vec<_>>>()?;

    if bech32_polymod(
        &hrp_expand(hrp)
            .into_iter()
            .chain(values.iter().copied())
            .collect::<Vec<_>>(),
    ) != 1
    {
        return None;
    }

    let data = &values[..values.len() - 6];
    let bytes = convert_bits(data, 5, 8, false)?;
    String::from_utf8(bytes).ok()
}

/// Expand the human-readable part for checksum calculation.
fn hrp_expand(hrp: &str) -> Vec<u8> {
    let mut expanded = Vec::with_capacity(hrp.len() * 2 + 1);
    expanded.extend(hrp.bytes().map(|byte| byte >> 5));
    expanded.push(0);
    expanded.extend(hrp.bytes().map(|byte| byte & 31));
    expanded
}

/// Calculate the Bech32 checksum polymod.
fn bech32_polymod(values: &[u8]) -> u32 {
    let mut checksum = 1u32;
    for value in values {
        let top = checksum >> 25;
        checksum = ((checksum & 0x1ffffff) << 5) ^ u32::from(*value);
        for (index, generator) in BECH32_GENERATOR.iter().enumerate() {
            if ((top >> index) & 1) != 0 {
                checksum ^= generator;
            }
        }
    }
    checksum
}

/// Convert a stream between bit widths, validating unused padding bits.
fn convert_bits(data: &[u8], from_bits: u32, to_bits: u32, pad: bool) -> Option<Vec<u8>> {
    let max_value = (1u32 << to_bits) - 1;
    let max_input = (1u32 << from_bits) - 1;
    let mut accumulator = 0u32;
    let mut bits = 0u32;
    let mut result = Vec::new();

    for value in data {
        let value = u32::from(*value);
        if value > max_input {
            return None;
        }
        accumulator = (accumulator << from_bits) | value;
        bits += from_bits;
        while bits >= to_bits {
            bits -= to_bits;
            result.push(((accumulator >> bits) & max_value) as u8);
        }
    }

    if pad {
        if bits > 0 {
            result.push(((accumulator << (to_bits - bits)) & max_value) as u8);
        }
    } else if bits >= from_bits || ((accumulator << (to_bits - bits)) & max_value) != 0 {
        return None;
    }

    Some(result)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        CheckerTypes::CheckAthena(Checker::<Athena>::new())
    }

    #[test]
    fn successful_decoding() {
        let decoder = Decoder::<Bech32Decoder>::new();
        let result = decoder
            .crack("x1dpjkcmr0yxcmff", &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Bech32");
        assert_eq!(result[0], "hello");
    }

    #[test]
    fn validates_checksum() {
        assert_eq!(
            decode_bech32_no_error_handling("A12UEL5L"),
            Some(String::new())
        );
        assert!(decode_bech32_no_error_handling("A12UEL5M").is_none());
        assert!(decode_bech32_no_error_handling("x1dpjkcmr0yxcmff").is_some());
    }

    #[test]
    fn rejects_mixed_case() {
        assert!(decode_bech32_no_error_handling("X1dpjkcmr0yxcmff").is_none());
    }

    #[test]
    fn rejects_invalid_padding() {
        assert!(decode_bech32_no_error_handling("x1dpjkcmr0yxcmfg").is_none());
    }
}
