//! Decode Bencode data.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, info, trace};
use serde_json::{Map, Value};

/// The Bencode decoder, call:
/// `let bencode_decoder = Decoder::<BencodeDecoder>::new()` to create a new instance
/// And then call:
/// `result = bencode_decoder.crack(input)` to decode Bencode data
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::bencode_decoder::BencodeDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_bencode = Decoder::<BencodeDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_bencode.crack("d3:msg11:hello worlde", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert!(result.unwrap()[0].contains("hello world"));
/// ```
pub struct BencodeDecoder;

impl Crack for Decoder<BencodeDecoder> {
    fn new() -> Decoder<BencodeDecoder> {
        Decoder {
            name: "Bencode",
            description: "Bencode is a compact serialization format used by BitTorrent. It encodes integers, byte strings, lists and dictionaries with a small recursive grammar.",
            link: "https://en.wikipedia.org/wiki/Bencode",
            tags: vec!["bencode", "bencode", "torrent", "decoder", "serialization"],
            popularity: 0.7,
            phantom: std::marker::PhantomData,
        }
    }

    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Bencode with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_bencode_no_error_handling(text) else {
            debug!("Failed to decode bencode");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!("Failed to decode bencode because check_string_success returned false");
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);
        results
    }

    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    fn get_name(&self) -> &str {
        self.name
    }

    fn get_description(&self) -> &str {
        self.description
    }

    fn get_link(&self) -> &str {
        self.link
    }

    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode Bencode into a JSON string.
fn decode_bencode_no_error_handling(text: &str) -> Option<String> {
    let bytes = text.as_bytes();
    let (value, idx) = parse_value(bytes, 0)?;
    if idx != bytes.len() {
        return None;
    }
    serde_json::to_string(&value).ok()
}

/// Parse one Bencode value.
fn parse_value(bytes: &[u8], idx: usize) -> Option<(Value, usize)> {
    let first = *bytes.get(idx)?;
    match first {
        b'i' => parse_integer(bytes, idx),
        b'l' => parse_list(bytes, idx),
        b'd' => parse_dict(bytes, idx),
        b'0'..=b'9' => parse_bytestring(bytes, idx),
        _ => None,
    }
}

/// Parse a Bencode integer.
fn parse_integer(bytes: &[u8], mut idx: usize) -> Option<(Value, usize)> {
    idx += 1;
    let start = idx;
    while *bytes.get(idx)? != b'e' {
        idx += 1;
    }
    let num = std::str::from_utf8(&bytes[start..idx])
        .ok()?
        .parse::<i64>()
        .ok()?;
    Some((Value::from(num), idx + 1))
}

/// Parse a Bencode byte string.
fn parse_bytestring(bytes: &[u8], mut idx: usize) -> Option<(Value, usize)> {
    let start = idx;
    while bytes.get(idx).copied()?.is_ascii_digit() {
        idx += 1;
    }
    if *bytes.get(idx)? != b':' {
        return None;
    }
    let len = std::str::from_utf8(&bytes[start..idx])
        .ok()?
        .parse::<usize>()
        .ok()?;
    idx += 1;
    let end = idx.checked_add(len)?;
    let data = bytes.get(idx..end)?;
    let text = String::from_utf8_lossy(data).to_string();
    Some((Value::String(text), end))
}

/// Parse a Bencode list.
fn parse_list(bytes: &[u8], mut idx: usize) -> Option<(Value, usize)> {
    idx += 1;
    let mut items = Vec::new();
    while *bytes.get(idx)? != b'e' {
        let (value, next) = parse_value(bytes, idx)?;
        items.push(value);
        idx = next;
    }
    Some((Value::Array(items), idx + 1))
}

/// Parse a Bencode dictionary.
fn parse_dict(bytes: &[u8], mut idx: usize) -> Option<(Value, usize)> {
    idx += 1;
    let mut map = Map::new();
    while *bytes.get(idx)? != b'e' {
        let (key_value, next) = parse_bytestring(bytes, idx)?;
        let key = key_value.as_str()?.to_string();
        let (value, after) = parse_value(bytes, next)?;
        map.insert(key, value);
        idx = after;
    }
    Some((Value::Object(map), idx + 1))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        CheckerTypes::CheckAthena(Checker::<Athena>::new())
    }

    #[test]
    fn successful_decoding() {
        let decoder = Decoder::<BencodeDecoder>::new();
        let result = decoder
            .crack("d3:msg11:hello worlde", &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for bencode");
        assert!(result[0].contains("hello world"));
    }

    #[test]
    fn decodes_string_value() {
        assert_eq!(
            decode_bencode_no_error_handling("11:hello world"),
            Some("\"hello world\"".to_string())
        );
    }

    #[test]
    fn decodes_dictionary() {
        let decoded = decode_bencode_no_error_handling("d3:cow3:moo4:spam4:eggse");
        assert!(decoded.is_some());
        assert!(decoded.unwrap().contains("cow"));
    }

    #[test]
    fn invalid_input_returns_none() {
        assert!(decode_bencode_no_error_handling("i12").is_none());
    }
}
