//! Decode a Bifid cipher string
//! The Bifid cipher uses a Polybius square. Each plaintext letter is replaced
//! by its row and column numbers, then all rows are written out, followed by
//! all columns. The resulting number stream is re-paired to give the
//! ciphertext. Decryption reverses this process with the same square.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};
use super::polybius_decoder::POLYBIUS_ALPHABET;

use log::{debug, trace};

/// The Bifid decoder, call:
/// `let bifid_decoder = Decoder::<BifidDecoder>::new()` to create a new instance
/// And then call:
/// `result = bifid_decoder.crack(input)` to decode a Bifid cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::bifid_decoder::BifidDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_bifid = Decoder::<BifidDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_bifid.crack("HAAEVSLDSP", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct BifidDecoder;

impl Crack for Decoder<BifidDecoder> {
    fn new() -> Decoder<BifidDecoder> {
        Decoder {
            name: "Bifid",
            description: "The Bifid cipher is a cipher which combines the Polybius square with transposition, and uses fractionation to achieve diffusion. It encrypts each plaintext letter by replacing it with its coordinates in a 5x5 square, then transposing the coordinates. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Bifid_cipher",
            tags: vec!["polybius", "classical", "fractionated", "transposition"],
            popularity: 0.35,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Bifid Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let clean_text: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();
        if clean_text.len() < 8 {
            debug!("Input text too short for Bifid analysis");
            return results;
        }

        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let mut best_result: Option<String> = None;

        // Try several periods. A period equal to the whole message length is
        // the classic default, but the ciphertext may use any block length.
        for period in 2..=10 {
            if clean_text.len() < period {
                break;
            }
            let decoded = bifid_decrypt(&clean_text, period);
            if decoded.is_empty() {
                continue;
            }
            let check_result = checker_with_sensitivity.check(&decoded);
            if check_result.is_identified {
                results.unencrypted_text = Some(vec![decoded]);
                results.update_checker(&check_result);
                return results;
            }
            if best_result.is_none() {
                best_result = Some(decoded);
            }
        }

        if let Some(decoded) = best_result {
            let check_result = checker_with_sensitivity.check(&decoded);
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&check_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decrypt a Bifid ciphertext using the standard alphabet square and the given
/// period (block length). Returns an empty string when the input cannot be
/// decrypted.
///
/// # Panics
///
/// This function never panics: letters are checked against the Polybius
/// alphabet before lookup.
pub fn bifid_decrypt(ciphertext: &str, period: usize) -> String {
    let clean: Vec<char> = ciphertext
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .map(|c| c.to_ascii_uppercase())
        .map(|c| if c == 'J' { 'I' } else { c })
        .filter(|c| POLYBIUS_ALPHABET.contains(c))
        .collect();

    if clean.is_empty() {
        return String::new();
    }

    let total = clean.len();
    // Flatten each ciphertext letter into its coordinate pair, producing a
    // single stream of 2*total numbers.
    let mut coords: Vec<u8> = Vec::with_capacity(total * 2);
    for &c in &clean {
        let Some(pos) = POLYBIUS_ALPHABET.iter().position(|&x| x == c) else {
            return String::new();
        };
        coords.push((pos / 5 + 1) as u8);
        coords.push((pos % 5 + 1) as u8);
    }

    // Process each block independently. Within a block of `chunk_len`
    // letters, the first `chunk_len` numbers of the stream are the rows of
    // the plaintext letters and the next `chunk_len` are the columns.
    let mut result = String::with_capacity(total);
    let mut start = 0;
    while start < total {
        let chunk_len = period.min(total - start);
        for i in 0..chunk_len {
            let row = coords[start * 2 + i];
            let col = coords[start * 2 + chunk_len + i];
            if !(1..=5).contains(&row) || !(1..=5).contains(&col) {
                return String::new();
            }
            result.push(POLYBIUS_ALPHABET[((row - 1) * 5 + (col - 1)) as usize]);
        }
        start += chunk_len;
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Encrypt with the standard alphabet square (helper for roundtrip tests).
    fn encrypt(text: &str, period: usize) -> String {
        let clean: Vec<char> = text
            .chars()
            .map(|c| c.to_ascii_uppercase())
            .map(|c| if c == 'J' { 'I' } else { c })
            .filter(|c| POLYBIUS_ALPHABET.contains(c))
            .collect();
        // For each block, write the row coordinates followed by the column
        // coordinates, then pair them up to make the ciphertext letters.
        let mut result = String::with_capacity(clean.len());
        let mut start = 0;
        while start < clean.len() {
            let chunk_len = period.min(clean.len() - start);
            let mut rows = Vec::with_capacity(chunk_len);
            let mut cols = Vec::with_capacity(chunk_len);
            for i in 0..chunk_len {
                let c = clean[start + i];
                let pos = POLYBIUS_ALPHABET.iter().position(|&x| x == c).unwrap();
                rows.push((pos / 5 + 1) as u8);
                cols.push((pos % 5 + 1) as u8);
            }
            let mut stream: Vec<u8> = Vec::with_capacity(chunk_len * 2);
            stream.extend_from_slice(&rows);
            stream.extend_from_slice(&cols);
            for i in 0..chunk_len {
                let row = stream[i * 2];
                let col = stream[i * 2 + 1];
                result.push(POLYBIUS_ALPHABET[((row - 1) * 5 + (col - 1)) as usize]);
            }
            start += chunk_len;
        }
        result
    }

    #[test]
    fn test_bifid_roundtrip() {
        // Wikipedia example: FLEEATONCE (period = whole message) with the
        // standard square gives a fixed ciphertext; verify the roundtrip.
        let plaintext = "FLEEATONCE";
        let ciphertext = encrypt(plaintext, plaintext.len());
        assert_eq!(bifid_decrypt(&ciphertext, plaintext.len()), plaintext);
    }

    #[test]
    fn test_bifid_wikipedia_vector() {
        // Wikipedia's example uses a mixed alphabet square:
        //   B G W K Z / Q P N D S / I O A X E / F C L U M / T H Y V R
        // FLEEATONCE encrypts to UAEOLWRINS with the whole message as one block.
        let square = ["BGWKZ", "QPNDS", "IOAXE", "FCLUM", "THYVR"];
        let plaintext = "FLEEATONCE";
        let mut cipher = String::new();
        for c in plaintext.chars() {
            let (r, col) = find_in_square(&square, c);
            cipher.push(r);
            cipher.push(col);
        }
        // Rows first then columns.
        let rows: String = cipher.chars().step_by(2).collect();
        let cols: String = cipher.chars().skip(1).step_by(2).collect();
        let stream: String = format!("{rows}{cols}");
        let mut ciphertext = String::new();
        for i in 0..stream.len() / 2 {
            let pair = format!(
                "{}{}",
                stream.chars().nth(i * 2).unwrap(),
                stream.chars().nth(i * 2 + 1).unwrap()
            );
            ciphertext.push(letter_from_pair(&square, &pair));
        }
        assert_eq!(ciphertext, "UAEOLWRINS");
    }

    /// Locate a letter in the square, returning its row and column digits.
    fn find_in_square(square: &[&str; 5], c: char) -> (char, char) {
        let c = if c == 'J' { 'I' } else { c };
        for (r, row) in square.iter().enumerate() {
            if let Some(col) = row.chars().position(|x| x == c) {
                return (
                    char::from_digit((r + 1) as u32, 10).unwrap(),
                    char::from_digit((col + 1) as u32, 10).unwrap(),
                );
            }
        }
        panic!("letter {c} not in square");
    }

    /// Map a two digit coordinate pair back to a letter.
    fn letter_from_pair(square: &[&str; 5], pair: &str) -> char {
        let r = pair.chars().next().unwrap().to_digit(10).unwrap() as usize;
        let c = pair.chars().nth(1).unwrap().to_digit(10).unwrap() as usize;
        square[r - 1].chars().nth(c - 1).unwrap()
    }

    #[test]
    fn test_bifid_crack() {
        let plaintext = "FLEEATONCE";
        let ciphertext = encrypt(plaintext, plaintext.len());
        let bifid_decoder = Decoder::<BifidDecoder>::new();
        let result = bifid_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Bifid decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_bifid_empty_input() {
        let bifid_decoder = Decoder::<BifidDecoder>::new();
        let result = bifid_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_bifid_short_input() {
        let bifid_decoder = Decoder::<BifidDecoder>::new();
        let result = bifid_decoder
            .crack("AB", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
