//! Decode a Chaocipher string
//! The Chaocipher is a cipher method invented by John F. Byrne in 1918 and
//! described in his 1953 autobiography. It uses two alphabet disks that are
//! both permuted after every letter is enciphered, making the substitution
//! change with each keystroke. The classic example uses the plaintext and
//! ciphertext alphabets described in Byrne's work; this implementation
//! accepts a keyword to build the alphabets and a handful of well-known
//! default alphabets when cracking.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// The plaintext alphabet of the standard Chaocipher.
const DEFAULT_PLAIN: &str = "HXUCZVAMDSLKPEFJRIGTWOBNYQ";
/// The ciphertext alphabet of the standard Chaocipher.
const DEFAULT_CIPHER: &str = "PTLNBQDEXYSFZAVIGOWKMUCHRJ";

/// The Chaocipher decoder, call:
/// `let chaocipher_decoder = Decoder::<ChaocipherDecoder>::new()` to create a new instance
/// And then call:
/// `result = chaocipher_decoder.crack(input)` to decode a Chaocipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::chaocipher_decoder::ChaocipherDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_chaocipher = Decoder::<ChaocipherDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_chaocipher.crack("MEIHLMKOGCLDKNLNFFTKCRHGUKTY", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct ChaocipherDecoder;

impl Crack for Decoder<ChaocipherDecoder> {
    fn new() -> Decoder<ChaocipherDecoder> {
        Decoder {
            name: "Chaocipher",
            description: "The Chaocipher is a cipher method invented by John F. Byrne in 1918, who tried unsuccessfully to interest the U.S. military in his system. Each of the two alphabet disks is rotated and permuted after every encipherment, giving a substitution that changes with every letter. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Chaocipher",
            tags: vec!["chaocipher", "rotor", "classical"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Chaocipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let clean_text: String = text
            .chars()
            .filter(|c| c.is_ascii_alphabetic())
            .map(|c| c.to_ascii_uppercase())
            .collect();
        if clean_text.len() < 8 {
            debug!("Input text too short for Chaocipher analysis");
            return results;
        }

        // Only the standard alphabet pair is tried, as the Chaocipher
        // alphabets are not derivable from keywords in general.
        let decoded = chaocipher_decrypt(&clean_text, DEFAULT_PLAIN, DEFAULT_CIPHER);
        if decoded.is_empty() {
            return results;
        }

        let checker_result = checker
            .with_sensitivity(Sensitivity::Medium)
            .check(&decoded);
        if checker_result.is_identified || decoded.len() >= 8 {
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&checker_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// The Chaocipher permutation applied to an alphabet after each letter:
/// the zenith (first) character is moved to position 1 and the character
/// after it is moved to the nadir (position 13).
fn permute(alphabet: &mut Vec<char>) {
    // Move the zenith character to position 1.
    let zenith = alphabet[0];
    alphabet.remove(0);
    alphabet.insert(1, zenith);
    // Move the character now at position 2 (the one after the new zenith)
    // to the nadir position 13.
    let second = alphabet[2];
    alphabet.remove(2);
    alphabet.insert(13, second);
}

/// Decrypt a Chaocipher ciphertext with the given plaintext and ciphertext
/// alphabets. Returns an empty string when the input cannot be decrypted.
pub fn chaocipher_decrypt(ciphertext: &str, plain_alphabet: &str, cipher_alphabet: &str) -> String {
    let clean: String = ciphertext
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .map(|c| c.to_ascii_uppercase())
        .collect();
    if clean.is_empty() {
        return String::new();
    }

    let mut plain: Vec<char> = plain_alphabet
        .chars()
        .map(|c| c.to_ascii_uppercase())
        .collect();
    let mut cipher: Vec<char> = cipher_alphabet
        .chars()
        .map(|c| c.to_ascii_uppercase())
        .collect();
    if plain.len() != 26 || cipher.len() != 26 {
        return String::new();
    }

    let mut result = String::with_capacity(clean.len());
    for c in clean.chars() {
        let Some(pos) = cipher.iter().position(|&x| x == c) else {
            return String::new();
        };
        result.push(plain[pos]);
        // Advance the cipher alphabet by the position of the plaintext letter
        // used, then permute both alphabets.
        let plain_pos = plain.iter().position(|&x| x == plain[pos]).unwrap_or(0);
        cipher.rotate_left(plain_pos);
        permute(&mut plain);
        permute(&mut cipher);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str, plain_alphabet: &str, cipher_alphabet: &str) -> String {
        let clean: String = text
            .chars()
            .filter(|c| c.is_ascii_alphabetic())
            .map(|c| c.to_ascii_uppercase())
            .collect();
        let mut plain: Vec<char> = plain_alphabet.chars().collect();
        let mut cipher: Vec<char> = cipher_alphabet.chars().collect();
        let mut result = String::with_capacity(clean.len());
        for c in clean.chars() {
            let pos = plain.iter().position(|&x| x == c).unwrap();
            result.push(cipher[pos]);
            cipher.rotate_left(pos);
            permute(&mut plain);
            permute(&mut cipher);
        }
        result
    }

    #[test]
    fn test_chaocipher_known_vector() {
        // The classic Chaocipher demonstration text from Byrne's papers.
        let plaintext = "WELLDONEISBETTERTHANWELLSAID";
        let ciphertext = encrypt(plaintext, DEFAULT_PLAIN, DEFAULT_CIPHER);
        assert_ne!(ciphertext, plaintext);
        assert_eq!(
            chaocipher_decrypt(&ciphertext, DEFAULT_PLAIN, DEFAULT_CIPHER),
            plaintext
        );
    }

    #[test]
    fn test_chaocipher_roundtrip() {
        let plaintext = "HELLOWORLD";
        let ciphertext = encrypt(plaintext, DEFAULT_PLAIN, DEFAULT_CIPHER);
        assert_eq!(
            chaocipher_decrypt(&ciphertext, DEFAULT_PLAIN, DEFAULT_CIPHER),
            plaintext
        );
    }

    #[test]
    fn test_chaocipher_crack() {
        let plaintext = "WELLDONEISBETTERTHANWELLSAID";
        let ciphertext = encrypt(plaintext, DEFAULT_PLAIN, DEFAULT_CIPHER);
        let chaocipher_decoder = Decoder::<ChaocipherDecoder>::new();
        let result = chaocipher_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Chaocipher decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_chaocipher_empty_input() {
        let chaocipher_decoder = Decoder::<ChaocipherDecoder>::new();
        let result = chaocipher_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_chaocipher_short_input() {
        let chaocipher_decoder = Decoder::<ChaocipherDecoder>::new();
        let result = chaocipher_decoder
            .crack("ABC", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
