//! Detect and decompress compressed data (gzip, zlib, deflate, bzip2, xz,
//! zstd, brotli).
//!
//! CTF challenges frequently wrap data in a compressed container and then
//! base64/hex encode it ("compressed then base64" is a classic chained
//! encoding). This decoder hex-decodes the input, sniffs the magic bytes, and
//! tries the matching decompressor before handing the result to the checker.
//!
//! Call `compression_decoder.crack` to use. It returns option<String> and
//! check with `result.is_some()` to see if it returned okay.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;
use super::xor_single_byte_decoder::hex_decode;

use log::{debug, info, trace};

/// The compression decoder, call:
/// `let compression_decoder = Decoder::<CompressionDecoder>::new()` to create a new instance
/// And then call:
/// `result = compression_decoder.crack(input)` to decompress
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::compression_decoder::CompressionDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_compression = Decoder::<CompressionDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_compression.crack("1f8b0800000000000003", &checker).unencrypted_text;
/// ```
pub struct CompressionDecoder;

impl Crack for Decoder<CompressionDecoder> {
    fn new() -> Decoder<CompressionDecoder> {
        Decoder {
            name: "compression",
            description: "Detects and decompresses common compressed container formats (gzip, zlib, deflate, bzip2, xz, zstd, brotli) by inspecting the magic bytes. Useful for CTF challenges that wrap data in a compressed container and then base64/hex encode it.",
            link: "https://en.wikipedia.org/wiki/Data_compression",
            tags: vec!["compression", "decompress", "gzip", "zlib", "bzip2", "xz", "zstd", "brotli", "auto-crack"],
            popularity: 0.9,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Compression with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let bytes = match hex_decode(text) {
            Some(bytes) => bytes,
            None => {
                debug!("Failed to hex-decode input for compression decoder");
                return results;
            }
        };

        if bytes.is_empty() {
            debug!("Empty input for compression decoder");
            return results;
        }

        // Cap the compressed input size to avoid zip-bomb style memory blowups.
        const MAX_COMPRESSED_BYTES: usize = 64 * 1024 * 1024;
        if bytes.len() > MAX_COMPRESSED_BYTES {
            debug!("Compression decoder input too large: {} bytes", bytes.len());
            return results;
        }

        let Some(decompressed) = try_decompress(&bytes) else {
            debug!("No known compression format matched");
            return results;
        };

        // Reject suspicious decompression ratios (zip-bomb protection).
        const MAX_RATIO: usize = 2000;
        if decompressed.len() > bytes.len().saturating_mul(MAX_RATIO).max(1000) {
            debug!("Decompressed data suspiciously large, refusing");
            return results;
        }

        let Ok(decoded_text) = String::from_utf8(decompressed) else {
            debug!("Decompressed data is not valid UTF-8");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode compression because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Sniff the magic bytes and try every known decompressor in turn. Returns the
/// first successful decompression.
fn try_decompress(bytes: &[u8]) -> Option<Vec<u8>> {
    if bytes.len() < 2 {
        return None;
    }

    // gzip: 1f 8b
    if bytes[0] == 0x1f && bytes[1] == 0x8b {
        if let Some(out) = decompress_gzip(bytes) {
            trace!("Decompressed as gzip ({} bytes)", out.len());
            return Some(out);
        }
    }

    // zlib: 78 01 / 78 5e / 78 9c / 78 da
    if bytes[0] == 0x78
        && matches!(
            bytes[1],
            0x01 | 0x5e | 0x9c | 0xda | 0x20 | 0x7d | 0xbb | 0xf9
        )
    {
        if let Some(out) = decompress_zlib(bytes) {
            trace!("Decompressed as zlib ({} bytes)", out.len());
            return Some(out);
        }
    }

    // bzip2: 42 5a 68 (BZh)
    if bytes.len() >= 3 && bytes[0] == b'B' && bytes[1] == b'Z' && bytes[2] == b'h' {
        if let Some(out) = decompress_bzip2(bytes) {
            trace!("Decompressed as bzip2 ({} bytes)", out.len());
            return Some(out);
        }
    }

    // xz: fd 37 7a 58 5a 00
    if bytes.len() >= 6
        && bytes[0] == 0xfd
        && bytes[1] == 0x37
        && bytes[2] == 0x7a
        && bytes[3] == 0x58
        && bytes[4] == 0x5a
        && bytes[5] == 0x00
    {
        if let Some(out) = decompress_xz(bytes) {
            trace!("Decompressed as xz ({} bytes)", out.len());
            return Some(out);
        }
    }

    // lzma-alone: 5d 00 00
    if bytes.len() >= 3 && bytes[0] == 0x5d && bytes[1] == 0x00 && bytes[2] == 0x00 {
        if let Some(out) = decompress_lzma(bytes) {
            trace!("Decompressed as lzma-alone ({} bytes)", out.len());
            return Some(out);
        }
    }

    // zstd: 28 b5 2f fd
    if bytes.len() >= 4
        && bytes[0] == 0x28
        && bytes[1] == 0xb5
        && bytes[2] == 0x2f
        && bytes[3] == 0xfd
    {
        if let Some(out) = decompress_zstd(bytes) {
            trace!("Decompressed as zstd ({} bytes)", out.len());
            return Some(out);
        }
    }

    // brotli: 0b .. (brotli has no fixed magic; try a bounded decode)
    if let Some(out) = decompress_brotli(bytes) {
        trace!("Decompressed as brotli ({} bytes)", out.len());
        return Some(out);
    }

    // Raw deflate stream (no header). Try as a last resort.
    if let Some(out) = decompress_deflate(bytes) {
        trace!("Decompressed as raw deflate ({} bytes)", out.len());
        return Some(out);
    }

    None
}

/// Decompress gzip (RFC 1952) data into its raw bytes.
fn decompress_gzip(bytes: &[u8]) -> Option<Vec<u8>> {
    use flate2::read::GzDecoder;
    use std::io::Read;

    let mut decoder = GzDecoder::new(bytes);
    let mut out = Vec::new();
    decoder.read_to_end(&mut out).ok()?;
    Some(out)
}

/// Decompress zlib (RFC 1950) data into its raw bytes.
fn decompress_zlib(bytes: &[u8]) -> Option<Vec<u8>> {
    use flate2::read::ZlibDecoder;
    use std::io::Read;

    let mut decoder = ZlibDecoder::new(bytes);
    let mut out = Vec::new();
    decoder.read_to_end(&mut out).ok()?;
    Some(out)
}

/// Decompress raw deflate (RFC 1951) data into its raw bytes.
fn decompress_deflate(bytes: &[u8]) -> Option<Vec<u8>> {
    use flate2::read::DeflateDecoder;
    use std::io::Read;

    let mut decoder = DeflateDecoder::new(bytes);
    let mut out = Vec::new();
    decoder.read_to_end(&mut out).ok()?;
    Some(out)
}

/// Decompress bzip2 data into its raw bytes.
fn decompress_bzip2(bytes: &[u8]) -> Option<Vec<u8>> {
    use bzip2::read::BzDecoder;
    use std::io::Read;

    let mut decoder = BzDecoder::new(bytes);
    let mut out = Vec::new();
    decoder.read_to_end(&mut out).ok()?;
    Some(out)
}

/// Decompress xz data into its raw bytes.
fn decompress_xz(bytes: &[u8]) -> Option<Vec<u8>> {
    use std::io::Read;
    use xz2::read::XzDecoder;

    let mut decoder = XzDecoder::new(bytes);
    let mut out = Vec::new();
    decoder.read_to_end(&mut out).ok()?;
    Some(out)
}

/// Decompress legacy .lzma data into its raw bytes.
fn decompress_lzma(bytes: &[u8]) -> Option<Vec<u8>> {
    use std::io::Read;
    use xz2::read::XzDecoder;

    // xz2's XzDecoder also handles the legacy .lzma format.
    let mut decoder = XzDecoder::new(bytes);
    let mut out = Vec::new();
    decoder.read_to_end(&mut out).ok()?;
    Some(out)
}

/// Decompress zstd data into its raw bytes.
fn decompress_zstd(bytes: &[u8]) -> Option<Vec<u8>> {
    use std::io::Read;
    use zstd::stream::read::Decoder;

    let mut decoder = Decoder::new(bytes).ok()?;
    let mut out = Vec::new();
    decoder.read_to_end(&mut out).ok()?;
    Some(out)
}

/// Decompress brotli data into its raw bytes.
fn decompress_brotli(bytes: &[u8]) -> Option<Vec<u8>> {
    let mut out = Vec::new();
    let mut decoder = brotli::Decompressor::new(bytes, 8192);
    match std::io::copy(&mut decoder, &mut out) {
        Ok(_) => Some(out),
        Err(_) => None,
    }
}

#[cfg(test)]
mod tests {
    use super::CompressionDecoder;
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn to_hex(bytes: &[u8]) -> String {
        bytes.iter().map(|b| format!("{:02x}", b)).collect()
    }

    #[test]
    fn test_gzip_roundtrip() {
        use flate2::write::GzEncoder;
        use flate2::Compression;
        use std::io::Write;

        let mut encoder = GzEncoder::new(Vec::new(), Compression::default());
        encoder.write_all(b"hello world").unwrap();
        let compressed = encoder.finish().unwrap();

        let decoder = Decoder::<CompressionDecoder>::new();
        let result = decoder.crack(&to_hex(&compressed), &get_athena_checker());
        let decoded = result.unencrypted_text.expect("failed to decompress gzip");
        assert_eq!(decoded[0], "hello world");
    }

    #[test]
    fn test_zlib_roundtrip() {
        use flate2::write::ZlibEncoder;
        use flate2::Compression;
        use std::io::Write;

        let mut encoder = ZlibEncoder::new(Vec::new(), Compression::default());
        encoder.write_all(b"zlib compressed text").unwrap();
        let compressed = encoder.finish().unwrap();

        let decoder = Decoder::<CompressionDecoder>::new();
        let result = decoder.crack(&to_hex(&compressed), &get_athena_checker());
        let decoded = result.unencrypted_text.expect("failed to decompress zlib");
        assert_eq!(decoded[0], "zlib compressed text");
    }

    #[test]
    fn test_bzip2_roundtrip() {
        use bzip2::write::BzEncoder;
        use bzip2::Compression;
        use std::io::Write;

        let mut encoder = BzEncoder::new(Vec::new(), Compression::default());
        encoder.write_all(b"bzip2 compressed text").unwrap();
        let compressed = encoder.finish().unwrap();

        let decoder = Decoder::<CompressionDecoder>::new();
        let result = decoder.crack(&to_hex(&compressed), &get_athena_checker());
        let decoded = result.unencrypted_text.expect("failed to decompress bzip2");
        assert_eq!(decoded[0], "bzip2 compressed text");
    }

    #[test]
    fn test_xz_roundtrip() {
        use std::io::Write;
        use xz2::write::XzEncoder;

        let mut encoder = XzEncoder::new(Vec::new(), 6);
        encoder.write_all(b"xz compressed text").unwrap();
        let compressed = encoder.finish().unwrap();

        let decoder = Decoder::<CompressionDecoder>::new();
        let result = decoder.crack(&to_hex(&compressed), &get_athena_checker());
        let decoded = result.unencrypted_text.expect("failed to decompress xz");
        assert_eq!(decoded[0], "xz compressed text");
    }

    #[test]
    fn test_zstd_roundtrip() {
        let compressed = zstd::encode_all(std::io::Cursor::new(b"zstd text"), 3).unwrap();

        let decoder = Decoder::<CompressionDecoder>::new();
        let result = decoder.crack(&to_hex(&compressed), &get_athena_checker());
        let decoded = result.unencrypted_text.expect("failed to decompress zstd");
        assert_eq!(decoded[0], "zstd text");
    }

    #[test]
    fn test_brotli_roundtrip() {
        let mut writer = Vec::new();
        let mut params = brotli::enc::BrotliEncoderParams::default();
        params.quality = 5;
        brotli::BrotliCompress(
            &mut std::io::Cursor::new(b"brotli text"),
            &mut writer,
            &params,
        )
        .unwrap();

        let decoder = Decoder::<CompressionDecoder>::new();
        let result = decoder.crack(&to_hex(&writer), &get_athena_checker());
        let decoded = result
            .unencrypted_text
            .expect("failed to decompress brotli");
        assert_eq!(decoded[0], "brotli text");
    }

    #[test]
    fn test_invalid_input() {
        let decoder = Decoder::<CompressionDecoder>::new();
        let result = decoder
            .crack("hello world not compressed", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_empty_input() {
        let decoder = Decoder::<CompressionDecoder>::new();
        let result = decoder.crack("", &get_athena_checker()).unencrypted_text;
        assert!(result.is_none());
    }
}
