//! Decode an Enigma machine cipher string
//! The Enigma machine is a rotor cipher machine used by Germany during World
//! War II. Each keystroke advances the rotors and the letter is substituted
//! through the plugboard, three rotors, and a reflector. This implementation
//! simulates the Enigma I / M3 rotor set with the standard rotors I, II, III
//! and reflector B, and tries a small set of common rotor orders and ring
//! settings when cracking.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// The wiring of the standard Enigma rotors, indexed by rotor name.
const ROTOR_WIRINGS: [(&str, &str, &str); 8] = [
    ("I", "EKMFLGDQVZNTOWYHXUSPAIBRCJ", "Q"),
    ("II", "AJDKSIRUXBLHWTMCQGZNPYFVOE", "E"),
    ("III", "BDFHJLCPRTXVZNYEIWGAKMUSQO", "V"),
    ("IV", "ESOVPZJAYQUIRHXLNFTGKDCMWB", "J"),
    ("V", "VZBRGITYUPSDNHLXAWMJQOFECK", "Z"),
    ("VI", "JPGVOUMFYQBENHZRDKASXLICTW", "ZM"),
    ("VII", "NZJHGRCXMYSWBOUFAIVLPEKQDT", "ZM"),
    ("VIII", "FKQHTLXOCBJSPDZRAMEWNIUYGV", "ZM"),
];

/// The standard reflectors.
const REFLECTORS: [(&str, &str); 3] = [
    ("B", "YRUHQSLDPXNGOKMIEBFZCWVJAT"),
    ("C", "FVPJIAOYEDRZXWGCTKUQSBNMHL"),
    ("B-Thin", "ENKQAUYWJICOPBLMDXZVFTHRGS"),
];

/// The Enigma decoder, call:
/// `let enigma_decoder = Decoder::<EnigmaDecoder>::new()` to create a new instance
/// And then call:
/// `result = enigma_decoder.crack(input)` to decode an Enigma cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::enigma_decoder::EnigmaDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_enigma = Decoder::<EnigmaDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_enigma.crack("EECWORMMZC", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct EnigmaDecoder;

impl Crack for Decoder<EnigmaDecoder> {
    fn new() -> Decoder<EnigmaDecoder> {
        Decoder {
            name: "Enigma",
            description: "The Enigma machine was a family of electro-mechanical rotor cipher machines used for the encryption and decryption of secret messages, most famously by Nazi Germany during World War II. This implementation simulates the Enigma I/M3 with standard rotors and tries common rotor orders. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Enigma_machine",
            tags: vec!["enigma", "rotor", "classical"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Enigma with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let clean_text: String = text
            .chars()
            .filter(|c| c.is_ascii_alphabetic())
            .map(|c| c.to_ascii_uppercase())
            .collect();
        if clean_text.len() < 4 {
            debug!("Input text too short for Enigma analysis");
            return results;
        }

        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let mut best_result: Option<String> = None;

        // Try a small set of common rotor orders with the standard initial
        // position (AAA) and plugboard (empty).
        let rotor_orders: [(&str, &str, &str); 3] =
            [("I", "II", "III"), ("II", "I", "III"), ("III", "II", "I")];
        for (r1, r2, r3) in rotor_orders {
            let decoded = enigma_decrypt(&clean_text, r1, r2, r3, "B", "AAA", "");
            if decoded.is_empty() {
                continue;
            }
            let check_result = checker_with_sensitivity.check(&decoded);
            if check_result.is_identified {
                results.unencrypted_text = Some(vec![decoded]);
                results.update_checker(&check_result);
                results.key = Some(format!("{r1}{r2}{r3} B AAA"));
                return results;
            }
            if best_result.is_none() {
                best_result = Some(decoded);
            }
        }

        if let Some(decoded) = best_result {
            let check_result = checker_with_sensitivity.check(&decoded);
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&check_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// A single Enigma rotor with its wiring and ring setting.
struct Rotor {
    /// The forward substitution wiring (left ring position to output).
    wiring: [usize; 26],
    /// The ring offset applied to the letter before substitution.
    ring: usize,
    /// The rotor position (window character).
    position: usize,
}

impl Rotor {
    /// Build a rotor from its name, ring setting letter, and position letter.
    fn new(name: &str, ring: char, position: char) -> Rotor {
        let wiring_str = ROTOR_WIRINGS
            .iter()
            .find(|(n, _, _)| *n == name)
            .map(|(_, w, _)| *w)
            .unwrap_or("ABCDEFGHIJKLMNOPQRSTUVWXYZ");
        let wiring = wiring_str
            .chars()
            .map(|c| c as usize - b'A' as usize)
            .collect::<Vec<_>>()
            .try_into()
            .expect("rotor wiring must be 26 characters");
        Rotor {
            wiring,
            ring: ring as usize - b'A' as usize,
            position: position as usize - b'A' as usize,
        }
    }

    /// Forward pass: substitute a letter index (0-25) through the rotor.
    fn forward(&self, c: usize) -> usize {
        let offset = (c as i64 + self.position as i64 - self.ring as i64).rem_euclid(26) as usize;
        ((self.wiring[offset] as i64 + self.ring as i64 - self.position as i64).rem_euclid(26))
            as usize
    }

    /// Backward pass: substitute in the reverse direction.
    fn backward(&self, c: usize) -> usize {
        let offset = (c as i64 + self.position as i64 - self.ring as i64).rem_euclid(26) as usize;
        let index = self
            .wiring
            .iter()
            .position(|&x| x == offset)
            .expect("rotor wiring is a permutation");
        ((index as i64 + self.ring as i64 - self.position as i64).rem_euclid(26)) as usize
    }
}

/// Decrypt an Enigma ciphertext with the given rotor order, reflector, ring
/// settings and plugboard pairs. Returns an empty string when the input is
/// invalid.
///
/// The ciphertext is processed with the rotors advanced for every letter, so
/// decryption is identical to encryption.
pub fn enigma_decrypt(
    ciphertext: &str,
    rotor1: &str,
    rotor2: &str,
    rotor3: &str,
    reflector: &str,
    ring_settings: &str,
    plugboard: &str,
) -> String {
    let clean: String = ciphertext
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .map(|c| c.to_ascii_uppercase())
        .collect();
    if clean.is_empty() {
        return String::new();
    }

    // Parse the plugboard pairs (e.g. "AB CD EF").
    let mut plug: [usize; 26] = std::array::from_fn(|i| i);
    for pair in plugboard.split_whitespace() {
        let chars: Vec<char> = pair.chars().filter(|c| c.is_ascii_alphabetic()).collect();
        if chars.len() == 2 {
            let a = chars[0].to_ascii_uppercase() as usize - b'A' as usize;
            let b = chars[1].to_ascii_uppercase() as usize - b'A' as usize;
            plug[a] = b;
            plug[b] = a;
        }
    }

    let ring: Vec<char> = ring_settings
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .collect();
    let ring1 = ring.first().copied().unwrap_or('A');
    let ring2 = ring.get(1).copied().unwrap_or('A');
    let ring3 = ring.get(2).copied().unwrap_or('A');

    let reflector_wiring = REFLECTORS
        .iter()
        .find(|(n, _)| *n == reflector)
        .map(|(_, w)| *w)
        .unwrap_or("YRUHQSLDPXNGOKMIEBFZCWVJAT");
    let reflector_map: Vec<usize> = reflector_wiring
        .chars()
        .map(|c| c as usize - b'A' as usize)
        .collect();

    let mut left = Rotor::new(rotor1, ring1, 'A');
    let mut middle = Rotor::new(rotor2, ring2, 'A');
    let mut right = Rotor::new(rotor3, ring3, 'A');

    let mut result = String::with_capacity(clean.len());
    for c in clean.chars() {
        // Advance the right rotor every keystroke; middle and left on notch.
        right.position = (right.position + 1).rem_euclid(26);
        let right_notch = ROTOR_WIRINGS
            .iter()
            .find(|(n, _, _)| *n == rotor3)
            .map(|(_, _, n)| *n)
            .unwrap_or("Q");
        if right_notch.contains((right.position as u8 + b'A') as char) {
            middle.position = (middle.position + 1).rem_euclid(26);
        }
        let middle_notch = ROTOR_WIRINGS
            .iter()
            .find(|(n, _, _)| *n == rotor2)
            .map(|(_, _, n)| *n)
            .unwrap_or("E");
        if middle_notch.contains((middle.position as u8 + b'A') as char) {
            left.position = (left.position + 1).rem_euclid(26);
        }

        let mut letter = c as usize - b'A' as usize;
        letter = plug[letter];
        letter = right.forward(letter);
        letter = middle.forward(letter);
        letter = left.forward(letter);
        letter = reflector_map[letter];
        letter = left.backward(letter);
        letter = middle.backward(letter);
        letter = right.backward(letter);
        letter = plug[letter];
        result.push((b'A' + letter as u8) as char);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    #[test]
    fn test_enigma_known_vector() {
        // With rotors I II III, reflector B, ring AAA and no plugboard, the
        // first few letters of "AAAAA" do not map to themselves.
        let encrypted = enigma_decrypt("AAAAA", "I", "II", "III", "B", "AAA", "");
        assert_ne!(encrypted, "AAAAA");
        // Decrypting the output with the same settings recovers the input.
        assert_eq!(
            enigma_decrypt(&encrypted, "I", "II", "III", "B", "AAA", ""),
            "AAAAA"
        );
    }

    #[test]
    fn test_enigma_self_inverse() {
        let text = "HELLOWORLD";
        let encrypted = enigma_decrypt(text, "I", "II", "III", "B", "AAA", "");
        assert_eq!(
            enigma_decrypt(&encrypted, "I", "II", "III", "B", "AAA", ""),
            text
        );
    }

    #[test]
    fn test_enigma_crack() {
        let plaintext = "FLEEATONCE";
        let ciphertext = enigma_decrypt(plaintext, "I", "II", "III", "B", "AAA", "");
        let enigma_decoder = Decoder::<EnigmaDecoder>::new();
        let result = enigma_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Enigma decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_enigma_empty_input() {
        let enigma_decoder = Decoder::<EnigmaDecoder>::new();
        let result = enigma_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_enigma_short_input() {
        let enigma_decoder = Decoder::<EnigmaDecoder>::new();
        let result = enigma_decoder
            .crack("AB", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
