//! Decode a Four-square cipher string
//! The Four-square cipher is a digraph substitution cipher invented by Felix
//! Delastelle. It uses four 5x5 squares: the plaintext digraph is found in
//! two plaintext squares and its ciphertext digraph is read from two
//! ciphertext squares built from two keywords. Decryption reverses the
//! mapping using the same squares.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};
use super::polybius_decoder::POLYBIUS_ALPHABET;

use log::{debug, trace};

/// Common keyword pairs to try when cracking.
const COMMON_KEYS: [(&str, &str); 6] = [
    ("PLAYFAIR", "DELASTELLE"),
    ("EXAMPLE", "KEYWORD"),
    ("MONARCHY", "CIPHER"),
    ("SECRET", "MESSAGE"),
    ("FIRST", "SECOND"),
    ("CRYPTO", "GRAPHY"),
];

/// The Four-square decoder, call:
/// `let four_square_decoder = Decoder::<FourSquareDecoder>::new()` to create a new instance
/// And then call:
/// `result = four_square_decoder.crack(input)` to decode a Four-square cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::four_square_decoder::FourSquareDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_four_square = Decoder::<FourSquareDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_four_square.crack("NEMSNEMMIIPY", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct FourSquareDecoder;

impl Crack for Decoder<FourSquareDecoder> {
    fn new() -> Decoder<FourSquareDecoder> {
        Decoder {
            name: "Four-square",
            description: "The Four-square cipher is a manual symmetric encryption technique and was the first literal digraph substitution cipher. It was invented by Felix Delastelle. It encrypts pairs of letters using four 5x5 squares, two of which are built from keywords. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Four-square_cipher",
            tags: vec!["polygraphic", "classical", "auto-crack"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Four-square Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let clean_text: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();
        if clean_text.len() < 8 || !clean_text.len().is_multiple_of(2) {
            debug!("Input text too short or odd for Four-square analysis");
            return results;
        }

        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let mut best_result: Option<String> = None;

        for (key1, key2) in COMMON_KEYS {
            let decoded = four_square_decrypt(&clean_text, key1, key2);
            if decoded.is_empty() {
                continue;
            }
            let check_result = checker_with_sensitivity.check(&decoded);
            if check_result.is_identified {
                results.unencrypted_text = Some(vec![decoded]);
                results.update_checker(&check_result);
                results.key = Some(format!("{key1}/{key2}"));
                return results;
            }
            if best_result.is_none() {
                best_result = Some(decoded);
            }
        }

        if let Some(decoded) = best_result {
            let check_result = checker_with_sensitivity.check(&decoded);
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&check_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Build a 5x5 square from a keyword using the standard alphabet (I/J merged).
fn build_square(keyword: &str) -> [[char; 5]; 5] {
    let mut used = [false; 25];
    let mut square = [[' '; 5]; 5];
    let mut pos = 0;
    for c in keyword.chars().chain(POLYBIUS_ALPHABET.iter().copied()) {
        let upper = c.to_ascii_uppercase();
        let letter = if upper == 'J' { 'I' } else { upper };
        if let Some(idx) = POLYBIUS_ALPHABET.iter().position(|&x| x == letter) {
            if !used[idx] {
                used[idx] = true;
                square[pos / 5][pos % 5] = POLYBIUS_ALPHABET[idx];
                pos += 1;
            }
        }
        if pos == 25 {
            break;
        }
    }
    square
}

/// Find the (row, col) position of a letter in the square.
fn find_pos(square: &[[char; 5]; 5], c: char) -> (usize, usize) {
    for r in 0..5 {
        for col in 0..5 {
            if square[r][col] == c {
                return (r, col);
            }
        }
    }
    panic!("letter {c} not in Four-square square");
}

/// Decrypt a Four-square ciphertext with the two keywords. Returns an empty
/// string when the input cannot be decrypted.
pub fn four_square_decrypt(ciphertext: &str, key1: &str, key2: &str) -> String {
    let clean: Vec<char> = ciphertext
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .map(|c| c.to_ascii_uppercase())
        .map(|c| if c == 'J' { 'I' } else { c })
        .filter(|c| POLYBIUS_ALPHABET.contains(c))
        .collect();
    if clean.len() < 2 || !clean.len().is_multiple_of(2) {
        return String::new();
    }

    // Layout:
    //   [plain1] [cipher1]
    //   [cipher2] [plain2]
    // The two ciphertext squares are built from key1 and key2; the two
    // plaintext squares hold the standard alphabet.
    let cipher_square1 = build_square(key1);
    let cipher_square2 = build_square(key2);
    let plain_square = build_square("");

    let mut result = String::with_capacity(clean.len());
    let mut idx = 0;
    while idx + 1 < clean.len() {
        // Locate the ciphertext letters in the ciphertext squares.
        let (r1, c1) = find_pos(&cipher_square1, clean[idx]);
        let (r2, c2) = find_pos(&cipher_square2, clean[idx + 1]);
        // The plaintext letters share the row of one ciphertext letter and
        // the column of the other, read from the plaintext squares.
        result.push(plain_square[r1][c2]);
        result.push(plain_square[r2][c1]);
        idx += 2;
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str, key1: &str, key2: &str) -> String {
        let clean: Vec<char> = text
            .chars()
            .map(|c| c.to_ascii_uppercase())
            .map(|c| if c == 'J' { 'I' } else { c })
            .filter(|c| POLYBIUS_ALPHABET.contains(c))
            .collect();
        let cipher_square1 = build_square(key1);
        let cipher_square2 = build_square(key2);
        let plain_square = build_square("");
        let mut result = String::new();
        let mut idx = 0;
        while idx + 1 < clean.len() {
            let (r1, c1) = find_pos(&plain_square, clean[idx]);
            let (r2, c2) = find_pos(&plain_square, clean[idx + 1]);
            result.push(cipher_square1[r1][c2]);
            result.push(cipher_square2[r2][c1]);
            idx += 2;
        }
        result
    }

    #[test]
    fn test_four_square_roundtrip() {
        let plaintext = "HELLOWORLD";
        let (key1, key2) = ("EXAMPLE", "KEYWORD");
        let ciphertext = encrypt(plaintext, key1, key2);
        assert_eq!(four_square_decrypt(&ciphertext, key1, key2), plaintext);
    }

    #[test]
    fn test_four_square_crack() {
        let plaintext = "MEETMEATONCE";
        let (key1, key2) = ("EXAMPLE", "KEYWORD");
        let ciphertext = encrypt(plaintext, key1, key2);
        let four_square_decoder = Decoder::<FourSquareDecoder>::new();
        let result = four_square_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Four-square decoder");
        assert_eq!(result[0].trim(), plaintext);
    }

    #[test]
    fn test_four_square_empty_input() {
        let four_square_decoder = Decoder::<FourSquareDecoder>::new();
        let result = four_square_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_four_square_short_input() {
        let four_square_decoder = Decoder::<FourSquareDecoder>::new();
        let result = four_square_decoder
            .crack("AB", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
