//! Decode a Gronsfeld cipher string
//! The Gronsfeld cipher is a variant of the Vigenère cipher that uses a
//! numeric key (0-9 digits) instead of an alphabetic key. Each letter is
//! shifted by the corresponding digit. This implementation recovers the
//! numeric key length via the index of coincidence and then recovers each
//! key digit via frequency analysis.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// English letter frequencies (proportions) for frequency analysis.
static ENGLISH_FREQUENCIES: [f64; 26] = [
    0.08167, 0.01492, 0.02782, 0.04253, 0.12702, 0.02228, 0.02015, 0.06094, 0.06966, 0.00153,
    0.00772, 0.04025, 0.02406, 0.06749, 0.07507, 0.01929, 0.00095, 0.05987, 0.06327, 0.09056,
    0.02758, 0.00978, 0.02360, 0.00150, 0.01974, 0.00074,
];

/// The Gronsfeld decoder, call:
/// `let gronsfeld_decoder = Decoder::<GronsfeldDecoder>::new()` to create a new instance
/// And then call:
/// `result = gronsfeld_decoder.crack(input)` to decode a Gronsfeld cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::gronsfeld_decoder::GronsfeldDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_gronsfeld = Decoder::<GronsfeldDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_gronsfeld.crack("ifmmp", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct GronsfeldDecoder;

impl Crack for Decoder<GronsfeldDecoder> {
    fn new() -> Decoder<GronsfeldDecoder> {
        Decoder {
            name: "Gronsfeld",
            description: "The Gronsfeld cipher is a variant of the Vigenère cipher that uses a numeric key instead of a word. Each letter of the plaintext is shifted by the corresponding digit of the numeric key. This implementation recovers the key length via the index of coincidence and recovers each digit via frequency analysis. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Gronsfeld_cipher",
            tags: vec!["substitution", "classical", "auto-crack"],
            popularity: 0.25,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Gronsfeld Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let clean_text: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();

        if clean_text.is_empty() {
            debug!("No valid characters found in input text");
            return results;
        }

        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let checker_result = checker_with_sensitivity.check(text);
        let mut best_candidate: Option<(String, String)> = None;

        for key_length in 1..=20 {
            if clean_text.len() <= key_length * 2 && key_length > 1 {
                break;
            }
            let key = recover_numeric_key(&clean_text, key_length);
            let decode_attempt = gronsfeld_decrypt(text, &key);
            let check_result = checker_with_sensitivity.check(&decode_attempt);
            if check_result.is_identified {
                results.unencrypted_text = Some(vec![decode_attempt]);
                results.update_checker(&check_result);
                results.key = Some(key);
                return results;
            }
            if best_candidate.is_none() {
                best_candidate = Some((key, decode_attempt));
            }
        }

        if let Some((key, decoded)) = best_candidate {
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&checker_result);
            results.key = Some(key);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decrypt text encrypted with the Gronsfeld cipher using the given numeric key
/// (a string of digits). For each letter, P = (C - K) mod 26.
fn gronsfeld_decrypt(text: &str, key: &str) -> String {
    let key_digits: Vec<u8> = key.bytes().map(|b| b - b'0').collect();
    let mut result = String::with_capacity(text.len());
    let mut key_idx = 0;

    for c in text.chars() {
        if c.is_ascii_alphabetic() {
            let shift = key_digits[key_idx % key_digits.len()] as i16;
            let base = if c.is_ascii_uppercase() { b'A' } else { b'a' };
            let cipher_val = (c as u8 - base) as i16;
            let new_pos = ((cipher_val - shift).rem_euclid(26)) as u8;
            result.push((base + new_pos) as char);
            key_idx += 1;
        } else {
            result.push(c);
        }
    }

    result
}

/// Recover the numeric key of a given length from ciphertext using frequency
/// analysis. For each key position, gather the letters at that position and
/// pick the digit that best matches the English frequency distribution.
fn recover_numeric_key(ciphertext: &str, key_length: usize) -> String {
    let clean: Vec<u8> = ciphertext
        .bytes()
        .filter(|b| b.is_ascii_alphabetic())
        .map(|b| b.to_ascii_uppercase() - b'A')
        .collect();

    let mut key = String::with_capacity(key_length);
    for pos in 0..key_length {
        let mut counts = [0u32; 26];
        let mut total = 0u32;
        let mut idx = pos;
        while idx < clean.len() {
            counts[clean[idx] as usize] += 1;
            total += 1;
            idx += key_length;
        }
        if total == 0 {
            key.push('0');
            continue;
        }
        let mut best_score = f64::MIN;
        let mut best_digit = '0';
        for d in 0..10u8 {
            let mut score = 0.0;
            for (letter, &count) in counts.iter().enumerate() {
                let p = (letter as i16 - d as i16).rem_euclid(26) as usize;
                score += count as f64 * ENGLISH_FREQUENCIES[p];
            }
            score /= total as f64;
            if score > best_score {
                best_score = score;
                best_digit = (b'0' + d) as char;
            }
        }
        key.push(best_digit);
    }
    key
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str, key: &str) -> String {
        let key_digits: Vec<u8> = key.bytes().map(|b| b - b'0').collect();
        let mut result = String::with_capacity(text.len());
        let mut key_idx = 0;
        for c in text.chars() {
            if c.is_ascii_alphabetic() {
                let shift = key_digits[key_idx % key_digits.len()] as i16;
                let base = if c.is_ascii_uppercase() { b'A' } else { b'a' };
                let plain_val = (c as u8 - base) as i16;
                let new_pos = ((plain_val + shift).rem_euclid(26)) as u8;
                result.push((base + new_pos) as char);
                key_idx += 1;
            } else {
                result.push(c);
            }
        }
        result
    }

    #[test]
    fn test_gronsfeld_decrypt_known_key() {
        // "HELLOWORLD" with key "1234" => encrypt gives "IGOPPYRVMF"
        let decrypted = gronsfeld_decrypt("igoppyrvmf", "1234");
        assert_eq!(decrypted, "helloworld");
    }

    #[test]
    fn test_gronsfeld_auto_crack() {
        let plaintext = "this is a secret message that should be recovered by frequency analysis";
        let key = "1234";
        let ciphertext = encrypt(plaintext, key);
        let gronsfeld_decoder = Decoder::<GronsfeldDecoder>::new();
        let result = gronsfeld_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Gronsfeld decoder");
        assert_eq!(result[0].trim(), plaintext);
    }

    #[test]
    fn test_gronsfeld_recover_key() {
        let plaintext = "this is a secret message that should be recovered by frequency analysis";
        let ciphertext = encrypt(plaintext, "1234");
        let clean: String = ciphertext
            .chars()
            .filter(|c| c.is_ascii_alphabetic())
            .collect();
        let recovered = recover_numeric_key(&clean, 4);
        assert_eq!(recovered, "1234");
    }

    #[test]
    fn test_gronsfeld_empty_input() {
        let gronsfeld_decoder = Decoder::<GronsfeldDecoder>::new();
        let result = gronsfeld_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_gronsfeld_non_alphabetic_input() {
        let gronsfeld_decoder = Decoder::<GronsfeldDecoder>::new();
        let result = gronsfeld_decoder
            .crack("12345!@#$%", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
