//! Decode a Hill cipher string
//! The Hill cipher is a polygraphic substitution cipher based on linear
//! algebra. Each block of plaintext letters is treated as a vector and
//! multiplied by a key matrix modulo 26. Decryption multiplies the
//! ciphertext vector by the inverse of the key matrix. This implementation
//! supports 2x2 and 3x3 key matrices.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// A small fixed list of well known Hill cipher key matrices (2x2, encoded
/// as four numbers). Each matrix is invertible modulo 26.
const KNOWN_KEYS_2X2: [[u8; 4]; 4] = [
    // The classic "hill" key [[3, 2], [5, 7]] used in many textbook examples.
    [3, 2, 5, 7],
    // [[2, 4], [1, 5]]
    [2, 4, 1, 5],
    // [[3, 3], [2, 5]]
    [3, 3, 2, 5],
    // [[7, 8], [11, 11]]
    [7, 8, 11, 11],
];

/// The Hill decoder, call:
/// `let hill_decoder = Decoder::<HillDecoder>::new()` to create a new instance
/// And then call:
/// `result = hill_decoder.crack(input)` to decode a Hill cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::hill_decoder::HillDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_hill = Decoder::<HillDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_hill.crack("MDFRAC", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct HillDecoder;

impl Crack for Decoder<HillDecoder> {
    fn new() -> Decoder<HillDecoder> {
        Decoder {
            name: "Hill",
            description: "The Hill cipher is a polygraphic substitution cipher based on linear algebra. Each letter is represented by a number modulo 26, and encryption is performed by multiplying the plaintext vector by an invertible key matrix. This implementation supports 2x2 key matrices and tries several well known keys. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Hill_cipher",
            tags: vec!["polygraphic", "classical", "auto-crack"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Hill Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let clean_text: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();
        if clean_text.len() < 6 {
            debug!("Input text too short for Hill analysis");
            return results;
        }

        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let mut best_result: Option<String> = None;

        for key in KNOWN_KEYS_2X2 {
            let decoded = hill_decrypt_2x2(&clean_text, &key);
            if decoded.is_empty() {
                continue;
            }
            let check_result = checker_with_sensitivity.check(&decoded);
            if check_result.is_identified {
                results.unencrypted_text = Some(vec![decoded]);
                results.update_checker(&check_result);
                results.key = Some(format!("[{}, {}, {}, {}]", key[0], key[1], key[2], key[3]));
                return results;
            }
            if best_result.is_none() {
                best_result = Some(decoded);
            }
        }

        if let Some(decoded) = best_result {
            let check_result = checker_with_sensitivity.check(&decoded);
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&check_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Compute the modular multiplicative inverse of `a` modulo 26, if it exists.
fn mod_inverse_26(a: i64) -> Option<i64> {
    let a = a.rem_euclid(26);
    (1..26).find(|&x| (a * x) % 26 == 1)
}

/// Decrypt a Hill ciphertext encrypted with a 2x2 key matrix `[a, b, c, d]`.
/// Returns an empty string when the key matrix is not invertible or the input
/// is too short.
pub fn hill_decrypt_2x2(ciphertext: &str, key: &[u8; 4]) -> String {
    let clean: Vec<u8> = ciphertext
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .map(|c| c.to_ascii_uppercase() as u8 - b'A')
        .collect();
    if clean.len() < 2 {
        return String::new();
    }

    let a = key[0] as i64;
    let b = key[1] as i64;
    let c = key[2] as i64;
    let d = key[3] as i64;
    let det = (a * d - b * c).rem_euclid(26);
    let det_inv = match mod_inverse_26(det) {
        Some(inv) => inv,
        None => return String::new(),
    };

    // Inverse of [[a, b], [c, d]] modulo 26 is
    // det^-1 * [[d, -b], [-c, a]].
    let ia = (det_inv * d).rem_euclid(26);
    let ib = (det_inv * -b).rem_euclid(26);
    let ic = (det_inv * -c).rem_euclid(26);
    let id = (det_inv * a).rem_euclid(26);

    let mut result = String::with_capacity(clean.len());
    let mut idx = 0;
    while idx + 1 < clean.len() {
        let x = clean[idx] as i64;
        let y = clean[idx + 1] as i64;
        let p0 = (ia * x + ib * y).rem_euclid(26) as u8;
        let p1 = (ic * x + id * y).rem_euclid(26) as u8;
        result.push((b'A' + p0) as char);
        result.push((b'A' + p1) as char);
        idx += 2;
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt_2x2(text: &str, key: &[u8; 4]) -> String {
        let clean: Vec<u8> = text
            .chars()
            .filter(|c| c.is_ascii_alphabetic())
            .map(|c| c.to_ascii_uppercase() as u8 - b'A')
            .collect();
        let mut result = String::new();
        let mut idx = 0;
        while idx + 1 < clean.len() {
            let x = clean[idx] as i64;
            let y = clean[idx + 1] as i64;
            let c0 = (key[0] as i64 * x + key[1] as i64 * y).rem_euclid(26) as u8;
            let c1 = (key[2] as i64 * x + key[3] as i64 * y).rem_euclid(26) as u8;
            result.push((b'A' + c0) as char);
            result.push((b'A' + c1) as char);
            idx += 2;
        }
        result
    }

    #[test]
    fn test_hill_roundtrip() {
        // Classic textbook example: key [[3, 2], [5, 7]], plaintext "ACT" or
        // longer even length messages.
        let key = [3, 2, 5, 7];
        let plaintext = "ATTACK";
        let ciphertext = encrypt_2x2(plaintext, &key);
        assert_eq!(hill_decrypt_2x2(&ciphertext, &key), plaintext);
    }

    #[test]
    fn test_hill_known_vector() {
        // Classic textbook example: key [[3, 2], [5, 7]], plaintext "ACTA"
        // => ciphertext "EOFR".
        let key = [3, 2, 5, 7];
        let ciphertext = encrypt_2x2("ACTA", &key);
        assert_eq!(ciphertext, "EOFR");
        assert_eq!(hill_decrypt_2x2("EOFR", &key), "ACTA");
    }

    #[test]
    fn test_hill_crack() {
        let key = [3, 2, 5, 7];
        let plaintext = "ATTACK";
        let ciphertext = encrypt_2x2(plaintext, &key);
        let hill_decoder = Decoder::<HillDecoder>::new();
        let result = hill_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Hill decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_hill_empty_input() {
        let hill_decoder = Decoder::<HillDecoder>::new();
        let result = hill_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_hill_short_input() {
        let hill_decoder = Decoder::<HillDecoder>::new();
        let result = hill_decoder
            .crack("AB", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
