//! Decode HTML/XML entities (e.g. `&amp;`, `&#65;`, `&#x41;`).
//!
//! Call `html_entities_decoder.crack` to use. It returns option<String> and
//! check with `result.is_some()` to see if it returned okay.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The HTML entities decoder, call:
/// `let html_entities_decoder = Decoder::<HtmlEntitiesDecoder>::new()` to create a new instance
/// And then call:
/// `result = html_entities_decoder.crack(input)` to decode
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::html_entities_decoder::HtmlEntitiesDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_entities = Decoder::<HtmlEntitiesDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_entities.crack("hello &amp; goodbye &#65;&#x42;", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello & goodbye AB");
/// ```
pub struct HtmlEntitiesDecoder;

impl Crack for Decoder<HtmlEntitiesDecoder> {
    fn new() -> Decoder<HtmlEntitiesDecoder> {
        Decoder {
            name: "HTML entities",
            description: "HTML character entities are used to represent special characters in HTML/XML documents. They take the form &name;, &#decimal;, or &#xhex; and are commonly used to obfuscate text in CTF challenges.",
            link: "https://developer.mozilla.org/en-US/docs/Glossary/Entity",
            tags: vec!["html", "xml", "entities", "web", "decoder"],
            popularity: 0.7,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying HTML entities with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let decoded_text = decode_html_entities(text);

        if decoded_text.is_none() {
            debug!("Failed to decode html entities because decode_html_entities returned None");
            return results;
        }

        let decoded_text = decoded_text.unwrap();
        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode html entities because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode HTML/XML entities. Only succeeds if at least one entity was replaced.
fn decode_html_entities(text: &str) -> Option<String> {
    let mut out = String::with_capacity(text.len());
    let mut replaced = false;
    let chars: Vec<char> = text.chars().collect();
    let mut i = 0;

    while i < chars.len() {
        if chars[i] == '&' {
            // Find the closing semicolon.
            if let Some(semi) = chars[i + 1..].iter().position(|&c| c == ';') {
                let end = i + 1 + semi;
                let entity: String = chars[i + 1..end].iter().collect();

                if let Some(decoded) = lookup_entity(&entity) {
                    out.push(decoded);
                    replaced = true;
                    i = end + 1;
                    continue;
                }
            }
        }
        out.push(chars[i]);
        i += 1;
    }

    if replaced {
        Some(out)
    } else {
        None
    }
}

/// Look up a single entity (without the & and ;) and return its character.
fn lookup_entity(entity: &str) -> Option<char> {
    // Numeric character references.
    if let Some(hex) = entity
        .strip_prefix("#x")
        .or_else(|| entity.strip_prefix("#X"))
    {
        let code = u32::from_str_radix(hex, 16).ok()?;
        return char::from_u32(code);
    }
    if let Some(dec) = entity.strip_prefix('#') {
        let code = dec.parse::<u32>().ok()?;
        return char::from_u32(code);
    }

    // Named entities (the most common subset).
    let decoded: Option<&str> = match entity {
        "amp" => Some("&"),
        "lt" => Some("<"),
        "gt" => Some(">"),
        "quot" => Some("\""),
        "apos" => Some("'"),
        "nbsp" => Some("\u{00a0}"),
        "copy" => Some("\u{00a9}"),
        "reg" => Some("\u{00ae}"),
        "trade" => Some("\u{2122}"),
        "hellip" => Some("\u{2026}"),
        "mdash" => Some("\u{2014}"),
        "ndash" => Some("\u{2013}"),
        "ldquo" => Some("\u{201c}"),
        "rdquo" => Some("\u{201d}"),
        "lsquo" => Some("\u{2018}"),
        "rsquo" => Some("\u{2019}"),
        "laquo" => Some("\u{00ab}"),
        "raquo" => Some("\u{00bb}"),
        "cent" => Some("\u{00a2}"),
        "pound" => Some("\u{00a3}"),
        "yen" => Some("\u{00a5}"),
        "euro" => Some("\u{20ac}"),
        "sect" => Some("\u{00a7}"),
        "para" => Some("\u{00b6}"),
        "deg" => Some("\u{00b0}"),
        "plusmn" => Some("\u{00b1}"),
        "times" => Some("\u{00d7}"),
        "divide" => Some("\u{00f7}"),
        "frac12" => Some("\u{00bd}"),
        "frac14" => Some("\u{00bc}"),
        "frac34" => Some("\u{00be}"),
        "sup2" => Some("\u{00b2}"),
        "sup3" => Some("\u{00b3}"),
        "micro" => Some("\u{00b5}"),
        "alpha" => Some("\u{03b1}"),
        "beta" => Some("\u{03b2}"),
        "gamma" => Some("\u{03b3}"),
        "delta" => Some("\u{03b4}"),
        "pi" => Some("\u{03c0}"),
        "sum" => Some("\u{2211}"),
        "infin" => Some("\u{221e}"),
        "ne" => Some("\u{2260}"),
        "le" => Some("\u{2264}"),
        "ge" => Some("\u{2265}"),
        "larr" => Some("\u{2190}"),
        "uarr" => Some("\u{2191}"),
        "rarr" => Some("\u{2192}"),
        "darr" => Some("\u{2193}"),
        _ => None,
    };

    decoded.map(|s| s.chars().next().unwrap())
}

#[cfg(test)]
mod tests {
    use super::HtmlEntitiesDecoder;
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    #[test]
    fn successful_decoding() {
        let entities_decoder = Decoder::<HtmlEntitiesDecoder>::new();
        let result =
            entities_decoder.crack("hello &amp; goodbye &#65;&#x42;", &get_athena_checker());
        let decoded_str = &result
            .unencrypted_text
            .expect("No unencrypted text for html entities");
        assert_eq!(decoded_str[0], "hello & goodbye AB");
    }

    #[test]
    fn decodes_named_entities() {
        let entities_decoder = Decoder::<HtmlEntitiesDecoder>::new();
        let result = entities_decoder.crack("a &lt; b &gt; c", &get_athena_checker());
        let decoded_str = &result
            .unencrypted_text
            .expect("No unencrypted text for html entities");
        assert_eq!(decoded_str[0], "a < b > c");
    }

    #[test]
    fn no_entities_returns_none() {
        let entities_decoder = Decoder::<HtmlEntitiesDecoder>::new();
        let result = entities_decoder
            .crack("plain text without entities", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
