//! Decode JSON Web Tokens (JWT).

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};

use log::{debug, info, trace};
use serde_json::Value;

/// The JWT decoder, call:
/// `let jwt_decoder = Decoder::<JwtDecoder>::new()` to create a new instance
/// And then call:
/// `result = jwt_decoder.crack(input)` to decode a JWT token
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::decoders::jwt_decoder::JwtDecoder;
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decoder = Decoder::<JwtDecoder>::new();
/// let checker = CheckerTypes::CheckAthena(Checker::<Athena>::new());
/// let token = "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiJoZWxsbyB3b3JsZCIsImFkbWluIjp0cnVlfQ.";
/// let result = decoder.crack(token, &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert!(result.unwrap()[0].contains("hello world"));
/// ```
pub struct JwtDecoder;

impl Crack for Decoder<JwtDecoder> {
    fn new() -> Decoder<JwtDecoder> {
        Decoder {
            name: "JWT",
            description: "JWTs are dot-separated JSON Web Tokens containing base64url-encoded header and payload segments. This decoder expands the header and payload into readable JSON.",
            link: "https://datatracker.ietf.org/doc/html/rfc7519",
            tags: vec!["jwt", "base64url", "json", "token", "decoder"],
            popularity: 0.7,
            phantom: std::marker::PhantomData,
        }
    }

    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying JWT with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_jwt_no_error_handling(text) else {
            debug!("Failed to decode jwt");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!("Failed to decode jwt because check_string_success returned false");
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);
        results
    }

    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    fn get_name(&self) -> &str {
        self.name
    }

    fn get_description(&self) -> &str {
        self.description
    }

    fn get_link(&self) -> &str {
        self.link
    }

    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode a JWT into a readable JSON string containing the header and payload.
fn decode_jwt_no_error_handling(text: &str) -> Option<String> {
    let clean = text.trim();
    let parts: Vec<&str> = clean.split('.').collect();
    if parts.len() < 2 {
        return None;
    }

    let header = decode_segment(parts[0])?;
    let payload = decode_segment(parts[1])?;

    let header_json: Value = serde_json::from_str(&header).ok()?;
    let payload_json: Value = serde_json::from_str(&payload).ok()?;

    serde_json::to_string(&serde_json::json!({
        "header": header_json,
        "payload": payload_json,
    }))
    .ok()
}

/// Decode one unpadded base64url JWT segment as UTF-8.
fn decode_segment(segment: &str) -> Option<String> {
    let bytes = URL_SAFE_NO_PAD.decode(segment.as_bytes()).ok()?;
    String::from_utf8(bytes).ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        CheckerTypes::CheckAthena(Checker::<Athena>::new())
    }

    #[test]
    fn successful_decoding() {
        let decoder = Decoder::<JwtDecoder>::new();
        let token =
            "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiJoZWxsbyB3b3JsZCIsImFkbWluIjp0cnVlfQ.";
        let result = decoder
            .crack(token, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for JWT");
        assert!(result[0].contains("hello world"));
    }

    #[test]
    fn decodes_known_token() {
        let decoded = decode_jwt_no_error_handling(
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjdGYiLCJuYW1lIjoiYWxpY2UifQ.signature",
        );
        assert!(decoded.is_some());
        assert!(decoded.unwrap().contains("alice"));
    }

    #[test]
    fn invalid_token_returns_none() {
        assert!(decode_jwt_no_error_handling("invalid.token").is_none());
    }
}
