//! Decode a leetspeak string
//! Leetspeak (or leet) replaces letters with visually similar digits and
//! symbols, e.g. `3` for E, `4` for A, `7` for T. This decoder maps the
//! common leet substitutions back to their plaintext letters while leaving
//! ordinary letters unchanged.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::trace;
use std::collections::HashMap;

/// The Leet decoder, call:
/// `let leet_decoder = Decoder::<LeetDecoder>::new()` to create a new instance
/// And then call:
/// `result = leet_decoder.crack(input)` to decode a leetspeak string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::leet_decoder::LeetDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_leet = Decoder::<LeetDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_leet.crack("h3ll0 w0rld", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct LeetDecoder;

impl Crack for Decoder<LeetDecoder> {
    fn new() -> Decoder<LeetDecoder> {
        Decoder {
            name: "Leetspeak",
            description: "Leetspeak (also known as leet, leetspeak, or 1337) is a system of modified spellings used primarily on the Internet. It often uses character replacements in ways that play on the similarity of their glyphs via reflection and other resemblance. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Leet",
            tags: vec!["leet", "substitution", "decoder"],
            popularity: 0.6,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Leetspeak with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        if text.is_empty() {
            return results;
        }

        let decoded_text = leet_to_text(text);
        if decoded_text == text {
            // No leet substitutions were found, so the input is not leetspeak.
            return results;
        }

        let checker_result = checker
            .with_sensitivity(Sensitivity::Medium)
            .check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Converts a leetspeak string to plaintext by mapping the common leet
/// substitutions to their letters. Characters that are not part of the leet
/// mapping are preserved unchanged.
fn leet_to_text(text: &str) -> String {
    let mut mapping = HashMap::new();
    mapping.insert('4', 'a');
    mapping.insert('@', 'a');
    mapping.insert('8', 'b');
    mapping.insert('(', 'c');
    mapping.insert('{', 'c');
    mapping.insert('3', 'e');
    mapping.insert('€', 'e');
    mapping.insert('6', 'g');
    mapping.insert('#', 'h');
    mapping.insert('1', 'l');
    mapping.insert('!', 'i');
    mapping.insert('|', 'l');
    mapping.insert('7', 't');
    mapping.insert('+', 't');
    mapping.insert('9', 'g');
    mapping.insert('0', 'o');
    mapping.insert('$', 's');
    mapping.insert('5', 's');
    mapping.insert('2', 'z');

    text.chars()
        .map(|c| {
            let lower = c.to_ascii_lowercase();
            *mapping.get(&lower).unwrap_or(&lower)
        })
        .collect::<String>()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    #[test]
    fn test_leet_known_vector() {
        assert_eq!(leet_to_text("h3ll0"), "hello");
        assert_eq!(leet_to_text("1337"), "leet");
        assert_eq!(leet_to_text("w0rld"), "world");
    }

    #[test]
    fn test_leet_crack() {
        let leet_decoder = Decoder::<LeetDecoder>::new();
        let result = leet_decoder
            .crack("1 l0v3 l33t", &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Leet decoder");
        assert_eq!(result[0], "l love leet");
    }

    #[test]
    fn test_leet_empty_input() {
        let leet_decoder = Decoder::<LeetDecoder>::new();
        let result = leet_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_leet_no_substitutions() {
        let leet_decoder = Decoder::<LeetDecoder>::new();
        // No leet substitutions, so the decoder should not claim a match.
        let result = leet_decoder
            .crack("hello world", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_leet_mixed_case() {
        assert_eq!(leet_to_text("H3LL0"), "hello");
    }
}
