//! Decode a NATO phonetic alphabet string
//! The NATO phonetic alphabet (also called the International Radiotelephony
//! Spelling Alphabet) maps each letter to a code word such as "ALPHA" or
//! "BRAVO". This decoder matches space-separated words against the code word
//! table and returns the corresponding letters.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};
use std::collections::HashMap;

/// The 26 NATO code words, indexed by their plaintext letter (A=0, B=1, ...).
const NATO_WORDS: [&str; 26] = [
    "ALPHA", "BRAVO", "CHARLIE", "DELTA", "ECHO", "FOXTROT", "GOLF", "HOTEL", "INDIA", "JULIETT",
    "KILO", "LIMA", "MIKE", "NOVEMBER", "OSCAR", "PAPA", "QUEBEC", "ROMEO", "SIERRA", "TANGO",
    "UNIFORM", "VICTOR", "WHISKEY", "XRAY", "YANKEE", "ZULU",
];

/// The NATO phonetic decoder, call:
/// `let nato_decoder = Decoder::<NatoDecoder>::new()` to create a new instance
/// And then call:
/// `result = nato_decoder.crack(input)` to decode a NATO phonetic string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::nato_decoder::NatoDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_nato = Decoder::<NatoDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_nato.crack("FOXTROT LIMA ECHO ECHO ALPHA TANGO OSCAR NOVEMBER CHARLIE ECHO", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct NatoDecoder;

impl Crack for Decoder<NatoDecoder> {
    fn new() -> Decoder<NatoDecoder> {
        Decoder {
            name: "NATO phonetic alphabet",
            description: "The NATO phonetic alphabet is the most widely used radiotelephone spelling alphabet. It is used to spell out words, parts of words, or sequences of numbers by replacing each letter with a code word. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/NATO_phonetic_alphabet",
            tags: vec!["nato", "phonetic", "substitution"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying NATO phonetic alphabet with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let words: Vec<&str> = text.split_whitespace().collect();
        if words.len() < 2 {
            debug!("Input too short for NATO phonetic analysis");
            return results;
        }

        let decoded = nato_decrypt(text);
        if decoded.is_empty() {
            debug!("Input does not look like NATO phonetic code words");
            return results;
        }

        let checker_result = checker
            .with_sensitivity(Sensitivity::Medium)
            .check(&decoded);
        if checker_result.is_identified || decoded.len() >= 8 {
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&checker_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decrypt a NATO phonetic alphabet message into plaintext letters.
///
/// The message is a whitespace-separated sequence of code words. Every word
/// must match a NATO code word (case-insensitively); unknown words make the
/// whole input invalid. Returns an empty string when the input cannot be
/// decrypted.
pub fn nato_decrypt(ciphertext: &str) -> String {
    let mut word_to_letter = HashMap::new();
    for (i, word) in NATO_WORDS.iter().enumerate() {
        word_to_letter.insert(*word, (b'A' + i as u8) as char);
    }

    let words: Vec<&str> = ciphertext.split_whitespace().collect();
    if words.is_empty() {
        return String::new();
    }

    let mut result = String::with_capacity(words.len());
    for word in words {
        let upper = word.to_ascii_uppercase();
        match word_to_letter.get(upper.as_str()) {
            Some(&letter) => result.push(letter),
            None => return String::new(),
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str) -> String {
        text.chars()
            .filter(|c| c.is_ascii_alphabetic())
            .map(|c| NATO_WORDS[(c.to_ascii_uppercase() as u8 - b'A') as usize])
            .collect::<Vec<_>>()
            .join(" ")
    }

    #[test]
    fn test_nato_roundtrip() {
        let plaintext = "HELLO";
        let ciphertext = encrypt(plaintext);
        assert_eq!(nato_decrypt(&ciphertext), plaintext);
    }

    #[test]
    fn test_nato_known_vector() {
        // A=ALPHA, B=BRAVO, C=CHARLIE, D=DELTA
        assert_eq!(nato_decrypt("ALPHA BRAVO CHARLIE DELTA"), "ABCD");
    }

    #[test]
    fn test_nato_case_insensitive() {
        assert_eq!(nato_decrypt("alpha bravo"), "AB");
    }

    #[test]
    fn test_nato_crack() {
        let plaintext = "FLEEATONCE";
        let ciphertext = encrypt(plaintext);
        let nato_decoder = Decoder::<NatoDecoder>::new();
        let result = nato_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for NATO decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_nato_empty_input() {
        let nato_decoder = Decoder::<NatoDecoder>::new();
        let result = nato_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_nato_invalid_word() {
        let nato_decoder = Decoder::<NatoDecoder>::new();
        // "HELLO" is not a NATO code word.
        let result = nato_decoder
            .crack("ALPHA HELLO BRAVO", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
