//! Decode a Nihilist cipher string
//! The Nihilist cipher encrypts plaintext by replacing each letter with its
//! Polybius square coordinate (a two digit number) and then adding the
//! coordinate of a key letter. The ciphertext is therefore a sequence of
//! numbers. Decryption subtracts the key coordinate from each number.
//! This implementation uses the standard alphabet (I/J merged) for the
//! Polybius square and attempts to recover short numeric keys by brute force.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// Standard Polybius square alphabet with I/J merged into a 5x5 grid.
const POLYBIUS_ALPHABET: [char; 25] = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
    'U', 'V', 'W', 'X', 'Y', 'Z',
];

/// The Nihilist decoder, call:
/// `let nihilist_decoder = Decoder::<NihilistDecoder>::new()` to create a new instance
/// And then call:
/// `result = nihilist_decoder.crack(input)` to decode a Nihilist cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::nihilist_decoder::NihilistDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_nihilist = Decoder::<NihilistDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_nihilist.crack("225555222436225525226344", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct NihilistDecoder;

impl Crack for Decoder<NihilistDecoder> {
    fn new() -> Decoder<NihilistDecoder> {
        Decoder {
            name: "Nihilist",
            description: "The Nihilist cipher is a manually operated symmetric encryption cipher, originally used by Russian Nihilists. It uses a Polybius square to convert letters to coordinates, then adds a key. This implementation uses the standard 5x5 alphabet and attempts to recover short numeric keys. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Nihilist_cipher",
            tags: vec!["polybius", "classical", "auto-crack"],
            popularity: 0.2,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Nihilist Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        // Nihilist ciphertext is a stream of two digit numbers.
        let clean: String = text.chars().filter(|c| c.is_ascii_digit()).collect();
        if clean.len() < 8 || !clean.len().is_multiple_of(2) {
            debug!(
                "Input does not look like a Nihilist ciphertext (even length of digits required)"
            );
            return results;
        }

        // Try to recover the key. For short plaintexts, brute force a single
        // letter key; for longer ones, brute force two letter keys.
        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let mut best_result: Option<(String, String)> = None;

        let key_space = if clean.len() > 40 { 2 } else { 1 };
        for key_len in 1..=key_space {
            let mut key: Vec<u8> = vec![0; key_len];
            let mut done = false;
            while !done {
                let key_str = key
                    .iter()
                    .map(|&i| POLYBIUS_ALPHABET[i as usize])
                    .collect::<String>();
                if let Some(decoded) = nihilist_decrypt_with_key(&clean, &key_str) {
                    let check_result = checker_with_sensitivity.check(&decoded);
                    if check_result.is_identified {
                        results.unencrypted_text = Some(vec![decoded]);
                        results.update_checker(&check_result);
                        results.key = Some(key_str);
                        return results;
                    }
                    if best_result.is_none() {
                        best_result = Some((key_str, decoded));
                    }
                }
                // Increment the key counter.
                let mut i = key_len;
                loop {
                    if i == 0 {
                        done = true;
                        break;
                    }
                    i -= 1;
                    key[i] += 1;
                    if key[i] < 25 {
                        break;
                    }
                    key[i] = 0;
                }
            }
        }

        if let Some((key, decoded)) = best_result {
            let check_result = checker_with_sensitivity.check(&decoded);
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&check_result);
            results.key = Some(key);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Get the Polybius coordinate (1-indexed, e.g. 11..55) of a letter.
fn polybius_coord(c: char) -> Option<u8> {
    let upper = c.to_ascii_uppercase();
    let idx = if upper == 'J' { 'I' } else { upper };
    POLYBIUS_ALPHABET.iter().position(|&x| x == idx).map(|i| {
        let row = (i / 5 + 1) as u8;
        let col = (i % 5 + 1) as u8;
        row * 10 + col
    })
}

/// Decrypt a Nihilist ciphertext (a stream of two digit numbers) using the
/// given key. Returns None if the plaintext cannot be mapped back to letters.
fn nihilist_decrypt_with_key(ciphertext: &str, key: &str) -> Option<String> {
    // Compute the key coordinate stream from the key letters.
    let mut key_coords: Vec<u8> = Vec::with_capacity(key.len());
    for c in key.chars() {
        key_coords.push(polybius_coord(c)?);
    }
    if key_coords.is_empty() {
        return None;
    }

    let digits: Vec<u8> = ciphertext
        .chars()
        .filter(|c| c.is_ascii_digit())
        .map(|c| c.to_digit(10).unwrap() as u8)
        .collect();

    let mut result = String::new();
    let mut idx = 0;
    while idx + 1 < digits.len() {
        let value = digits[idx] * 10 + digits[idx + 1];
        let key_coord = key_coords[(idx / 2) % key_coords.len()];
        // Subtract the key coordinate, wrapping if the ciphertext is less.
        let plain_coord = if value >= key_coord {
            value - key_coord
        } else {
            // Handle the case where the value wrapped around the grid. The
            // maximum coordinate is 55, so the plain coordinate can be
            // recovered by adding 100 and subtracting (rough heuristic).
            value + 100 - key_coord
        };
        if !(11..=55).contains(&plain_coord) {
            return None;
        }
        let row = (plain_coord / 10) as usize;
        let col = (plain_coord % 10) as usize;
        if !(1..=5).contains(&row) || !(1..=5).contains(&col) {
            return None;
        }
        result.push(POLYBIUS_ALPHABET[(row - 1) * 5 + (col - 1)]);
        idx += 2;
    }
    Some(result)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str, key: &str) -> String {
        let mut key_coords: Vec<u8> = Vec::new();
        for c in key.chars() {
            if let Some(coord) = polybius_coord(c) {
                key_coords.push(coord);
            }
        }
        let mut result = String::new();
        let mut idx = 0;
        for c in text.chars() {
            if let Some(plain_coord) = polybius_coord(c) {
                let key_coord = key_coords[idx % key_coords.len()];
                let value = plain_coord + key_coord;
                result.push_str(&format!("{:02}", value));
                idx += 1;
            }
        }
        result
    }

    #[test]
    fn test_nihilist_decrypt_known_key() {
        // "HELLO" with key "A" (coord 11): plain coords 23 15 31 31 34
        // => cipher 34 26 42 42 45
        let decrypted = nihilist_decrypt_with_key("3426424245", "A").unwrap();
        assert_eq!(decrypted, "HELLO");
    }

    #[test]
    fn test_nihilist_roundtrip() {
        // Key "A" (coord 11) keeps all ciphertexts at two digits
        // (max plaintext coord 55 + 11 = 66).
        let plaintext = "HELLOWORLD";
        let key = "A";
        let ciphertext = encrypt(plaintext, key);
        let decrypted = nihilist_decrypt_with_key(&ciphertext, key).unwrap();
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn test_nihilist_auto_crack() {
        let plaintext = "ATTACKATDAWN";
        let key = "A";
        let ciphertext = encrypt(plaintext, key);
        let nihilist_decoder = Decoder::<NihilistDecoder>::new();
        let result = nihilist_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Nihilist decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_nihilist_polybius_coord() {
        assert_eq!(polybius_coord('A'), Some(11));
        assert_eq!(polybius_coord('E'), Some(15));
        assert_eq!(polybius_coord('Z'), Some(55));
        // J maps to I (24)
        assert_eq!(polybius_coord('J'), Some(24));
    }

    #[test]
    fn test_nihilist_invalid_input() {
        let nihilist_decoder = Decoder::<NihilistDecoder>::new();
        let result = nihilist_decoder
            .crack("abc", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_nihilist_empty_input() {
        let nihilist_decoder = Decoder::<NihilistDecoder>::new();
        let result = nihilist_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
