//! Decode a Pigpen cipher string
//! The Pigpen cipher (also known as the Freemason's cipher) substitutes each
//! letter with a symbol drawn from a grid of lines and dots. The symbols are
//! mapped back to letters by their position in the grids: the first grid of
//! nine letters uses no dot, the second uses a dot, the third is an X-shaped
//! grid, and the fourth adds a dot to the X grid.

use crate::checkers::CheckerTypes;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::trace;
use std::collections::HashMap;

/// The Pigpen decoder, call:
/// `let pigpen_decoder = Decoder::<PigpenDecoder>::new()` to create a new instance
/// And then call:
/// `result = pigpen_decoder.crack(input)` to decode a Pigpen cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::pigpen_decoder::PigpenDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_pigpen = Decoder::<PigpenDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_pigpen.crack("◷◴◻◻◾", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct PigpenDecoder;

impl Crack for Decoder<PigpenDecoder> {
    fn new() -> Decoder<PigpenDecoder> {
        Decoder {
            name: "Pigpen cipher",
            description: "The Pigpen cipher (sometimes referred to as the masonic cipher, Freemason's cipher, or Rosicrucian cipher) is a geometric simple substitution cipher which exchanges letters for symbols which are fragments of a grid. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Pigpen_cipher",
            tags: vec!["pigpen", "substitution", "classical"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Pigpen cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        if text.is_empty() {
            return results;
        }

        let decoded_text = pigpen_to_text(text);
        if decoded_text == text {
            // No Pigpen symbols were present, so the input is not Pigpen.
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Converts Pigpen Unicode symbols to their corresponding Latin letters.
///
/// The mapping covers the four standard Pigpen grids:
/// - `◰`-`◸` (grid 1) and `◹`-`◿`-`◴`-`◵`-`◶`-`◷` (grid 2 with dot) are the
///   nine-square grids; letters A-I and J-R.
/// - The X grids use `◤◥◢◣`-based characters for S-Z.
fn pigpen_to_text(text: &str) -> String {
    let mut mapping = HashMap::new();
    // Grid 1 (no dot): A-I
    mapping.insert('◰', 'a');
    mapping.insert('◱', 'b');
    mapping.insert('◲', 'c');
    mapping.insert('◳', 'd');
    mapping.insert('◴', 'e');
    mapping.insert('◵', 'f');
    mapping.insert('◶', 'g');
    mapping.insert('◷', 'h');
    mapping.insert('◸', 'i');
    // Grid 2 (dot): J-R
    mapping.insert('◹', 'j');
    mapping.insert('◺', 'k');
    mapping.insert('◻', 'l');
    mapping.insert('◼', 'm');
    mapping.insert('◽', 'n');
    mapping.insert('◾', 'o');
    mapping.insert('◿', 'p');
    mapping.insert('⬔', 'q');
    mapping.insert('⬕', 'r');
    // X grids: S-Z (the X grid characters are the corner pieces).
    mapping.insert('◤', 's');
    mapping.insert('◥', 't');
    mapping.insert('◢', 'u');
    mapping.insert('◣', 'v');
    mapping.insert('⬓', 'w');
    mapping.insert('⬒', 'x');
    mapping.insert('⬑', 'y');
    mapping.insert('⬐', 'z');

    text.chars()
        .map(|c| *mapping.get(&c).unwrap_or(&c))
        .collect::<String>()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str) -> String {
        // Symbols ordered to match the letter mapping used in pigpen_to_text.
        let symbols = [
            '◰', '◱', '◲', '◳', '◴', '◵', '◶', '◷', '◸', '◹', '◺', '◻', '◼', '◽', '◾', '◿', '⬔',
            '⬕', '◤', '◥', '◢', '◣', '⬓', '⬒', '⬑', '⬐',
        ];
        let sym_to_letter: HashMap<char, char> = symbols
            .iter()
            .enumerate()
            .map(|(i, &s)| (s, (b'a' + i as u8) as char))
            .collect();
        text.chars()
            .map(|c| {
                sym_to_letter
                    .iter()
                    .find(|(_, &v)| v == c.to_ascii_lowercase())
                    .map(|(&k, _)| k)
                    .unwrap_or(c)
            })
            .collect()
    }

    #[test]
    fn test_pigpen_roundtrip() {
        let plaintext = "hello";
        let ciphertext = encrypt(plaintext);
        assert_eq!(pigpen_to_text(&ciphertext), plaintext);
    }

    #[test]
    fn test_pigpen_known_vector() {
        // "a" => ◰, "r" => ⬕
        assert_eq!(pigpen_to_text("◰"), "a");
        assert_eq!(pigpen_to_text("⬕"), "r");
    }

    #[test]
    fn test_pigpen_crack() {
        let plaintext = "hello";
        let ciphertext = encrypt(plaintext);
        let pigpen_decoder = Decoder::<PigpenDecoder>::new();
        let result = pigpen_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Pigpen decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_pigpen_empty_input() {
        let pigpen_decoder = Decoder::<PigpenDecoder>::new();
        let result = pigpen_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_pigpen_no_symbols() {
        let pigpen_decoder = Decoder::<PigpenDecoder>::new();
        // No Pigpen symbols in the input; the decoder should not claim a match.
        let result = pigpen_decoder
            .crack("HELLO", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
