//! Decode a Playfair cipher string
//! The Playfair cipher is a digraph substitution cipher using a 5x5 square
//! built from a keyword. Each pair of plaintext letters is replaced according
//! to their positions in the square: same row shifts right, same column
//! shifts down, otherwise a rectangle swap. This implementation supports
//! decryption with a keyword and attempts a small list of common keywords.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};
use super::polybius_decoder::POLYBIUS_ALPHABET;

use log::{debug, trace};

/// Common Playfair keywords to try when cracking.
const COMMON_KEYS: [&str; 8] = [
    "PLAYFAIR", "MONARCHY", "KEYWORD", "CIPHER", "SECRET", "CRYPTO", "ENIGMA", "LIONEL",
];

/// The Playfair decoder, call:
/// `let playfair_decoder = Decoder::<PlayfairDecoder>::new()` to create a new instance
/// And then call:
/// `result = playfair_decoder.crack(input)` to decode a Playfair cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::playfair_decoder::PlayfairDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_playfair = Decoder::<PlayfairDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_playfair.crack("CLKLCLRSNAEL", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct PlayfairDecoder;

impl Crack for Decoder<PlayfairDecoder> {
    fn new() -> Decoder<PlayfairDecoder> {
        Decoder {
            name: "Playfair",
            description: "The Playfair cipher or Playfair square is a manual symmetric encryption technique and was the first literal digraph substitution cipher. The scheme was invented in 1854 by Charles Wheatstone. It encrypts pairs of letters using a 5x5 square built from a keyword. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Playfair_cipher",
            tags: vec!["polygraphic", "classical", "auto-crack"],
            popularity: 0.45,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Playfair Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let clean_text: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();
        if clean_text.len() < 8 {
            debug!("Input text too short for Playfair analysis");
            return results;
        }

        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let mut best_result: Option<String> = None;

        for &key in &COMMON_KEYS {
            let decoded = playfair_decrypt(&clean_text, key);
            if decoded.is_empty() {
                continue;
            }
            let check_result = checker_with_sensitivity.check(&decoded);
            if check_result.is_identified {
                results.unencrypted_text = Some(vec![decoded]);
                results.update_checker(&check_result);
                results.key = Some(key.to_string());
                return results;
            }
            if best_result.is_none() {
                best_result = Some(decoded);
            }
        }

        if let Some(decoded) = best_result {
            let check_result = checker_with_sensitivity.check(&decoded);
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&check_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Build a 5x5 Playfair square from a keyword using the standard alphabet
/// (I/J merged).
fn build_square(keyword: &str) -> [[char; 5]; 5] {
    let mut used = [false; 25];
    let mut square = [[' '; 5]; 5];
    let mut pos = 0;
    for c in keyword.chars().chain(POLYBIUS_ALPHABET.iter().copied()) {
        let upper = c.to_ascii_uppercase();
        let letter = if upper == 'J' { 'I' } else { upper };
        if let Some(idx) = POLYBIUS_ALPHABET.iter().position(|&x| x == letter) {
            if !used[idx] {
                used[idx] = true;
                square[pos / 5][pos % 5] = POLYBIUS_ALPHABET[idx];
                pos += 1;
            }
        }
        if pos == 25 {
            break;
        }
    }
    square
}

/// Find the (row, col) position of a letter in the square.
fn find_pos(square: &[[char; 5]; 5], c: char) -> (usize, usize) {
    square
        .iter()
        .enumerate()
        .find_map(|(r, row)| row.iter().position(|&x| x == c).map(|col| (r, col)))
        .unwrap_or_else(|| panic!("letter {c} not in Playfair square"))
}

/// Decrypt a Playfair ciphertext with the given keyword. Returns an empty
/// string when the input cannot be decrypted.
pub fn playfair_decrypt(ciphertext: &str, keyword: &str) -> String {
    let clean: Vec<char> = ciphertext
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .map(|c| c.to_ascii_uppercase())
        .map(|c| if c == 'J' { 'I' } else { c })
        .filter(|c| POLYBIUS_ALPHABET.contains(c))
        .collect();
    if clean.len() < 2 || !clean.len().is_multiple_of(2) {
        return String::new();
    }

    let square = build_square(keyword);
    let mut result = String::with_capacity(clean.len());
    let mut idx = 0;
    while idx + 1 < clean.len() {
        let (r1, c1) = find_pos(&square, clean[idx]);
        let (r2, c2) = find_pos(&square, clean[idx + 1]);
        let (nr1, nc1, nr2, nc2) = if r1 == r2 {
            // Same row: shift each letter left by one.
            (r1, (c1 + 4) % 5, r2, (c2 + 4) % 5)
        } else if c1 == c2 {
            // Same column: shift each letter up by one.
            ((r1 + 4) % 5, c1, (r2 + 4) % 5, c2)
        } else {
            // Rectangle swap.
            (r1, c2, r2, c1)
        };
        result.push(square[nr1][nc1]);
        result.push(square[nr2][nc2]);
        idx += 2;
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str, keyword: &str) -> String {
        let clean: Vec<char> = text
            .chars()
            .map(|c| c.to_ascii_uppercase())
            .map(|c| if c == 'J' { 'I' } else { c })
            .filter(|c| POLYBIUS_ALPHABET.contains(c))
            .collect();
        let square = build_square(keyword);
        let mut result = String::new();
        let mut idx = 0;
        while idx + 1 < clean.len() {
            let (r1, c1) = find_pos(&square, clean[idx]);
            let (r2, c2) = find_pos(&square, clean[idx + 1]);
            let (nr1, nc1, nr2, nc2) = if r1 == r2 {
                (r1, (c1 + 1) % 5, r2, (c2 + 1) % 5)
            } else if c1 == c2 {
                ((r1 + 1) % 5, c1, (r2 + 1) % 5, c2)
            } else {
                (r1, c2, r2, c1)
            };
            result.push(square[nr1][nc1]);
            result.push(square[nr2][nc2]);
            idx += 2;
        }
        result
    }

    #[test]
    fn test_playfair_roundtrip() {
        // Classic example: keyword MONARCHY, plaintext HELLO padded with X.
        let plaintext = "HELLOX";
        let keyword = "MONARCHY";
        let ciphertext = encrypt(plaintext, keyword);
        assert_eq!(playfair_decrypt(&ciphertext, keyword), plaintext);
    }

    #[test]
    fn test_playfair_known_vector() {
        // Wikipedia example: keyword MONARCHY, "WE" => "UG" and "AR" => "RM"
        // with the standard square.
        assert_eq!(playfair_decrypt("UGRM", "MONARCHY"), "WEAR");
    }

    #[test]
    fn test_playfair_crack() {
        let plaintext = "MEETMEATONCE";
        let keyword = "MONARCHY";
        let ciphertext = encrypt(plaintext, keyword);
        let playfair_decoder = Decoder::<PlayfairDecoder>::new();
        let result = playfair_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Playfair decoder");
        assert_eq!(result[0].trim(), plaintext);
    }

    #[test]
    fn test_playfair_empty_input() {
        let playfair_decoder = Decoder::<PlayfairDecoder>::new();
        let result = playfair_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_playfair_short_input() {
        let playfair_decoder = Decoder::<PlayfairDecoder>::new();
        let result = playfair_decoder
            .crack("AB", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
