//! Decode a Polybius square cipher string
//! The Polybius square is a 5x5 grid of letters (I/J merged) where each letter
//! is replaced by its row and column numbers. The ciphertext is a sequence of
//! coordinate pairs such as `442315`.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// Standard Polybius square alphabet with I/J merged into a 5x5 grid.
pub const POLYBIUS_ALPHABET: [char; 25] = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
    'U', 'V', 'W', 'X', 'Y', 'Z',
];

/// The Polybius decoder, call:
/// `let polybius_decoder = Decoder::<PolybiusDecoder>::new()` to create a new instance
/// And then call:
/// `result = polybius_decoder.crack(input)` to decode a Polybius square cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::polybius_decoder::PolybiusDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_polybius = Decoder::<PolybiusDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_polybius.crack("114444111325114414115233", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct PolybiusDecoder;

impl Crack for Decoder<PolybiusDecoder> {
    fn new() -> Decoder<PolybiusDecoder> {
        Decoder {
            name: "Polybius",
            description: "The Polybius square is a device invented by the ancient Greek historian Polybius for fractionating plaintext characters so that they can be represented by a smaller set of symbols. Each letter is replaced by its row and column coordinates in a 5x5 square. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Polybius_square",
            tags: vec!["polybius", "classical", "fractionated"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Polybius Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        // The ciphertext is a stream of digits; the plaintext is recovered by
        // grouping them into coordinate pairs. Try all plausible groupings
        // (different separators are handled by just keeping digits).
        let clean: String = text.chars().filter(|c| c.is_ascii_digit()).collect();
        if clean.len() < 4 || !clean.len().is_multiple_of(2) {
            debug!(
                "Input does not look like a Polybius ciphertext (even length of digits required)"
            );
            return results;
        }

        let decoded = polybius_decrypt(&clean);
        if decoded.is_empty() {
            return results;
        }
        let checker_result = checker
            .with_sensitivity(Sensitivity::Medium)
            .check(&decoded);
        if checker_result.is_identified || decoded.len() >= 10 {
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&checker_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode a Polybius square ciphertext (a stream of digits grouped into
/// coordinate pairs) into plaintext. Non-digit characters are ignored.
pub fn polybius_decrypt(ciphertext: &str) -> String {
    let digits: Vec<u8> = ciphertext
        .chars()
        .filter(|c| c.is_ascii_digit())
        .map(|c| c.to_digit(10).unwrap() as u8)
        .collect();
    let mut result = String::with_capacity(digits.len() / 2);
    let mut idx = 0;
    while idx + 1 < digits.len() {
        let row = digits[idx];
        let col = digits[idx + 1];
        if !(1..=5).contains(&row) || !(1..=5).contains(&col) {
            return String::new();
        }
        result.push(POLYBIUS_ALPHABET[((row - 1) * 5 + (col - 1)) as usize]);
        idx += 2;
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str) -> String {
        let mut result = String::new();
        for c in text.chars() {
            let upper = c.to_ascii_uppercase();
            let letter = if upper == 'J' { 'I' } else { upper };
            if let Some(pos) = POLYBIUS_ALPHABET.iter().position(|&x| x == letter) {
                let row = pos / 5 + 1;
                let col = pos % 5 + 1;
                result.push_str(&format!("{row}{col}"));
            }
        }
        result
    }

    #[test]
    fn test_polybius_decrypt_known() {
        // "ATTACK" => A=11, T=44, T=44, A=11, C=13, K=25
        assert_eq!(polybius_decrypt("114444111325"), "ATTACK");
    }

    #[test]
    fn test_polybius_roundtrip() {
        let plaintext = "ATTACKATDAWN";
        let ciphertext = encrypt(plaintext);
        assert_eq!(polybius_decrypt(&ciphertext), plaintext);
    }

    #[test]
    fn test_polybius_crack() {
        let plaintext = "ATTACKATDAWN";
        let ciphertext = encrypt(plaintext);
        let polybius_decoder = Decoder::<PolybiusDecoder>::new();
        let result = polybius_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Polybius decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_polybius_empty_input() {
        let polybius_decoder = Decoder::<PolybiusDecoder>::new();
        let result = polybius_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_polybius_odd_length_input() {
        let polybius_decoder = Decoder::<PolybiusDecoder>::new();
        let result = polybius_decoder
            .crack("12345", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
