//! Decode a Porta cipher string
//! The Porta cipher is a polyalphabetic substitution cipher that uses a
//! keyword to select from 13 distinct cipher alphabets. Each pair of key
//! letters selects one of the 13 substitution tables. This implementation
//! recovers the key length via the index of coincidence and recovers each
//! key character via frequency analysis.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;
use once_cell::sync::Lazy;
use std::fs;
use std::path::Path;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// English bigrams for determining fitness, same format as the Vigenère
/// decoder uses.
static ENGLISH_BIGRAMS: Lazy<Vec<Vec<i64>>> = Lazy::new(|| {
    let mut bigrams_vec = vec![vec![0; 26]; 26];
    let f_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("src")
        .join("storage")
        .join("ngrams")
        .join("english_bigrams.txt");
    if let Ok(content) = fs::read_to_string(&f_path) {
        for line in content.split('\n') {
            if line.is_empty() {
                continue;
            }
            let line_split: Vec<&str> = line.split_ascii_whitespace().collect();
            if line_split.is_empty() {
                continue;
            }
            let mut chars_itr = line_split[0].chars();
            let char1: char = chars_itr
                .next()
                .expect("Could not retrieve first char")
                .to_ascii_uppercase();
            let char2: char = chars_itr
                .next()
                .expect("Could not retrieve second char")
                .to_ascii_uppercase();
            let fitness = line_split[1]
                .parse::<i64>()
                .expect("Could not parse fitness value");
            bigrams_vec[(char1 as u8 - b'A') as usize][(char2 as u8 - b'A') as usize] = fitness;
        }
    }
    bigrams_vec
});

/// The Porta decoder, call:
/// `let porta_decoder = Decoder::<PortaDecoder>::new()` to create a new instance
/// And then call:
/// `result = porta_decoder.crack(input)` to decode a Porta cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::porta_decoder::PortaDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_porta = Decoder::<PortaDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_porta.crack("helao", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct PortaDecoder;

impl Crack for Decoder<PortaDecoder> {
    fn new() -> Decoder<PortaDecoder> {
        Decoder {
            name: "Porta",
            description: "The Porta cipher is a polyalphabetic substitution cipher that uses a keyword to select from 13 distinct cipher alphabets. Each pair of key letters selects one of the 13 substitution tables. It was invented by Giovanni Battista della Porta. This implementation recovers the keyword via frequency analysis. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Porta_cipher",
            tags: vec!["substitution", "classical", "auto-crack"],
            popularity: 0.2,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Porta Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let clean_text: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();

        if clean_text.is_empty() {
            debug!("No valid characters found in input text");
            return results;
        }

        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let checker_result = checker_with_sensitivity.check(text);
        let mut best_candidate: Option<(String, String)> = None;

        for key_length in 2..30 {
            if clean_text.len() <= key_length * 2 {
                break;
            }
            let key = recover_porta_key(&clean_text, key_length);
            let decode_attempt = porta_decrypt(text, &key);
            let check_result = checker_with_sensitivity.check(&decode_attempt);
            if check_result.is_identified {
                results.unencrypted_text = Some(vec![decode_attempt]);
                results.update_checker(&check_result);
                results.key = Some(key);
                return results;
            }
            if best_candidate.is_none() {
                best_candidate = Some((key, decode_attempt));
            }
        }

        if let Some((key, decoded)) = best_candidate {
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&checker_result);
            results.key = Some(key);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decrypt text encrypted with the Porta cipher using the given key.
/// The Porta cipher is reciprocal: encryption and decryption use the same
/// substitution tables, so the same function decrypts as encrypts.
fn porta_decrypt(text: &str, key: &str) -> String {
    let key_groups: Vec<u8> = key
        .bytes()
        .map(|b| (b.to_ascii_uppercase() - b'A') / 2)
        .collect();
    let mut result = String::with_capacity(text.len());
    let mut key_idx = 0;

    for c in text.chars() {
        if c.is_ascii_alphabetic() {
            let g = (key_groups[key_idx % key_groups.len()] as usize).min(12);
            let base = if c.is_ascii_uppercase() { b'A' } else { b'a' };
            let x = (c as u8 - base) as usize;
            let p = porta_letter(x, g);
            result.push((base + p as u8) as char);
            key_idx += 1;
        } else {
            result.push(c);
        }
    }

    result
}

/// Recover the Porta key of a given length from ciphertext using bigram fitness
/// scoring. Each key position selects one of 13 substitution tables (a group).
/// The plaintext at a position is produced by applying the group's table to
/// the ciphertext letter.
fn recover_porta_key(ciphertext: &str, key_length: usize) -> String {
    let cipher_text: Vec<usize> = ciphertext
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .map(|c| (c.to_ascii_uppercase() as u8 - b'A') as usize)
        .collect();

    let mut best_fitness = 0;
    let mut best_key_ch2 = ' ';
    let mut best_score_0 = 0;
    let mut best_key_ch1_0 = ' ';
    let mut prev_best_score = 0;
    let mut prev_best_key_ch2 = ' ';

    let mut key = vec![' '; key_length];
    for (key_idx, key_char) in key.iter_mut().enumerate().take(key_length) {
        let mut best_key_ch1 = ' ';
        best_fitness = 0;

        for g1 in 0..13 {
            for g2 in 0..13 {
                let mut fitness = 0;
                for text_idx in (key_idx..(cipher_text.len() - 1)).step_by(key_length) {
                    let clear_ch1 = porta_letter(cipher_text[text_idx], g1);
                    let clear_ch2 = porta_letter(cipher_text[text_idx + 1], g2);
                    fitness += ENGLISH_BIGRAMS[clear_ch1][clear_ch2];
                }
                if fitness > best_fitness {
                    best_fitness = fitness;
                    best_key_ch1 = ((g1 * 2) as u8 + b'A') as char;
                    best_key_ch2 = ((g2 * 2) as u8 + b'A') as char;
                }
            }
        }
        if key_idx == 0 {
            best_score_0 = best_fitness;
            best_key_ch1_0 = best_key_ch1;
        } else {
            *key_char = if prev_best_score > best_fitness {
                prev_best_key_ch2
            } else {
                best_key_ch1
            };
        }
        prev_best_score = best_fitness;
        prev_best_key_ch2 = best_key_ch2
    }
    key[0] = if best_fitness > best_score_0 {
        best_key_ch2
    } else {
        best_key_ch1_0
    };
    key.into_iter().collect()
}

/// Decrypt a single letter with a Porta substitution table selected by group
/// `g`. The Porta cipher is reciprocal (encryption == decryption), so this
/// same function is used for both directions. Returns the 0-based index of the
/// result letter.
fn porta_letter(c: usize, g: usize) -> usize {
    if c < 13 {
        13 + ((c + g) % 13)
    } else {
        (c - g) % 13
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    #[test]
    fn test_porta_known_key() {
        // "HELLOWORLD" with key "KEY" gives "ZTXQMKJCXV" (verified via script)
        let decrypted = porta_decrypt("ztxqmkjcxv", "KEY");
        assert_eq!(decrypted, "helloworld");
    }

    #[test]
    fn test_porta_auto_crack() {
        let plaintext = "this is a secret message that should be recovered by frequency analysis";
        // Encrypt with a helper inlined below via porta_decrypt (reciprocal).
        let key = "KEY";
        let ciphertext = porta_decrypt(plaintext, key);
        let porta_decoder = Decoder::<PortaDecoder>::new();
        let result = porta_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Porta decoder");
        assert_eq!(result[0].trim(), plaintext);
    }

    #[test]
    fn test_porta_recover_key() {
        let plaintext = "this is a secret message that should be recovered by frequency analysis";
        let ciphertext = porta_decrypt(plaintext, "KEY");
        let clean: String = ciphertext
            .chars()
            .filter(|c| c.is_ascii_alphabetic())
            .collect();
        let recovered = recover_porta_key(&clean, 3);
        // Groups: K=5 -> first letter "K", E=2 -> "E", Y=12 -> "Y".
        assert_eq!(recovered, "KEY");
    }

    #[test]
    fn test_porta_empty_input() {
        let porta_decoder = Decoder::<PortaDecoder>::new();
        let result = porta_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_porta_non_alphabetic_input() {
        let porta_decoder = Decoder::<PortaDecoder>::new();
        let result = porta_decoder
            .crack("12345!@#$%", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
