//! Decode Punycode labels such as `xn--bcher-kva`.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, info, trace};

/// Punycode base.
const BASE: u32 = 36;
/// Punycode minimum threshold.
const TMIN: u32 = 1;
/// Punycode maximum threshold.
const TMAX: u32 = 26;
/// Punycode bias skew.
const SKEW: u32 = 38;
/// Punycode damping factor.
const DAMP: u32 = 700;
/// Punycode initial bias.
const INITIAL_BIAS: u32 = 72;
/// Punycode initial code point.
const INITIAL_N: u32 = 128;

/// The Punycode decoder, call:
/// `let punycode_decoder = Decoder::<PunycodeDecoder>::new()` to create a new instance
/// And then call:
/// `result = punycode_decoder.crack(input)` to decode Punycode labels
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::punycode_decoder::PunycodeDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_punycode = Decoder::<PunycodeDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_punycode.crack("xn--bcher-kva.example", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "bücher.example");
/// ```
pub struct PunycodeDecoder;

impl Crack for Decoder<PunycodeDecoder> {
    fn new() -> Decoder<PunycodeDecoder> {
        Decoder {
            name: "Punycode",
            description: "Punycode encodes Unicode domain labels into ASCII using the xn-- prefix. This decoder handles prefixed labels and dotted domain names.",
            link: "https://datatracker.ietf.org/doc/html/rfc3492",
            tags: vec!["punycode", "idna", "unicode", "domain", "decoder"],
            popularity: 0.7,
            phantom: std::marker::PhantomData,
        }
    }

    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Punycode with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_punycode_text(text) else {
            debug!("Failed to decode punycode");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!("Failed to decode punycode because check_string_success returned false");
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);
        results
    }

    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    fn get_name(&self) -> &str {
        self.name
    }

    fn get_description(&self) -> &str {
        self.description
    }

    fn get_link(&self) -> &str {
        self.link
    }

    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode a string containing one or more `xn--` labels.
fn decode_punycode_text(text: &str) -> Option<String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return None;
    }

    let mut changed = false;
    let mut labels = Vec::new();
    for label in trimmed.split('.') {
        if let Some(encoded) = label
            .strip_prefix("xn--")
            .or_else(|| label.strip_prefix("XN--"))
        {
            labels.push(decode_punycode_label(encoded)?);
            changed = true;
        } else {
            labels.push(label.to_string());
        }
    }

    changed.then(|| labels.join("."))
}

/// Decode a single Punycode label without the `xn--` prefix.
fn decode_punycode_label(input: &str) -> Option<String> {
    let mut output: Vec<char> = Vec::new();
    let mut encoded = input;

    if let Some(delimiter) = input.rfind('-') {
        let (basic, rest) = input.split_at(delimiter);
        if !basic.is_ascii() {
            return None;
        }
        output.extend(basic.chars());
        encoded = &rest[1..];
    }

    let mut n = INITIAL_N;
    let mut i = 0u32;
    let mut bias = INITIAL_BIAS;
    let mut iter = encoded.chars().peekable();

    while iter.peek().is_some() {
        let old_i = i;
        let mut weight = 1u32;
        let mut k = BASE;

        loop {
            let digit = punycode_digit(iter.next()?)?;
            i = i.checked_add(digit.checked_mul(weight)?)?;
            let threshold = if k <= bias + TMIN {
                TMIN
            } else if k >= bias + TMAX {
                TMAX
            } else {
                k - bias
            };
            if digit < threshold {
                break;
            }
            weight = weight.checked_mul(BASE - threshold)?;
            k = k.checked_add(BASE)?;
        }

        let out_len = output.len() as u32 + 1;
        bias = adapt(i - old_i, out_len, old_i == 0);
        n = n.checked_add(i / out_len)?;
        i %= out_len;
        let ch = char::from_u32(n)?;
        output.insert(i as usize, ch);
        i += 1;
    }

    Some(output.into_iter().collect())
}

/// Decode a Punycode digit.
fn punycode_digit(c: char) -> Option<u32> {
    match c {
        'a'..='z' => Some(c as u32 - 'a' as u32),
        'A'..='Z' => Some(c as u32 - 'A' as u32),
        '0'..='9' => Some(c as u32 - '0' as u32 + 26),
        _ => None,
    }
}

/// Adapt the Punycode bias.
fn adapt(delta: u32, num_points: u32, first_time: bool) -> u32 {
    let mut delta = if first_time { delta / DAMP } else { delta / 2 };
    delta += delta / num_points;

    let mut k = 0;
    while delta > ((BASE - TMIN) * TMAX) / 2 {
        delta /= BASE - TMIN;
        k += BASE;
    }
    k + (((BASE - TMIN + 1) * delta) / (delta + SKEW))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        CheckerTypes::CheckAthena(Checker::<Athena>::new())
    }

    #[test]
    fn successful_decoding() {
        let decoder = Decoder::<PunycodeDecoder>::new();
        let result = decoder
            .crack("xn--bcher-kva.example", &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for punycode");
        assert_eq!(result[0], "bücher.example");
    }

    #[test]
    fn decodes_known_domain_label() {
        assert_eq!(
            decode_punycode_text("xn--bcher-kva.example"),
            Some("bücher.example".to_string())
        );
    }

    #[test]
    fn ignores_unprefixed_input() {
        assert!(decode_punycode_text("example.com").is_none());
    }

    #[test]
    fn invalid_label_returns_none() {
        assert!(decode_punycode_text("xn--***").is_none());
    }
}
