//! Decode a Straddling checkerboard cipher string
//! The straddling checkerboard is a substitution cipher that encodes letters
//! as single digits or pairs of digits. The alphabet is laid out on a grid
//! with a few blank cells in the first row; letters in those columns are
//! encoded as the column digit followed by their row digit. This
//! implementation builds the checkerboard from a keyword and tries a small
//! list of common keywords when cracking.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// Common keywords used to build the straddling checkerboard when cracking.
const COMMON_KEYS: [&str; 8] = [
    "KEYWORD", "CIPHER", "SECRET", "MONARCHY", "ENIGMA", "CRYPTO", "CHECKER", "MESSAGE",
];

/// The Straddling checkerboard decoder, call:
/// `let straddling_decoder = Decoder::<StraddlingCheckerboardDecoder>::new()` to create a new instance
/// And then call:
/// `result = straddling_decoder.crack(input)` to decode a straddling checkerboard string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::straddling_checkerboard_decoder::StraddlingCheckerboardDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_straddling = Decoder::<StraddlingCheckerboardDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_straddling.crack("681172681972469611", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct StraddlingCheckerboardDecoder;

impl Crack for Decoder<StraddlingCheckerboardDecoder> {
    fn new() -> Decoder<StraddlingCheckerboardDecoder> {
        Decoder {
            name: "Straddling checkerboard",
            description: "The straddling checkerboard is a substitution cipher that encodes each letter as either a single digit or a pair of digits, with a variable-length encoding that makes the ciphertext compact. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Straddling_checkerboard",
            tags: vec!["straddling", "checkerboard", "classical"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Straddling checkerboard with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let clean_text: String = text.chars().filter(|c| c.is_ascii_digit()).collect();
        if clean_text.len() < 8 {
            debug!("Input text too short for Straddling checkerboard analysis");
            return results;
        }

        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let mut best_result: Option<String> = None;

        for &key in &COMMON_KEYS {
            let decoded = straddling_decrypt(&clean_text, key);
            if decoded.is_empty() {
                continue;
            }
            let check_result = checker_with_sensitivity.check(&decoded);
            if check_result.is_identified {
                results.unencrypted_text = Some(vec![decoded]);
                results.update_checker(&check_result);
                results.key = Some(key.to_string());
                return results;
            }
            if best_result.is_none() {
                best_result = Some(decoded);
            }
        }

        if let Some(decoded) = best_result {
            let check_result = checker_with_sensitivity.check(&decoded);
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&check_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// The alphabet used in the checkerboard (A-Z, no Q, with . and / for
/// punctuation) — the standard 28-symbol straddling checkerboard.
const CHECKERBOARD_ALPHABET: [char; 28] = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T',
    'U', 'V', 'W', 'X', 'Y', 'Z', '.', '/', ' ',
];

/// Build the checkerboard table from a keyword.
///
/// Returns a 3x10 grid. The first row holds the keyword letters with the two
/// blank (marker) cells fixed at columns 6 and 7. The second and third rows
/// hold the remaining letters of the alphabet.
fn build_checkerboard(keyword: &str) -> [[Option<char>; 10]; 3] {
    let mut used = [false; 28];
    let mut grid = [[None; 10]; 3];

    // The first row has 8 usable cells (columns 6 and 7 are the markers).
    let first_row_cols: [usize; 8] = [0, 1, 2, 3, 4, 5, 8, 9];

    let mut chars: Vec<char> = keyword
        .chars()
        .map(|c| c.to_ascii_uppercase())
        .filter(|c| c.is_ascii_alphabetic() && *c != 'Q')
        .collect();
    chars.extend(CHECKERBOARD_ALPHABET.iter().copied());

    let mut first_row_pos = 0usize;
    let mut later_pos = 0usize;
    for c in chars {
        if let Some(idx) = CHECKERBOARD_ALPHABET.iter().position(|&x| x == c) {
            if !used[idx] {
                used[idx] = true;
                if first_row_pos < first_row_cols.len() {
                    grid[0][first_row_cols[first_row_pos]] = Some(c);
                    first_row_pos += 1;
                } else {
                    let (row, col) = if later_pos < 10 {
                        (1, later_pos)
                    } else {
                        (2, later_pos - 10)
                    };
                    grid[row][col] = Some(c);
                    later_pos += 1;
                }
            }
        }
    }

    grid
}

/// Decrypt a straddling checkerboard ciphertext (a stream of digits) using
/// the checkerboard built from `keyword`. Returns an empty string when the
/// input cannot be decrypted.
pub fn straddling_decrypt(ciphertext: &str, keyword: &str) -> String {
    let clean: String = ciphertext.chars().filter(|c| c.is_ascii_digit()).collect();
    if clean.is_empty() {
        return String::new();
    }

    let grid = build_checkerboard(keyword);
    // The two marker columns are fixed at 6 and 7 in this layout.
    let marker1 = 6usize;
    let marker2 = 7usize;

    let digits: Vec<usize> = clean
        .chars()
        .filter_map(|c| c.to_digit(10).map(|d| d as usize))
        .collect();
    if digits.is_empty() {
        return String::new();
    }

    let mut result = String::with_capacity(digits.len());
    let mut idx = 0;
    while idx < digits.len() {
        let col = digits[idx];
        if col == marker1 || col == marker2 {
            // A marker digit switches to row 1 (marker1) or row 2 (marker2);
            // the next digit is the column in that row.
            if idx + 1 >= digits.len() {
                return String::new();
            }
            let table_col = digits[idx + 1];
            let grid_row = if col == marker1 { 1 } else { 2 };
            if table_col >= 10 {
                return String::new();
            }
            match grid[grid_row][table_col] {
                Some(c) => result.push(c),
                None => return String::new(),
            }
            idx += 2;
        } else {
            // A single digit indexes into the first row.
            if col >= 10 {
                return String::new();
            }
            match grid[0][col] {
                Some(c) => result.push(c),
                None => return String::new(),
            }
            idx += 1;
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str, keyword: &str) -> String {
        let grid = build_checkerboard(keyword);
        let marker1 = 6usize;
        let marker2 = 7usize;
        // Find the row/col of each letter.
        let mut result = String::new();
        for c in text.chars().map(|c| c.to_ascii_uppercase()) {
            if c == 'Q' {
                continue;
            }
            let mut found = false;
            for row in 0..3 {
                for col in 0..10 {
                    if grid[row][col] == Some(c) {
                        if row == 0 {
                            result.push_str(&col.to_string());
                        } else {
                            let marker = if row == 1 { marker1 } else { marker2 };
                            result.push_str(&format!("{marker}{col}"));
                        }
                        found = true;
                        break;
                    }
                }
                if found {
                    break;
                }
            }
        }
        result
    }

    #[test]
    fn test_straddling_roundtrip() {
        let plaintext = "HELLOWORLD";
        let keyword = "KEYWORD";
        let ciphertext = encrypt(plaintext, keyword);
        assert_eq!(straddling_decrypt(&ciphertext, keyword), plaintext);
    }

    #[test]
    fn test_straddling_known_vector() {
        // With keyword KEYWORD, the first row is KEYWORD followed by D, A:
        // K at 0, E at 1, Y at 2, W at 3, O at 4, R at 5, D at 8, A at 9.
        assert_eq!(straddling_decrypt("89", "KEYWORD"), "DA");
    }

    #[test]
    fn test_straddling_crack() {
        let plaintext = "MEETMEATONCE";
        let keyword = "KEYWORD";
        let ciphertext = encrypt(plaintext, keyword);
        let straddling_decoder = Decoder::<StraddlingCheckerboardDecoder>::new();
        let result = straddling_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Straddling checkerboard decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_straddling_empty_input() {
        let straddling_decoder = Decoder::<StraddlingCheckerboardDecoder>::new();
        let result = straddling_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_straddling_invalid_input() {
        let straddling_decoder = Decoder::<StraddlingCheckerboardDecoder>::new();
        // Trailing marker digit cannot be decoded.
        let result = straddling_decoder
            .crack("123456", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
