//! Decode a Tap code cipher string
//! Tap code (also called knock code) encodes each letter as a pair of
//! numbers (row, column) in a 5x5 Polybius square. The digits are usually
//! separated by dots (`.`) and letter pairs by spaces, e.g. `.. ...` is the
//! letter C. This implementation accepts groups of 1-5 dots, separated by
//! dots and spaces, and decodes them with the standard A-Z (I/J merged)
//! square.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};
use super::polybius_decoder::POLYBIUS_ALPHABET;

use log::{debug, trace};

/// The Tap code decoder, call:
/// `let tap_code_decoder = Decoder::<TapCodeDecoder>::new()` to create a new instance
/// And then call:
/// `result = tap_code_decoder.crack(input)` to decode a Tap code string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::tap_code_decoder::TapCodeDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_tap_code = Decoder::<TapCodeDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_tap_code.crack(".. . ... . . ..... . ..... . . .... .... ... .... ... ... . ... . .....", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct TapCodeDecoder;

impl Crack for Decoder<TapCodeDecoder> {
    fn new() -> Decoder<TapCodeDecoder> {
        Decoder {
            name: "Tap code",
            description: "Tap code, sometimes called knock code, is a way to encode and transmit messages on a telegraph or a prison cell. Each letter is transmitted as a pair of tap counts between one and five, encoding its row and column in a 5x5 Polybius square. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Tap_code",
            tags: vec!["tap-code", "polybius", "classical"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Tap code with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let decoded = tap_code_decrypt(text);
        if decoded.is_empty() {
            debug!("Input does not look like a Tap code message");
            return results;
        }

        let checker_result = checker
            .with_sensitivity(Sensitivity::Medium)
            .check(&decoded);
        if checker_result.is_identified || decoded.len() >= 8 {
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&checker_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decrypt a Tap code message into plaintext.
///
/// The message is a sequence of tap groups where each group is 1-5 dots (or
/// other non-space characters) and letter pairs are separated by whitespace.
/// A pair `(row, col)` maps to the letter at that position in the standard
/// Polybius square (rows and columns are 1-indexed). Returns an empty string
/// when the input cannot be decrypted.
pub fn tap_code_decrypt(ciphertext: &str) -> String {
    let groups: Vec<&str> = ciphertext.split_whitespace().collect();
    if groups.is_empty() || !groups.len().is_multiple_of(2) {
        return String::new();
    }

    let mut result = String::with_capacity(groups.len() / 2);
    let mut idx = 0;
    while idx + 1 < groups.len() {
        let row = groups[idx].chars().count();
        let col = groups[idx + 1].chars().count();
        if !(1..=5).contains(&row) || !(1..=5).contains(&col) {
            return String::new();
        }
        result.push(POLYBIUS_ALPHABET[(row - 1) * 5 + (col - 1)]);
        idx += 2;
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str) -> String {
        let mut groups = Vec::new();
        for c in text.chars() {
            let upper = c.to_ascii_uppercase();
            if let Some(pos) = POLYBIUS_ALPHABET.iter().position(|&x| x == upper) {
                let row = pos / 5 + 1;
                let col = pos % 5 + 1;
                groups.push(".".repeat(row));
                groups.push(".".repeat(col));
            }
        }
        groups.join(" ")
    }

    #[test]
    fn test_tap_code_roundtrip() {
        let plaintext = "HELLO";
        let ciphertext = encrypt(plaintext);
        assert_eq!(tap_code_decrypt(&ciphertext), plaintext);
    }

    #[test]
    fn test_tap_code_known_vector() {
        // C = row 1, column 3 => ". ..."  (one dot, three dots)
        assert_eq!(tap_code_decrypt(". ..."), "C");
        // A = (1,1) => "." "."
        assert_eq!(tap_code_decrypt(". ."), "A");
    }

    #[test]
    fn test_tap_code_crack() {
        let plaintext = "ATTACKATDAWN";
        let ciphertext = encrypt(plaintext);
        let tap_code_decoder = Decoder::<TapCodeDecoder>::new();
        let result = tap_code_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Tap code decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_tap_code_empty_input() {
        let tap_code_decoder = Decoder::<TapCodeDecoder>::new();
        let result = tap_code_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_tap_code_odd_group_count() {
        let tap_code_decoder = Decoder::<TapCodeDecoder>::new();
        // Odd number of groups cannot form letter pairs.
        let result = tap_code_decoder
            .crack(". .. ...", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
