//! Decode a Trifid cipher string
//! The Trifid cipher extends the Bifid cipher to three dimensions using a
//! 3x3x3 cube of 27 characters. Each plaintext letter is replaced by its
//! (layer, row, column) coordinates, all layers are written out in order, and
//! the resulting number stream is re-paired into triples to give the
//! ciphertext. Decryption reverses this process with the same cube.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, trace};

/// The standard 27 character Trifid alphabet (A-Z plus a period).
const TRIFID_ALPHABET: [char; 27] = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
    'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '.',
];

/// The Trifid decoder, call:
/// `let trifid_decoder = Decoder::<TrifidDecoder>::new()` to create a new instance
/// And then call:
/// `result = trifid_decoder.crack(input)` to decode a Trifid cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::trifid_decoder::TrifidDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_trifid = Decoder::<TrifidDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_trifid.crack("DKZCJKMMXE", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct TrifidDecoder;

impl Crack for Decoder<TrifidDecoder> {
    fn new() -> Decoder<TrifidDecoder> {
        Decoder {
            name: "Trifid",
            description: "The Trifid cipher is a cipher invented by Felix Delastelle, which extends the concept of the Bifid cipher to a third dimension. Each letter is replaced by three coordinates in a 3x3x3 cube, then the coordinates are transposed. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Trifid_cipher",
            tags: vec!["polybius", "classical", "fractionated", "transposition"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Trifid Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let clean_text: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();
        if clean_text.len() < 9 {
            debug!("Input text too short for Trifid analysis");
            return results;
        }

        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let mut best_result: Option<String> = None;

        for period in 3..=10 {
            if clean_text.len() < period {
                break;
            }
            let decoded = trifid_decrypt(&clean_text, period);
            if decoded.is_empty() {
                continue;
            }
            let check_result = checker_with_sensitivity.check(&decoded);
            if check_result.is_identified {
                results.unencrypted_text = Some(vec![decoded]);
                results.update_checker(&check_result);
                return results;
            }
            if best_result.is_none() {
                best_result = Some(decoded);
            }
        }

        if let Some(decoded) = best_result {
            let check_result = checker_with_sensitivity.check(&decoded);
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&check_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decrypt a Trifid ciphertext using the standard alphabet cube and the given
/// period (block length). Returns an empty string when the input cannot be
/// decrypted.
///
/// # Panics
///
/// This function never panics: letters are checked against the Trifid
/// alphabet before lookup.
pub fn trifid_decrypt(ciphertext: &str, period: usize) -> String {
    let clean: Vec<char> = ciphertext
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .map(|c| c.to_ascii_uppercase())
        .filter(|c| TRIFID_ALPHABET.contains(c))
        .collect();

    if clean.is_empty() {
        return String::new();
    }

    let total = clean.len();
    // Flatten each ciphertext character into its (layer, row, column)
    // coordinate triple.
    let mut coords: Vec<u8> = Vec::with_capacity(total * 3);
    for &c in &clean {
        let Some(pos) = TRIFID_ALPHABET.iter().position(|&x| x == c) else {
            return String::new();
        };
        coords.push((pos / 9 + 1) as u8);
        coords.push(((pos % 9) / 3 + 1) as u8);
        coords.push((pos % 3 + 1) as u8);
    }

    // Within a block of `chunk_len` characters, the first `chunk_len` numbers
    // of the stream are the layers of the plaintext, the next `chunk_len` are
    // the rows, and the last `chunk_len` are the columns.
    let mut result = String::with_capacity(total);
    let mut start = 0;
    while start < total {
        let chunk_len = period.min(total - start);
        for i in 0..chunk_len {
            let layer = coords[start * 3 + i];
            let row = coords[start * 3 + chunk_len + i];
            let col = coords[start * 3 + 2 * chunk_len + i];
            if !(1..=3).contains(&layer) || !(1..=3).contains(&row) || !(1..=3).contains(&col) {
                return String::new();
            }
            let pos = ((layer - 1) * 9 + (row - 1) * 3 + (col - 1)) as usize;
            result.push(TRIFID_ALPHABET[pos]);
        }
        start += chunk_len;
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Encrypt with the standard alphabet cube (helper for roundtrip tests).
    fn encrypt(text: &str, period: usize) -> String {
        let clean: Vec<char> = text
            .chars()
            .map(|c| c.to_ascii_uppercase())
            .filter(|c| TRIFID_ALPHABET.contains(c))
            .collect();
        let mut result = String::with_capacity(clean.len());
        let mut start = 0;
        while start < clean.len() {
            let chunk_len = period.min(clean.len() - start);
            let mut layers = Vec::with_capacity(chunk_len);
            let mut rows = Vec::with_capacity(chunk_len);
            let mut cols = Vec::with_capacity(chunk_len);
            for i in 0..chunk_len {
                let c = clean[start + i];
                let pos = TRIFID_ALPHABET.iter().position(|&x| x == c).unwrap();
                layers.push((pos / 9 + 1) as u8);
                rows.push(((pos % 9) / 3 + 1) as u8);
                cols.push((pos % 3 + 1) as u8);
            }
            let mut stream: Vec<u8> = Vec::with_capacity(chunk_len * 3);
            stream.extend_from_slice(&layers);
            stream.extend_from_slice(&rows);
            stream.extend_from_slice(&cols);
            for i in 0..chunk_len {
                let layer = stream[i * 3];
                let row = stream[i * 3 + 1];
                let col = stream[i * 3 + 2];
                let pos = ((layer - 1) * 9 + (row - 1) * 3 + (col - 1)) as usize;
                result.push(TRIFID_ALPHABET[pos]);
            }
            start += chunk_len;
        }
        result
    }

    #[test]
    fn test_trifid_roundtrip() {
        let plaintext = "FLEEATONCE";
        let period = 3;
        let ciphertext = encrypt(plaintext, period);
        assert_eq!(trifid_decrypt(&ciphertext, period), plaintext);
    }

    #[test]
    fn test_trifid_crack() {
        let plaintext = "FLEEATONCE";
        let ciphertext = encrypt(plaintext, 3);
        let trifid_decoder = Decoder::<TrifidDecoder>::new();
        let result = trifid_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Trifid decoder");
        assert_eq!(result[0], plaintext);
    }

    #[test]
    fn test_trifid_empty_input() {
        let trifid_decoder = Decoder::<TrifidDecoder>::new();
        let result = trifid_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_trifid_short_input() {
        let trifid_decoder = Decoder::<TrifidDecoder>::new();
        let result = trifid_decoder
            .crack("ABC", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
