//! Decode a Two-square cipher string
//! The Two-square cipher (also called the double Playfair) is a digraph
//! substitution cipher invented by Felix Delastelle. It uses two 5x5 squares:
//! a plaintext square holding the standard alphabet and a ciphertext square
//! built from a keyword. Decryption reverses the encryption mapping using the
//! same squares.

use crate::checkers::CheckerTypes;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};
use super::polybius_decoder::POLYBIUS_ALPHABET;

use log::{debug, trace};

/// Common keywords to try when cracking.
const COMMON_KEYS: [&str; 8] = [
    "PLAYFAIR",
    "EXAMPLE",
    "KEYWORD",
    "MONARCHY",
    "SECRET",
    "CRYPTO",
    "CIPHER",
    "DELASTELLE",
];

/// The Two-square decoder, call:
/// `let two_square_decoder = Decoder::<TwoSquareDecoder>::new()` to create a new instance
/// And then call:
/// `result = two_square_decoder.crack(input)` to decode a Two-square cipher string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::two_square_decoder::TwoSquareDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_two_square = Decoder::<TwoSquareDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_two_square.crack("NXMTNXMOKIAP", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct TwoSquareDecoder;

impl Crack for Decoder<TwoSquareDecoder> {
    fn new() -> Decoder<TwoSquareDecoder> {
        Decoder {
            name: "Two-square",
            description: "The Two-square cipher, also called double Playfair, is a manual symmetric encryption technique. It was developed by Felix Delastelle. It encrypts pairs of letters using two 5x5 squares, one of which is built from a keyword. Uses Medium sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Two-square_cipher",
            tags: vec!["polygraphic", "classical", "auto-crack"],
            popularity: 0.25,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Two-square Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let clean_text: String = text.chars().filter(|c| c.is_ascii_alphabetic()).collect();
        if clean_text.len() < 8 || !clean_text.len().is_multiple_of(2) {
            debug!("Input text too short or odd for Two-square analysis");
            return results;
        }

        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Medium);
        let mut best_result: Option<String> = None;

        for &key in &COMMON_KEYS {
            let decoded = two_square_decrypt(&clean_text, key);
            if decoded.is_empty() {
                continue;
            }
            let check_result = checker_with_sensitivity.check(&decoded);
            if check_result.is_identified {
                results.unencrypted_text = Some(vec![decoded]);
                results.update_checker(&check_result);
                results.key = Some(key.to_string());
                return results;
            }
            if best_result.is_none() {
                best_result = Some(decoded);
            }
        }

        if let Some(decoded) = best_result {
            let check_result = checker_with_sensitivity.check(&decoded);
            results.unencrypted_text = Some(vec![decoded]);
            results.update_checker(&check_result);
        }
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }

    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }

    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }

    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Build a 5x5 square from a keyword using the standard alphabet (I/J merged).
fn build_square(keyword: &str) -> [[char; 5]; 5] {
    let mut used = [false; 25];
    let mut square = [[' '; 5]; 5];
    let mut pos = 0;
    for c in keyword.chars().chain(POLYBIUS_ALPHABET.iter().copied()) {
        let upper = c.to_ascii_uppercase();
        let letter = if upper == 'J' { 'I' } else { upper };
        if let Some(idx) = POLYBIUS_ALPHABET.iter().position(|&x| x == letter) {
            if !used[idx] {
                used[idx] = true;
                square[pos / 5][pos % 5] = POLYBIUS_ALPHABET[idx];
                pos += 1;
            }
        }
        if pos == 25 {
            break;
        }
    }
    square
}

/// Find the (row, col) position of a letter in the square.
fn find_pos(square: &[[char; 5]; 5], c: char) -> (usize, usize) {
    for r in 0..5 {
        for col in 0..5 {
            if square[r][col] == c {
                return (r, col);
            }
        }
    }
    panic!("letter {c} not in Two-square square");
}

/// Decrypt a Two-square ciphertext with the keyword. Returns an empty string
/// when the input cannot be decrypted.
pub fn two_square_decrypt(ciphertext: &str, keyword: &str) -> String {
    let clean: Vec<char> = ciphertext
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .map(|c| c.to_ascii_uppercase())
        .map(|c| if c == 'J' { 'I' } else { c })
        .filter(|c| POLYBIUS_ALPHABET.contains(c))
        .collect();
    if clean.len() < 2 || !clean.len().is_multiple_of(2) {
        return String::new();
    }

    let plain_square = build_square("");
    let cipher_square = build_square(keyword);

    let mut result = String::with_capacity(clean.len());
    let mut idx = 0;
    while idx + 1 < clean.len() {
        // Locate the ciphertext letters in the ciphertext square.
        let (r1, c1) = find_pos(&cipher_square, clean[idx]);
        let (r2, c2) = find_pos(&cipher_square, clean[idx + 1]);
        if r1 == r2 || c1 == c2 {
            // Same row or column: read the letters back from the plaintext square.
            result.push(plain_square[r1][c1]);
            result.push(plain_square[r2][c2]);
        } else {
            // Rectangle swap read from the plaintext square.
            result.push(plain_square[r1][c2]);
            result.push(plain_square[r2][c1]);
        }
        idx += 2;
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn encrypt(text: &str, keyword: &str) -> String {
        let clean: Vec<char> = text
            .chars()
            .map(|c| c.to_ascii_uppercase())
            .map(|c| if c == 'J' { 'I' } else { c })
            .filter(|c| POLYBIUS_ALPHABET.contains(c))
            .collect();
        let plain_square = build_square("");
        let cipher_square = build_square(keyword);
        let mut result = String::new();
        let mut idx = 0;
        while idx + 1 < clean.len() {
            let (r1, c1) = find_pos(&plain_square, clean[idx]);
            let (r2, c2) = find_pos(&plain_square, clean[idx + 1]);
            if r1 == r2 || c1 == c2 {
                result.push(cipher_square[r1][c1]);
                result.push(cipher_square[r2][c2]);
            } else {
                result.push(cipher_square[r1][c2]);
                result.push(cipher_square[r2][c1]);
            }
            idx += 2;
        }
        result
    }

    #[test]
    fn test_two_square_roundtrip() {
        let plaintext = "HELLOWORLD";
        let keyword = "EXAMPLE";
        let ciphertext = encrypt(plaintext, keyword);
        assert_eq!(two_square_decrypt(&ciphertext, keyword), plaintext);
    }

    #[test]
    fn test_two_square_crack() {
        let plaintext = "MEETMEATONCE";
        let keyword = "EXAMPLE";
        let ciphertext = encrypt(plaintext, keyword);
        let two_square_decoder = Decoder::<TwoSquareDecoder>::new();
        let result = two_square_decoder
            .crack(&ciphertext, &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for Two-square decoder");
        assert_eq!(result[0].trim(), plaintext);
    }

    #[test]
    fn test_two_square_empty_input() {
        let two_square_decoder = Decoder::<TwoSquareDecoder>::new();
        let result = two_square_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn test_two_square_short_input() {
        let two_square_decoder = Decoder::<TwoSquareDecoder>::new();
        let result = two_square_decoder
            .crack("AB", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
