//! Decode Unicode escape sequences such as `\u0048`, `\u{48}`, `\U00000048`.
//!
//! Call `unicode_escape_decoder.crack` to use. It returns option<String> and
//! check with `result.is_some()` to see if it returned okay.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Unicode escape decoder, call:
/// `let unicode_escape_decoder = Decoder::<UnicodeEscapeDecoder>::new()` to create a new instance
/// And then call:
/// `result = unicode_escape_decoder.crack(input)` to decode
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::unicode_escape_decoder::UnicodeEscapeDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_unicode = Decoder::<UnicodeEscapeDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_unicode.crack("\\u0048\\u0069", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "Hi");
/// ```
pub struct UnicodeEscapeDecoder;

impl Crack for Decoder<UnicodeEscapeDecoder> {
    fn new() -> Decoder<UnicodeEscapeDecoder> {
        Decoder {
            name: "Unicode escape",
            description: "Unicode escape sequences represent Unicode code points as ASCII text. Common forms are \\uXXXX (4 hex digits), \\UXXXXXXXX (8 hex digits) and \\u{...}. They are used in JSON, Java, Python and C/C++ source code and are a frequent CTF obfuscation technique.",
            link: "https://en.wikipedia.org/wiki/Unicode_escape",
            tags: vec!["unicode", "escape", "text", "decoder"],
            popularity: 0.6,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Unicode escape with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let decoded_text = decode_unicode_escapes(text);

        if decoded_text.is_none() {
            debug!("Failed to decode unicode escapes because decode_unicode_escapes returned None");
            return results;
        }

        let decoded_text = decoded_text.unwrap();
        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode unicode escape because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode Unicode escape sequences. Only succeeds if at least one sequence was
/// replaced.
fn decode_unicode_escapes(text: &str) -> Option<String> {
    let chars: Vec<char> = text.chars().collect();
    let mut out = String::with_capacity(text.len());
    let mut i = 0;
    let mut replaced = false;

    while i < chars.len() {
        if chars[i] == '\\' && i + 1 < chars.len() {
            if let Some((decoded, next_i)) = parse_escape(&chars, i) {
                out.push(decoded);
                replaced = true;
                i = next_i;
                continue;
            }
        }
        out.push(chars[i]);
        i += 1;
    }

    if replaced {
        Some(out)
    } else {
        None
    }
}

/// Try to parse a unicode escape starting at `chars[start]` (which must be `\`).
/// Returns the decoded char and the index just past the escape.
fn parse_escape(chars: &[char], start: usize) -> Option<(char, usize)> {
    let n = chars.len();
    // \u{...} or \uXXXX or \UXXXXXXXX
    match chars.get(start + 1) {
        Some('u') => {
            if chars.get(start + 2) == Some(&'{') {
                // \u{HEX}
                let close = chars[start + 3..].iter().position(|&c| c == '}')?;
                let hex: String = chars[start + 3..start + 3 + close].iter().collect();
                let code = u32::from_str_radix(&hex, 16).ok()?;
                let c = char::from_u32(code)?;
                Some((c, start + 3 + close + 1))
            } else {
                // \uXXXX
                if start + 6 > n {
                    return None;
                }
                let hex: String = chars[start + 2..start + 6].iter().collect();
                let code = u32::from_str_radix(&hex, 16).ok()?;
                let c = char::from_u32(code)?;
                Some((c, start + 6))
            }
        }
        Some('U') => {
            // \UXXXXXXXX (8 hex digits)
            if start + 10 > n {
                return None;
            }
            let hex: String = chars[start + 2..start + 10].iter().collect();
            let code = u32::from_str_radix(&hex, 16).ok()?;
            let c = char::from_u32(code)?;
            Some((c, start + 10))
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::UnicodeEscapeDecoder;
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    #[test]
    fn successful_decoding_4_hex() {
        let decoder = Decoder::<UnicodeEscapeDecoder>::new();
        let result = decoder.crack("\\u0048\\u0069", &get_athena_checker());
        let decoded_str = &result
            .unencrypted_text
            .expect("No unencrypted text for unicode escape");
        assert_eq!(decoded_str[0], "Hi");
    }

    #[test]
    fn successful_decoding_8_hex() {
        let decoder = Decoder::<UnicodeEscapeDecoder>::new();
        let result = decoder.crack("\\U00000048\\U00000069", &get_athena_checker());
        let decoded_str = &result
            .unencrypted_text
            .expect("No unencrypted text for unicode escape");
        assert_eq!(decoded_str[0], "Hi");
    }

    #[test]
    fn successful_decoding_braced() {
        let decoder = Decoder::<UnicodeEscapeDecoder>::new();
        let result = decoder.crack("\\u{48}\\u{69}", &get_athena_checker());
        let decoded_str = &result
            .unencrypted_text
            .expect("No unencrypted text for unicode escape");
        assert_eq!(decoded_str[0], "Hi");
    }

    #[test]
    fn no_escapes_returns_none() {
        let decoder = Decoder::<UnicodeEscapeDecoder>::new();
        let result = decoder
            .crack("plain text without escapes", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
