//! Brute-force decode a single-byte XOR cipher.
//!
//! For each of the 256 possible key bytes the ciphertext is XOR'd byte-by-byte
//! and the result is scored with a frequency-based English model (bigrams +
//! printable character weighting). The best scoring candidate is then run
//! through the checker. This is one of the most common CTF challenge types.
//!
//! Call `xor_single_byte_decoder.crack` to use. It returns option<String> and
//! check with `result.is_some()` to see if it returned okay.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use crate::storage::load_english_bigrams;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The xor single byte decoder, call:
/// `let xor_decoder = Decoder::<XorSingleByteDecoder>::new()` to create a new instance
/// And then call:
/// `result = xor_decoder.crack(input)` to decode a xor string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::xor_single_byte_decoder::XorSingleByteDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_xor = Decoder::<XorSingleByteDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_xor.crack("1b37373331363f78151b7f2b783431333d78397828372d363c78373e783a393b3736", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct XorSingleByteDecoder;

impl Crack for Decoder<XorSingleByteDecoder> {
    fn new() -> Decoder<XorSingleByteDecoder> {
        Decoder {
            name: "xor-single-byte",
            description: "XOR is a simple bitwise operation used in many ciphers. A single-byte XOR cipher XORs every byte of the plaintext with the same key byte. Because there are only 256 possible keys it can be brute-forced, scoring each candidate against an English frequency model. This is one of the most common CTF challenge types.",
            link: "https://en.wikipedia.org/wiki/XOR_cipher",
            tags: vec!["xor", "crypto", "auto-crack", "brute-force"],
            popularity: 0.9,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying XorSingleByte with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        // The input is almost always hex-encoded ciphertext.
        let bytes = match hex_decode(text) {
            Some(bytes) => bytes,
            None => {
                debug!("Failed to hex-decode input for xor-single-byte");
                return results;
            }
        };

        if bytes.is_empty() {
            debug!("Empty input for xor-single-byte");
            return results;
        }

        let bigrams = load_english_bigrams();

        let mut best_score = f64::NEG_INFINITY;
        let mut best_plaintext: Option<Vec<u8>> = None;
        let mut best_key: u8 = 0;

        for key in 0..=255u16 {
            let candidate: Vec<u8> = bytes.iter().map(|b| b ^ (key as u8)).collect();
            let score = score_plaintext(&candidate, &bigrams);
            if score > best_score {
                best_score = score;
                best_plaintext = Some(candidate);
                best_key = key as u8;
            }
        }

        let Some(candidate) = best_plaintext else {
            return results;
        };

        let Ok(decoded_text) = String::from_utf8(candidate) else {
            debug!("Best XOR candidate is not valid UTF-8");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode xor-single-byte because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);
        results.key = Some(format!("{:#04x} (0x{:02x})", best_key, best_key));

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode a hex string into bytes, tolerating whitespace and an optional 0x
/// prefix. Returns None on failure.
pub(crate) fn hex_decode(text: &str) -> Option<Vec<u8>> {
    let cleaned: String = text.chars().filter(|c| !c.is_whitespace()).collect();
    let cleaned = cleaned.strip_prefix("0x").unwrap_or(&cleaned);

    if !cleaned.len().is_multiple_of(2) {
        return None;
    }
    if !cleaned.bytes().all(|b| b.is_ascii_hexdigit()) {
        return None;
    }

    let mut bytes = Vec::with_capacity(cleaned.len() / 2);
    let encoded = cleaned.as_bytes();
    for i in (0..cleaned.len()).step_by(2) {
        let hi = (encoded[i] as char).to_digit(16)?;
        let lo = (encoded[i + 1] as char).to_digit(16)?;
        bytes.push(((hi << 4) | lo) as u8);
    }
    Some(bytes)
}

/// Score a candidate plaintext with an English bigram model plus printable
/// character weighting. Higher is better.
fn score_plaintext(bytes: &[u8], bigrams: &std::collections::HashMap<(char, char), f64>) -> f64 {
    if bytes.is_empty() {
        return f64::NEG_INFINITY;
    }

    let mut score = 0.0;

    for &b in bytes {
        match b {
            b'a'..=b'z' | b'A'..=b'Z' => score += 0.8,
            b' ' => score += 0.4,
            b'0'..=b'9' => score += 0.2,
            0x09 | 0x0a | 0x0d => score += 0.1,
            // Remaining printable punctuation, excluding letters/digits/space.
            b'!'..=b'/' | b':'..=b'@' | b'['..=b'`' | b'{'..=b'~' => score += 0.05,
            // Control characters / extended bytes strongly suggest a wrong key.
            _ => score -= 2.0,
        }
    }

    // Bigram scoring over lowercase letters, including spaces as word separators.
    let lower: Vec<char> = bytes
        .iter()
        .map(|&b| {
            let c = b as char;
            if c.is_ascii_alphabetic() {
                c.to_ascii_lowercase()
            } else if c == ' ' {
                ' '
            } else {
                '\0'
            }
        })
        .collect();

    for pair in lower.windows(2) {
        if let (Some(&left), Some(&right)) = (pair.first(), pair.last()) {
            if left != '\0' && right != '\0' {
                if let Some(&prob) = bigrams.get(&(left, right)) {
                    score += (prob * 100.0).ln_1p();
                }
            }
        }
    }

    score
}

#[cfg(test)]
mod tests {
    use super::XorSingleByteDecoder;
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    #[test]
    fn test_hex_decode() {
        assert_eq!(super::hex_decode("48656c6c6f"), Some(b"Hello".to_vec()));
        assert_eq!(super::hex_decode("0x48656c6c6f"), Some(b"Hello".to_vec()));
        assert_eq!(super::hex_decode("48 65 6c 6c 6f"), Some(b"Hello".to_vec()));
        assert_eq!(super::hex_decode("xyz"), None);
        assert_eq!(super::hex_decode("abc"), None);
    }

    #[test]
    fn successful_decoding() {
        // Classic Matasano single-byte XOR challenge.
        let xor_decoder = Decoder::<XorSingleByteDecoder>::new();
        let result = xor_decoder.crack(
            "1b37373331363f78151b7f2b783431333d78397828372d363c78373e783a393b3736",
            &get_athena_checker(),
        );
        let decoded = result.unencrypted_text.expect("failed to decode");
        assert_eq!(
            decoded[0].to_lowercase(),
            "cooking mc's like a pound of bacon"
        );
    }

    #[test]
    fn successful_decoding_plain_text() {
        let xor_decoder = Decoder::<XorSingleByteDecoder>::new();
        let result = xor_decoder.crack("attack at dawn", &get_athena_checker());
        assert!(
            result.unencrypted_text.is_none(),
            "Plain text should not be accepted as hex"
        );
    }

    #[test]
    fn xor_decode_empty_string() {
        let xor_decoder = Decoder::<XorSingleByteDecoder>::new();
        let result = xor_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
