//! Automatically crack a repeating-key XOR cipher (the XOR analogue of the
//! Vigenère cipher).
//!
//! The algorithm:
//!   1. Estimate the key length with the Kasiski examination (repeated byte
//!      sequences reveal the period) combined with the Index of Coincidence.
//!   2. Transpose the ciphertext into `key_len` columns, each column XOR'd
//!      with a single key byte.
//!   3. Recover each key byte via single-byte XOR frequency analysis.
//!   4. Decrypt and run the result through the checker.
//!
//! Call `xor_repeating_decoder.crack` to use. It returns option<String> and
//! check with `result.is_some()` to see if it returned okay.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use crate::storage::load_english_bigrams;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;
use super::xor_single_byte_decoder::hex_decode;

use log::{debug, info, trace};

/// The xor repeating decoder, call:
/// `let xor_decoder = Decoder::<XorRepeatingDecoder>::new()` to create a new instance
/// And then call:
/// `result = xor_decoder.crack(input)` to decode a xor string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::xor_repeating_decoder::XorRepeatingDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_xor = Decoder::<XorRepeatingDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_xor.crack("1b37373331363f78151b7f2b783431333d78397828372d363c78373e783a393b3736", &checker).unencrypted_text;
/// assert!(result.is_some());
/// ```
pub struct XorRepeatingDecoder;

impl Crack for Decoder<XorRepeatingDecoder> {
    fn new() -> Decoder<XorRepeatingDecoder> {
        Decoder {
            name: "xor-repeating",
            description: "A repeating-key XOR cipher XORs each plaintext byte with a key byte, cycling through a key of length N. It is the XOR analogue of the Vigenère cipher. The key length can be recovered with the Kasiski examination and the Index of Coincidence, after which each key byte is recovered via single-byte frequency analysis.",
            link: "https://en.wikipedia.org/wiki/Vigen%C3%A8re_cipher",
            tags: vec!["xor", "crypto", "auto-crack", "brute-force"],
            popularity: 0.85,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying XorRepeating with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let bytes = match hex_decode(text) {
            Some(bytes) => bytes,
            None => {
                debug!("Failed to hex-decode input for xor-repeating");
                return results;
            }
        };

        if bytes.len() < 8 {
            debug!("Input too short for xor-repeating");
            return results;
        }

        let bigrams = load_english_bigrams();
        let key_len = estimate_key_length(&bytes);

        if key_len < 1 || key_len > bytes.len() {
            debug!("Invalid key length {} for xor-repeating", key_len);
            return results;
        }

        // Recover each key byte from its transposed column.
        let mut key = Vec::with_capacity(key_len);
        for col in 0..key_len {
            let column: Vec<u8> = bytes.iter().skip(col).step_by(key_len).copied().collect();
            if let Some((k, _score)) = recover_single_byte_key(&column, &bigrams) {
                key.push(k);
            } else {
                debug!("Failed to recover key byte at column {}", col);
                return results;
            }
        }

        let decoded_bytes: Vec<u8> = bytes
            .iter()
            .enumerate()
            .map(|(i, &b)| b ^ key[i % key.len()])
            .collect();

        let Ok(decoded_text) = String::from_utf8(decoded_bytes) else {
            debug!("Decrypted xor-repeating output is not valid UTF-8");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode xor-repeating because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);
        results.key = Some(
            key.iter()
                .map(|k| format!("{:02x}", k))
                .collect::<Vec<_>>()
                .join(" "),
        );

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Estimate the repeating-key length via Kasiski examination + Index of
/// Coincidence. Returns the most likely key length between 2 and 40.
fn estimate_key_length(bytes: &[u8]) -> usize {
    // Kasiski: distances between repeated 3-byte sequences share the key
    // length as a factor. Collect candidate factors.
    let mut factors: Vec<usize> = Vec::new();
    let min_run = 3;
    if bytes.len() > 2 * min_run {
        for i in 0..bytes.len() - min_run {
            let seq = &bytes[i..i + min_run];
            let mut j = i + min_run;
            while j + min_run <= bytes.len() {
                if &bytes[j..j + min_run] == seq {
                    let distance = j - i;
                    let mut d = 1;
                    while d * d <= distance {
                        if distance % d == 0 {
                            factors.push(d);
                            factors.push(distance / d);
                        }
                        d += 1;
                    }
                    break;
                }
                j += 1;
            }
        }
    }

    // Fall back to Index of Coincidence scoring over a range of key lengths
    // if Kasiski did not find any repeated sequences.
    let mut best_len = 0;
    let mut best_ic_avg = f64::INFINITY;
    for candidate in 2..=40usize.min(bytes.len()) {
        let ic = average_ic(bytes, candidate);
        let expected_ic = english_expected_ic(candidate);
        let delta = (ic - expected_ic).abs();
        if delta < best_ic_avg {
            best_ic_avg = delta;
            best_len = candidate;
        }
    }

    // If Kasiski found factors, prefer the factor closest to the IC result.
    if !factors.is_empty() {
        let mut best_factor = factors[0];
        let mut best_factor_dist = usize::MAX;
        for &f in &factors {
            if f < 2 {
                continue;
            }
            let dist = (f as isize - best_len as isize).unsigned_abs();
            if dist < best_factor_dist {
                best_factor_dist = dist;
                best_factor = f;
            }
        }
        best_len = best_factor;
    }

    best_len.clamp(1, 40)
}

/// Average Index of Coincidence for a given key length. Random text gives
/// ~0.038, real text ~0.066 for each column.
fn average_ic(bytes: &[u8], key_len: usize) -> f64 {
    let mut total = 0.0;
    let mut count = 0.0;
    for col in 0..key_len {
        let column: Vec<u8> = bytes.iter().skip(col).step_by(key_len).copied().collect();
        if column.len() < 2 {
            continue;
        }
        let mut freq = [0u32; 256];
        for &b in &column {
            freq[b as usize] += 1;
        }
        let n = column.len() as f64;
        let mut numerator = 0.0;
        for &c in freq.iter() {
            numerator += (c as f64) * (c as f64 - 1.0);
        }
        total += numerator / (n * (n - 1.0));
        count += 1.0;
    }
    if count == 0.0 {
        0.0
    } else {
        total / count
    }
}

/// Expected average Index of Coincidence for English text XOR'd with a key of
/// the given length. This is a rough heuristic: ~0.066 for a single column.
fn english_expected_ic(key_len: usize) -> f64 {
    // Random byte uniform IC is 1/256 = 0.0039 per column; but ciphertext here
    // is English XOR key.  The exact expected value varies, so we use a
    // monotonic approximation: IC grows as the key length decreases toward 1.
    0.066 + 0.0039 * (key_len as f64)
}

/// Recover the single byte key for a column of bytes (all XOR'd with the same
/// key byte) using English frequency scoring.
fn recover_single_byte_key(
    column: &[u8],
    bigrams: &std::collections::HashMap<(char, char), f64>,
) -> Option<(u8, f64)> {
    let mut best_key: u8 = 0;
    let mut best_score = f64::NEG_INFINITY;

    for key in 0..=255u16 {
        let candidate: Vec<u8> = column.iter().map(|b| b ^ (key as u8)).collect();
        let score = score_plaintext(&candidate, bigrams);
        if score > best_score {
            best_score = score;
            best_key = key as u8;
        }
    }

    if best_score == f64::NEG_INFINITY {
        None
    } else {
        Some((best_key, best_score))
    }
}

/// Score a candidate plaintext with an English bigram model plus printable
/// character weighting. Higher is better.
fn score_plaintext(bytes: &[u8], bigrams: &std::collections::HashMap<(char, char), f64>) -> f64 {
    if bytes.is_empty() {
        return f64::NEG_INFINITY;
    }

    let mut score = 0.0;

    for &b in bytes {
        match b {
            b'a'..=b'z' | b'A'..=b'Z' => score += 0.8,
            b' ' => score += 0.4,
            b'0'..=b'9' => score += 0.2,
            0x09 | 0x0a | 0x0d => score += 0.1,
            // Remaining printable punctuation, excluding letters/digits/space.
            b'!'..=b'/' | b':'..=b'@' | b'['..=b'`' | b'{'..=b'~' => score += 0.05,
            _ => score -= 2.0,
        }
    }

    let lower: Vec<char> = bytes
        .iter()
        .map(|&b| {
            let c = b as char;
            if c.is_ascii_alphabetic() {
                c.to_ascii_lowercase()
            } else if c == ' ' {
                ' '
            } else {
                '\0'
            }
        })
        .collect();

    for pair in lower.windows(2) {
        if let (Some(&left), Some(&right)) = (pair.first(), pair.last()) {
            if left != '\0' && right != '\0' {
                if let Some(&prob) = bigrams.get(&(left, right)) {
                    score += (prob * 100.0).ln_1p();
                }
            }
        }
    }

    score
}

#[cfg(test)]
mod tests {
    use super::XorRepeatingDecoder;
    use crate::decoders::xor_single_byte_decoder::hex_decode;
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn repeating_xor(plaintext: &[u8], key: &[u8]) -> String {
        plaintext
            .iter()
            .enumerate()
            .map(|(i, &b)| b ^ key[i % key.len()])
            .map(|b| format!("{:02x}", b))
            .collect()
    }

    #[test]
    fn test_estimate_key_length() {
        let plaintext =
            b"Burning 'em, if you ain't quick and nimble I go crazy when I hear a cymbal";
        let key = b"ICE";
        let ciphertext = hex_decode(&repeating_xor(plaintext, key)).unwrap();
        let estimated = super::estimate_key_length(&ciphertext);
        assert_eq!(estimated, 3);
    }

    #[test]
    fn successful_decoding_ice() {
        // Classic Matasano challenge 5/6 repeating-key XOR.
        let plaintext =
            b"Burning 'em, if you ain't quick and nimble I go crazy when I hear a cymbal";
        let key = b"ICE";
        let input = repeating_xor(plaintext, key);

        let xor_decoder = Decoder::<XorRepeatingDecoder>::new();
        let result = xor_decoder.crack(&input, &get_athena_checker());
        let decoded = result.unencrypted_text.expect("failed to decode");
        assert_eq!(decoded[0].as_bytes(), plaintext);
    }

    #[test]
    fn xor_decode_empty_string() {
        let xor_decoder = Decoder::<XorRepeatingDecoder>::new();
        let result = xor_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }
}
