//! Decode XXencode text.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::{Crack, Decoder};

use log::{debug, info, trace};

/// The XXencode alphabet.
const XX_ALPHABET: &[u8; 64] = b"+-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

/// The XXencode decoder, call:
/// `let xxencode_decoder = Decoder::<XxencodeDecoder>::new()` to create a new instance
/// And then call:
/// `result = xxencode_decoder.crack(input)` to decode XXencoded text
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::xxencode_decoder::XxencodeDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_xxencode = Decoder::<XxencodeDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_xxencode.crack("9O4JgP4wURqxmP4E+", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct XxencodeDecoder;

impl Crack for Decoder<XxencodeDecoder> {
    fn new() -> Decoder<XxencodeDecoder> {
        Decoder {
            name: "XXencode",
            description: "XXencode is a uuencode-like binary-to-text format with a different 64-character alphabet. It appears in legacy transfer formats and CTF challenges.",
            link: "https://en.wikipedia.org/wiki/Xxencoding",
            tags: vec!["xxencode", "xxe", "encoding", "decoder", "ctf"],
            popularity: 0.7,
            phantom: std::marker::PhantomData,
        }
    }

    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying XXencode with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_xxencode_no_error_handling(text) else {
            debug!("Failed to decode xxencode");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!("Failed to decode xxencode because check_string_success returned false");
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);
        results
    }

    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }

    fn get_name(&self) -> &str {
        self.name
    }

    fn get_description(&self) -> &str {
        self.description
    }

    fn get_link(&self) -> &str {
        self.link
    }

    fn get_popularity(&self) -> f32 {
        self.popularity
    }
}

/// Decode XXencode into UTF-8 text. Accepts raw encoded lines and begin/end blocks.
fn decode_xxencode_no_error_handling(text: &str) -> Option<String> {
    let mut bytes = Vec::new();
    let mut saw_data = false;

    for raw_line in text.lines() {
        let line = raw_line.trim_end_matches('\r');
        if line.is_empty() || line.starts_with("begin ") || line == "end" {
            continue;
        }

        let line_bytes = line.as_bytes();
        let expected = xx_value(*line_bytes.first()?)? as usize;
        if expected == 0 {
            continue;
        }

        let mut line_out = Vec::with_capacity(expected);
        for chunk in line_bytes[1..].chunks(4) {
            if chunk.len() < 2 {
                return None;
            }
            let a = xx_value(chunk[0])?;
            let b = xx_value(chunk[1])?;
            let c = chunk.get(2).map_or(Some(0), |byte| xx_value(*byte))?;
            let d = chunk.get(3).map_or(Some(0), |byte| xx_value(*byte))?;

            line_out.push((a << 2) | (b >> 4));
            if line_out.len() < expected {
                line_out.push((b << 4) | (c >> 2));
            }
            if line_out.len() < expected {
                line_out.push((c << 6) | d);
            }
        }

        if line_out.len() < expected {
            return None;
        }
        bytes.extend_from_slice(&line_out[..expected]);
        saw_data = true;
    }

    if saw_data {
        String::from_utf8(bytes).ok()
    } else {
        None
    }
}

/// Convert an XXencode byte to its 6-bit value.
fn xx_value(byte: u8) -> Option<u8> {
    XX_ALPHABET
        .iter()
        .position(|&candidate| candidate == byte)
        .map(|idx| idx as u8)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };

    fn get_athena_checker() -> CheckerTypes {
        CheckerTypes::CheckAthena(Checker::<Athena>::new())
    }

    #[test]
    fn successful_decoding() {
        let decoder = Decoder::<XxencodeDecoder>::new();
        let result = decoder
            .crack("9O4JgP4wURqxmP4E+", &get_athena_checker())
            .unencrypted_text
            .expect("No unencrypted text for xxencode");
        assert_eq!(result[0], "hello world");
    }

    #[test]
    fn decodes_wrapped_block() {
        let input = "begin 644 hello.txt\n9O4JgP4wURqxmP4E+\n+\nend";
        assert_eq!(
            decode_xxencode_no_error_handling(input),
            Some("hello world".to_string())
        );
    }

    #[test]
    fn invalid_character_returns_none() {
        assert!(decode_xxencode_no_error_handling("9O4Jg_").is_none());
    }
}
